
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `AlumniRegistration` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AlumniRegistration
 * Public alumni registration submissions (exportable by admin).
 */
export type AlumniRegistrationModel = runtime.Types.Result.DefaultSelection<Prisma.$AlumniRegistrationPayload>

export type AggregateAlumniRegistration = {
  _count: AlumniRegistrationCountAggregateOutputType | null
  _avg: AlumniRegistrationAvgAggregateOutputType | null
  _sum: AlumniRegistrationSumAggregateOutputType | null
  _min: AlumniRegistrationMinAggregateOutputType | null
  _max: AlumniRegistrationMaxAggregateOutputType | null
}

export type AlumniRegistrationAvgAggregateOutputType = {
  yearOfAdmission: number | null
  yearOfGraduation: number | null
}

export type AlumniRegistrationSumAggregateOutputType = {
  yearOfAdmission: number | null
  yearOfGraduation: number | null
}

export type AlumniRegistrationMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  fullName: string | null
  gender: string | null
  dateOfBirth: Date | null
  profilePhoto: string | null
  email: string | null
  mobileNumber: string | null
  alternatePhone: string | null
  currentAddress: string | null
  cityStateCountry: string | null
  courseProgram: string | null
  department: string | null
  yearOfAdmission: number | null
  yearOfGraduation: number | null
  enrollmentRollNumber: string | null
  currentOccupation: string | null
  companyOrganizationName: string | null
  jobTitle: string | null
  workLocation: string | null
  yearsOfExperience: string | null
  linkedInProfile: string | null
  socialMedia: string | null
  personalWebsite: string | null
  willingToMentor: boolean | null
  interestedInEvents: boolean | null
  areasOfInterest: string | null
  achievementsAwards: string | null
  suggestionsFeedback: string | null
  messageToInstitution: string | null
  declarationAccepted: boolean | null
  ipAddress: string | null
  userAgent: string | null
}

export type AlumniRegistrationMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  fullName: string | null
  gender: string | null
  dateOfBirth: Date | null
  profilePhoto: string | null
  email: string | null
  mobileNumber: string | null
  alternatePhone: string | null
  currentAddress: string | null
  cityStateCountry: string | null
  courseProgram: string | null
  department: string | null
  yearOfAdmission: number | null
  yearOfGraduation: number | null
  enrollmentRollNumber: string | null
  currentOccupation: string | null
  companyOrganizationName: string | null
  jobTitle: string | null
  workLocation: string | null
  yearsOfExperience: string | null
  linkedInProfile: string | null
  socialMedia: string | null
  personalWebsite: string | null
  willingToMentor: boolean | null
  interestedInEvents: boolean | null
  areasOfInterest: string | null
  achievementsAwards: string | null
  suggestionsFeedback: string | null
  messageToInstitution: string | null
  declarationAccepted: boolean | null
  ipAddress: string | null
  userAgent: string | null
}

export type AlumniRegistrationCountAggregateOutputType = {
  id: number
  createdAt: number
  fullName: number
  gender: number
  dateOfBirth: number
  profilePhoto: number
  email: number
  mobileNumber: number
  alternatePhone: number
  currentAddress: number
  cityStateCountry: number
  courseProgram: number
  department: number
  yearOfAdmission: number
  yearOfGraduation: number
  enrollmentRollNumber: number
  currentOccupation: number
  companyOrganizationName: number
  jobTitle: number
  workLocation: number
  yearsOfExperience: number
  linkedInProfile: number
  socialMedia: number
  personalWebsite: number
  willingToMentor: number
  interestedInEvents: number
  areasOfInterest: number
  achievementsAwards: number
  suggestionsFeedback: number
  messageToInstitution: number
  declarationAccepted: number
  ipAddress: number
  userAgent: number
  _all: number
}


export type AlumniRegistrationAvgAggregateInputType = {
  yearOfAdmission?: true
  yearOfGraduation?: true
}

export type AlumniRegistrationSumAggregateInputType = {
  yearOfAdmission?: true
  yearOfGraduation?: true
}

export type AlumniRegistrationMinAggregateInputType = {
  id?: true
  createdAt?: true
  fullName?: true
  gender?: true
  dateOfBirth?: true
  profilePhoto?: true
  email?: true
  mobileNumber?: true
  alternatePhone?: true
  currentAddress?: true
  cityStateCountry?: true
  courseProgram?: true
  department?: true
  yearOfAdmission?: true
  yearOfGraduation?: true
  enrollmentRollNumber?: true
  currentOccupation?: true
  companyOrganizationName?: true
  jobTitle?: true
  workLocation?: true
  yearsOfExperience?: true
  linkedInProfile?: true
  socialMedia?: true
  personalWebsite?: true
  willingToMentor?: true
  interestedInEvents?: true
  areasOfInterest?: true
  achievementsAwards?: true
  suggestionsFeedback?: true
  messageToInstitution?: true
  declarationAccepted?: true
  ipAddress?: true
  userAgent?: true
}

export type AlumniRegistrationMaxAggregateInputType = {
  id?: true
  createdAt?: true
  fullName?: true
  gender?: true
  dateOfBirth?: true
  profilePhoto?: true
  email?: true
  mobileNumber?: true
  alternatePhone?: true
  currentAddress?: true
  cityStateCountry?: true
  courseProgram?: true
  department?: true
  yearOfAdmission?: true
  yearOfGraduation?: true
  enrollmentRollNumber?: true
  currentOccupation?: true
  companyOrganizationName?: true
  jobTitle?: true
  workLocation?: true
  yearsOfExperience?: true
  linkedInProfile?: true
  socialMedia?: true
  personalWebsite?: true
  willingToMentor?: true
  interestedInEvents?: true
  areasOfInterest?: true
  achievementsAwards?: true
  suggestionsFeedback?: true
  messageToInstitution?: true
  declarationAccepted?: true
  ipAddress?: true
  userAgent?: true
}

export type AlumniRegistrationCountAggregateInputType = {
  id?: true
  createdAt?: true
  fullName?: true
  gender?: true
  dateOfBirth?: true
  profilePhoto?: true
  email?: true
  mobileNumber?: true
  alternatePhone?: true
  currentAddress?: true
  cityStateCountry?: true
  courseProgram?: true
  department?: true
  yearOfAdmission?: true
  yearOfGraduation?: true
  enrollmentRollNumber?: true
  currentOccupation?: true
  companyOrganizationName?: true
  jobTitle?: true
  workLocation?: true
  yearsOfExperience?: true
  linkedInProfile?: true
  socialMedia?: true
  personalWebsite?: true
  willingToMentor?: true
  interestedInEvents?: true
  areasOfInterest?: true
  achievementsAwards?: true
  suggestionsFeedback?: true
  messageToInstitution?: true
  declarationAccepted?: true
  ipAddress?: true
  userAgent?: true
  _all?: true
}

export type AlumniRegistrationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AlumniRegistration to aggregate.
   */
  where?: Prisma.AlumniRegistrationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AlumniRegistrations to fetch.
   */
  orderBy?: Prisma.AlumniRegistrationOrderByWithRelationInput | Prisma.AlumniRegistrationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AlumniRegistrationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AlumniRegistrations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AlumniRegistrations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AlumniRegistrations
  **/
  _count?: true | AlumniRegistrationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AlumniRegistrationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AlumniRegistrationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AlumniRegistrationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AlumniRegistrationMaxAggregateInputType
}

export type GetAlumniRegistrationAggregateType<T extends AlumniRegistrationAggregateArgs> = {
      [P in keyof T & keyof AggregateAlumniRegistration]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAlumniRegistration[P]>
    : Prisma.GetScalarType<T[P], AggregateAlumniRegistration[P]>
}




export type AlumniRegistrationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AlumniRegistrationWhereInput
  orderBy?: Prisma.AlumniRegistrationOrderByWithAggregationInput | Prisma.AlumniRegistrationOrderByWithAggregationInput[]
  by: Prisma.AlumniRegistrationScalarFieldEnum[] | Prisma.AlumniRegistrationScalarFieldEnum
  having?: Prisma.AlumniRegistrationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AlumniRegistrationCountAggregateInputType | true
  _avg?: AlumniRegistrationAvgAggregateInputType
  _sum?: AlumniRegistrationSumAggregateInputType
  _min?: AlumniRegistrationMinAggregateInputType
  _max?: AlumniRegistrationMaxAggregateInputType
}

export type AlumniRegistrationGroupByOutputType = {
  id: string
  createdAt: Date
  fullName: string
  gender: string
  dateOfBirth: Date
  profilePhoto: string | null
  email: string
  mobileNumber: string
  alternatePhone: string | null
  currentAddress: string
  cityStateCountry: string
  courseProgram: string
  department: string
  yearOfAdmission: number
  yearOfGraduation: number
  enrollmentRollNumber: string
  currentOccupation: string
  companyOrganizationName: string | null
  jobTitle: string | null
  workLocation: string | null
  yearsOfExperience: string | null
  linkedInProfile: string | null
  socialMedia: string | null
  personalWebsite: string | null
  willingToMentor: boolean
  interestedInEvents: boolean
  areasOfInterest: string | null
  achievementsAwards: string | null
  suggestionsFeedback: string | null
  messageToInstitution: string | null
  declarationAccepted: boolean
  ipAddress: string | null
  userAgent: string | null
  _count: AlumniRegistrationCountAggregateOutputType | null
  _avg: AlumniRegistrationAvgAggregateOutputType | null
  _sum: AlumniRegistrationSumAggregateOutputType | null
  _min: AlumniRegistrationMinAggregateOutputType | null
  _max: AlumniRegistrationMaxAggregateOutputType | null
}

type GetAlumniRegistrationGroupByPayload<T extends AlumniRegistrationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AlumniRegistrationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AlumniRegistrationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AlumniRegistrationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AlumniRegistrationGroupByOutputType[P]>
      }
    >
  >



export type AlumniRegistrationWhereInput = {
  AND?: Prisma.AlumniRegistrationWhereInput | Prisma.AlumniRegistrationWhereInput[]
  OR?: Prisma.AlumniRegistrationWhereInput[]
  NOT?: Prisma.AlumniRegistrationWhereInput | Prisma.AlumniRegistrationWhereInput[]
  id?: Prisma.StringFilter<"AlumniRegistration"> | string
  createdAt?: Prisma.DateTimeFilter<"AlumniRegistration"> | Date | string
  fullName?: Prisma.StringFilter<"AlumniRegistration"> | string
  gender?: Prisma.StringFilter<"AlumniRegistration"> | string
  dateOfBirth?: Prisma.DateTimeFilter<"AlumniRegistration"> | Date | string
  profilePhoto?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  email?: Prisma.StringFilter<"AlumniRegistration"> | string
  mobileNumber?: Prisma.StringFilter<"AlumniRegistration"> | string
  alternatePhone?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  currentAddress?: Prisma.StringFilter<"AlumniRegistration"> | string
  cityStateCountry?: Prisma.StringFilter<"AlumniRegistration"> | string
  courseProgram?: Prisma.StringFilter<"AlumniRegistration"> | string
  department?: Prisma.StringFilter<"AlumniRegistration"> | string
  yearOfAdmission?: Prisma.IntFilter<"AlumniRegistration"> | number
  yearOfGraduation?: Prisma.IntFilter<"AlumniRegistration"> | number
  enrollmentRollNumber?: Prisma.StringFilter<"AlumniRegistration"> | string
  currentOccupation?: Prisma.StringFilter<"AlumniRegistration"> | string
  companyOrganizationName?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  jobTitle?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  workLocation?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  yearsOfExperience?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  linkedInProfile?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  socialMedia?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  personalWebsite?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  willingToMentor?: Prisma.BoolFilter<"AlumniRegistration"> | boolean
  interestedInEvents?: Prisma.BoolFilter<"AlumniRegistration"> | boolean
  areasOfInterest?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  achievementsAwards?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  suggestionsFeedback?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  messageToInstitution?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  declarationAccepted?: Prisma.BoolFilter<"AlumniRegistration"> | boolean
  ipAddress?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  userAgent?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
}

export type AlumniRegistrationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  profilePhoto?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrder
  mobileNumber?: Prisma.SortOrder
  alternatePhone?: Prisma.SortOrderInput | Prisma.SortOrder
  currentAddress?: Prisma.SortOrder
  cityStateCountry?: Prisma.SortOrder
  courseProgram?: Prisma.SortOrder
  department?: Prisma.SortOrder
  yearOfAdmission?: Prisma.SortOrder
  yearOfGraduation?: Prisma.SortOrder
  enrollmentRollNumber?: Prisma.SortOrder
  currentOccupation?: Prisma.SortOrder
  companyOrganizationName?: Prisma.SortOrderInput | Prisma.SortOrder
  jobTitle?: Prisma.SortOrderInput | Prisma.SortOrder
  workLocation?: Prisma.SortOrderInput | Prisma.SortOrder
  yearsOfExperience?: Prisma.SortOrderInput | Prisma.SortOrder
  linkedInProfile?: Prisma.SortOrderInput | Prisma.SortOrder
  socialMedia?: Prisma.SortOrderInput | Prisma.SortOrder
  personalWebsite?: Prisma.SortOrderInput | Prisma.SortOrder
  willingToMentor?: Prisma.SortOrder
  interestedInEvents?: Prisma.SortOrder
  areasOfInterest?: Prisma.SortOrderInput | Prisma.SortOrder
  achievementsAwards?: Prisma.SortOrderInput | Prisma.SortOrder
  suggestionsFeedback?: Prisma.SortOrderInput | Prisma.SortOrder
  messageToInstitution?: Prisma.SortOrderInput | Prisma.SortOrder
  declarationAccepted?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  userAgent?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type AlumniRegistrationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AlumniRegistrationWhereInput | Prisma.AlumniRegistrationWhereInput[]
  OR?: Prisma.AlumniRegistrationWhereInput[]
  NOT?: Prisma.AlumniRegistrationWhereInput | Prisma.AlumniRegistrationWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"AlumniRegistration"> | Date | string
  fullName?: Prisma.StringFilter<"AlumniRegistration"> | string
  gender?: Prisma.StringFilter<"AlumniRegistration"> | string
  dateOfBirth?: Prisma.DateTimeFilter<"AlumniRegistration"> | Date | string
  profilePhoto?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  email?: Prisma.StringFilter<"AlumniRegistration"> | string
  mobileNumber?: Prisma.StringFilter<"AlumniRegistration"> | string
  alternatePhone?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  currentAddress?: Prisma.StringFilter<"AlumniRegistration"> | string
  cityStateCountry?: Prisma.StringFilter<"AlumniRegistration"> | string
  courseProgram?: Prisma.StringFilter<"AlumniRegistration"> | string
  department?: Prisma.StringFilter<"AlumniRegistration"> | string
  yearOfAdmission?: Prisma.IntFilter<"AlumniRegistration"> | number
  yearOfGraduation?: Prisma.IntFilter<"AlumniRegistration"> | number
  enrollmentRollNumber?: Prisma.StringFilter<"AlumniRegistration"> | string
  currentOccupation?: Prisma.StringFilter<"AlumniRegistration"> | string
  companyOrganizationName?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  jobTitle?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  workLocation?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  yearsOfExperience?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  linkedInProfile?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  socialMedia?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  personalWebsite?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  willingToMentor?: Prisma.BoolFilter<"AlumniRegistration"> | boolean
  interestedInEvents?: Prisma.BoolFilter<"AlumniRegistration"> | boolean
  areasOfInterest?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  achievementsAwards?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  suggestionsFeedback?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  messageToInstitution?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  declarationAccepted?: Prisma.BoolFilter<"AlumniRegistration"> | boolean
  ipAddress?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
  userAgent?: Prisma.StringNullableFilter<"AlumniRegistration"> | string | null
}, "id">

export type AlumniRegistrationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  profilePhoto?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrder
  mobileNumber?: Prisma.SortOrder
  alternatePhone?: Prisma.SortOrderInput | Prisma.SortOrder
  currentAddress?: Prisma.SortOrder
  cityStateCountry?: Prisma.SortOrder
  courseProgram?: Prisma.SortOrder
  department?: Prisma.SortOrder
  yearOfAdmission?: Prisma.SortOrder
  yearOfGraduation?: Prisma.SortOrder
  enrollmentRollNumber?: Prisma.SortOrder
  currentOccupation?: Prisma.SortOrder
  companyOrganizationName?: Prisma.SortOrderInput | Prisma.SortOrder
  jobTitle?: Prisma.SortOrderInput | Prisma.SortOrder
  workLocation?: Prisma.SortOrderInput | Prisma.SortOrder
  yearsOfExperience?: Prisma.SortOrderInput | Prisma.SortOrder
  linkedInProfile?: Prisma.SortOrderInput | Prisma.SortOrder
  socialMedia?: Prisma.SortOrderInput | Prisma.SortOrder
  personalWebsite?: Prisma.SortOrderInput | Prisma.SortOrder
  willingToMentor?: Prisma.SortOrder
  interestedInEvents?: Prisma.SortOrder
  areasOfInterest?: Prisma.SortOrderInput | Prisma.SortOrder
  achievementsAwards?: Prisma.SortOrderInput | Prisma.SortOrder
  suggestionsFeedback?: Prisma.SortOrderInput | Prisma.SortOrder
  messageToInstitution?: Prisma.SortOrderInput | Prisma.SortOrder
  declarationAccepted?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  userAgent?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.AlumniRegistrationCountOrderByAggregateInput
  _avg?: Prisma.AlumniRegistrationAvgOrderByAggregateInput
  _max?: Prisma.AlumniRegistrationMaxOrderByAggregateInput
  _min?: Prisma.AlumniRegistrationMinOrderByAggregateInput
  _sum?: Prisma.AlumniRegistrationSumOrderByAggregateInput
}

export type AlumniRegistrationScalarWhereWithAggregatesInput = {
  AND?: Prisma.AlumniRegistrationScalarWhereWithAggregatesInput | Prisma.AlumniRegistrationScalarWhereWithAggregatesInput[]
  OR?: Prisma.AlumniRegistrationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AlumniRegistrationScalarWhereWithAggregatesInput | Prisma.AlumniRegistrationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AlumniRegistration"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AlumniRegistration"> | Date | string
  fullName?: Prisma.StringWithAggregatesFilter<"AlumniRegistration"> | string
  gender?: Prisma.StringWithAggregatesFilter<"AlumniRegistration"> | string
  dateOfBirth?: Prisma.DateTimeWithAggregatesFilter<"AlumniRegistration"> | Date | string
  profilePhoto?: Prisma.StringNullableWithAggregatesFilter<"AlumniRegistration"> | string | null
  email?: Prisma.StringWithAggregatesFilter<"AlumniRegistration"> | string
  mobileNumber?: Prisma.StringWithAggregatesFilter<"AlumniRegistration"> | string
  alternatePhone?: Prisma.StringNullableWithAggregatesFilter<"AlumniRegistration"> | string | null
  currentAddress?: Prisma.StringWithAggregatesFilter<"AlumniRegistration"> | string
  cityStateCountry?: Prisma.StringWithAggregatesFilter<"AlumniRegistration"> | string
  courseProgram?: Prisma.StringWithAggregatesFilter<"AlumniRegistration"> | string
  department?: Prisma.StringWithAggregatesFilter<"AlumniRegistration"> | string
  yearOfAdmission?: Prisma.IntWithAggregatesFilter<"AlumniRegistration"> | number
  yearOfGraduation?: Prisma.IntWithAggregatesFilter<"AlumniRegistration"> | number
  enrollmentRollNumber?: Prisma.StringWithAggregatesFilter<"AlumniRegistration"> | string
  currentOccupation?: Prisma.StringWithAggregatesFilter<"AlumniRegistration"> | string
  companyOrganizationName?: Prisma.StringNullableWithAggregatesFilter<"AlumniRegistration"> | string | null
  jobTitle?: Prisma.StringNullableWithAggregatesFilter<"AlumniRegistration"> | string | null
  workLocation?: Prisma.StringNullableWithAggregatesFilter<"AlumniRegistration"> | string | null
  yearsOfExperience?: Prisma.StringNullableWithAggregatesFilter<"AlumniRegistration"> | string | null
  linkedInProfile?: Prisma.StringNullableWithAggregatesFilter<"AlumniRegistration"> | string | null
  socialMedia?: Prisma.StringNullableWithAggregatesFilter<"AlumniRegistration"> | string | null
  personalWebsite?: Prisma.StringNullableWithAggregatesFilter<"AlumniRegistration"> | string | null
  willingToMentor?: Prisma.BoolWithAggregatesFilter<"AlumniRegistration"> | boolean
  interestedInEvents?: Prisma.BoolWithAggregatesFilter<"AlumniRegistration"> | boolean
  areasOfInterest?: Prisma.StringNullableWithAggregatesFilter<"AlumniRegistration"> | string | null
  achievementsAwards?: Prisma.StringNullableWithAggregatesFilter<"AlumniRegistration"> | string | null
  suggestionsFeedback?: Prisma.StringNullableWithAggregatesFilter<"AlumniRegistration"> | string | null
  messageToInstitution?: Prisma.StringNullableWithAggregatesFilter<"AlumniRegistration"> | string | null
  declarationAccepted?: Prisma.BoolWithAggregatesFilter<"AlumniRegistration"> | boolean
  ipAddress?: Prisma.StringNullableWithAggregatesFilter<"AlumniRegistration"> | string | null
  userAgent?: Prisma.StringNullableWithAggregatesFilter<"AlumniRegistration"> | string | null
}

export type AlumniRegistrationCreateInput = {
  id?: string
  createdAt?: Date | string
  fullName: string
  gender: string
  dateOfBirth: Date | string
  profilePhoto?: string | null
  email: string
  mobileNumber: string
  alternatePhone?: string | null
  currentAddress: string
  cityStateCountry: string
  courseProgram: string
  department: string
  yearOfAdmission: number
  yearOfGraduation: number
  enrollmentRollNumber: string
  currentOccupation: string
  companyOrganizationName?: string | null
  jobTitle?: string | null
  workLocation?: string | null
  yearsOfExperience?: string | null
  linkedInProfile?: string | null
  socialMedia?: string | null
  personalWebsite?: string | null
  willingToMentor?: boolean
  interestedInEvents?: boolean
  areasOfInterest?: string | null
  achievementsAwards?: string | null
  suggestionsFeedback?: string | null
  messageToInstitution?: string | null
  declarationAccepted?: boolean
  ipAddress?: string | null
  userAgent?: string | null
}

export type AlumniRegistrationUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  fullName: string
  gender: string
  dateOfBirth: Date | string
  profilePhoto?: string | null
  email: string
  mobileNumber: string
  alternatePhone?: string | null
  currentAddress: string
  cityStateCountry: string
  courseProgram: string
  department: string
  yearOfAdmission: number
  yearOfGraduation: number
  enrollmentRollNumber: string
  currentOccupation: string
  companyOrganizationName?: string | null
  jobTitle?: string | null
  workLocation?: string | null
  yearsOfExperience?: string | null
  linkedInProfile?: string | null
  socialMedia?: string | null
  personalWebsite?: string | null
  willingToMentor?: boolean
  interestedInEvents?: boolean
  areasOfInterest?: string | null
  achievementsAwards?: string | null
  suggestionsFeedback?: string | null
  messageToInstitution?: string | null
  declarationAccepted?: boolean
  ipAddress?: string | null
  userAgent?: string | null
}

export type AlumniRegistrationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profilePhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
  mobileNumber?: Prisma.StringFieldUpdateOperationsInput | string
  alternatePhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentAddress?: Prisma.StringFieldUpdateOperationsInput | string
  cityStateCountry?: Prisma.StringFieldUpdateOperationsInput | string
  courseProgram?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  yearOfAdmission?: Prisma.IntFieldUpdateOperationsInput | number
  yearOfGraduation?: Prisma.IntFieldUpdateOperationsInput | number
  enrollmentRollNumber?: Prisma.StringFieldUpdateOperationsInput | string
  currentOccupation?: Prisma.StringFieldUpdateOperationsInput | string
  companyOrganizationName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jobTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workLocation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  yearsOfExperience?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedInProfile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  socialMedia?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  personalWebsite?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  willingToMentor?: Prisma.BoolFieldUpdateOperationsInput | boolean
  interestedInEvents?: Prisma.BoolFieldUpdateOperationsInput | boolean
  areasOfInterest?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  achievementsAwards?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  suggestionsFeedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageToInstitution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  declarationAccepted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AlumniRegistrationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profilePhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
  mobileNumber?: Prisma.StringFieldUpdateOperationsInput | string
  alternatePhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentAddress?: Prisma.StringFieldUpdateOperationsInput | string
  cityStateCountry?: Prisma.StringFieldUpdateOperationsInput | string
  courseProgram?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  yearOfAdmission?: Prisma.IntFieldUpdateOperationsInput | number
  yearOfGraduation?: Prisma.IntFieldUpdateOperationsInput | number
  enrollmentRollNumber?: Prisma.StringFieldUpdateOperationsInput | string
  currentOccupation?: Prisma.StringFieldUpdateOperationsInput | string
  companyOrganizationName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jobTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workLocation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  yearsOfExperience?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedInProfile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  socialMedia?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  personalWebsite?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  willingToMentor?: Prisma.BoolFieldUpdateOperationsInput | boolean
  interestedInEvents?: Prisma.BoolFieldUpdateOperationsInput | boolean
  areasOfInterest?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  achievementsAwards?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  suggestionsFeedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageToInstitution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  declarationAccepted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AlumniRegistrationCreateManyInput = {
  id?: string
  createdAt?: Date | string
  fullName: string
  gender: string
  dateOfBirth: Date | string
  profilePhoto?: string | null
  email: string
  mobileNumber: string
  alternatePhone?: string | null
  currentAddress: string
  cityStateCountry: string
  courseProgram: string
  department: string
  yearOfAdmission: number
  yearOfGraduation: number
  enrollmentRollNumber: string
  currentOccupation: string
  companyOrganizationName?: string | null
  jobTitle?: string | null
  workLocation?: string | null
  yearsOfExperience?: string | null
  linkedInProfile?: string | null
  socialMedia?: string | null
  personalWebsite?: string | null
  willingToMentor?: boolean
  interestedInEvents?: boolean
  areasOfInterest?: string | null
  achievementsAwards?: string | null
  suggestionsFeedback?: string | null
  messageToInstitution?: string | null
  declarationAccepted?: boolean
  ipAddress?: string | null
  userAgent?: string | null
}

export type AlumniRegistrationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profilePhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
  mobileNumber?: Prisma.StringFieldUpdateOperationsInput | string
  alternatePhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentAddress?: Prisma.StringFieldUpdateOperationsInput | string
  cityStateCountry?: Prisma.StringFieldUpdateOperationsInput | string
  courseProgram?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  yearOfAdmission?: Prisma.IntFieldUpdateOperationsInput | number
  yearOfGraduation?: Prisma.IntFieldUpdateOperationsInput | number
  enrollmentRollNumber?: Prisma.StringFieldUpdateOperationsInput | string
  currentOccupation?: Prisma.StringFieldUpdateOperationsInput | string
  companyOrganizationName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jobTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workLocation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  yearsOfExperience?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedInProfile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  socialMedia?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  personalWebsite?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  willingToMentor?: Prisma.BoolFieldUpdateOperationsInput | boolean
  interestedInEvents?: Prisma.BoolFieldUpdateOperationsInput | boolean
  areasOfInterest?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  achievementsAwards?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  suggestionsFeedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageToInstitution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  declarationAccepted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AlumniRegistrationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profilePhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
  mobileNumber?: Prisma.StringFieldUpdateOperationsInput | string
  alternatePhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentAddress?: Prisma.StringFieldUpdateOperationsInput | string
  cityStateCountry?: Prisma.StringFieldUpdateOperationsInput | string
  courseProgram?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  yearOfAdmission?: Prisma.IntFieldUpdateOperationsInput | number
  yearOfGraduation?: Prisma.IntFieldUpdateOperationsInput | number
  enrollmentRollNumber?: Prisma.StringFieldUpdateOperationsInput | string
  currentOccupation?: Prisma.StringFieldUpdateOperationsInput | string
  companyOrganizationName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jobTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workLocation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  yearsOfExperience?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedInProfile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  socialMedia?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  personalWebsite?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  willingToMentor?: Prisma.BoolFieldUpdateOperationsInput | boolean
  interestedInEvents?: Prisma.BoolFieldUpdateOperationsInput | boolean
  areasOfInterest?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  achievementsAwards?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  suggestionsFeedback?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  messageToInstitution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  declarationAccepted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AlumniRegistrationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  profilePhoto?: Prisma.SortOrder
  email?: Prisma.SortOrder
  mobileNumber?: Prisma.SortOrder
  alternatePhone?: Prisma.SortOrder
  currentAddress?: Prisma.SortOrder
  cityStateCountry?: Prisma.SortOrder
  courseProgram?: Prisma.SortOrder
  department?: Prisma.SortOrder
  yearOfAdmission?: Prisma.SortOrder
  yearOfGraduation?: Prisma.SortOrder
  enrollmentRollNumber?: Prisma.SortOrder
  currentOccupation?: Prisma.SortOrder
  companyOrganizationName?: Prisma.SortOrder
  jobTitle?: Prisma.SortOrder
  workLocation?: Prisma.SortOrder
  yearsOfExperience?: Prisma.SortOrder
  linkedInProfile?: Prisma.SortOrder
  socialMedia?: Prisma.SortOrder
  personalWebsite?: Prisma.SortOrder
  willingToMentor?: Prisma.SortOrder
  interestedInEvents?: Prisma.SortOrder
  areasOfInterest?: Prisma.SortOrder
  achievementsAwards?: Prisma.SortOrder
  suggestionsFeedback?: Prisma.SortOrder
  messageToInstitution?: Prisma.SortOrder
  declarationAccepted?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
}

export type AlumniRegistrationAvgOrderByAggregateInput = {
  yearOfAdmission?: Prisma.SortOrder
  yearOfGraduation?: Prisma.SortOrder
}

export type AlumniRegistrationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  profilePhoto?: Prisma.SortOrder
  email?: Prisma.SortOrder
  mobileNumber?: Prisma.SortOrder
  alternatePhone?: Prisma.SortOrder
  currentAddress?: Prisma.SortOrder
  cityStateCountry?: Prisma.SortOrder
  courseProgram?: Prisma.SortOrder
  department?: Prisma.SortOrder
  yearOfAdmission?: Prisma.SortOrder
  yearOfGraduation?: Prisma.SortOrder
  enrollmentRollNumber?: Prisma.SortOrder
  currentOccupation?: Prisma.SortOrder
  companyOrganizationName?: Prisma.SortOrder
  jobTitle?: Prisma.SortOrder
  workLocation?: Prisma.SortOrder
  yearsOfExperience?: Prisma.SortOrder
  linkedInProfile?: Prisma.SortOrder
  socialMedia?: Prisma.SortOrder
  personalWebsite?: Prisma.SortOrder
  willingToMentor?: Prisma.SortOrder
  interestedInEvents?: Prisma.SortOrder
  areasOfInterest?: Prisma.SortOrder
  achievementsAwards?: Prisma.SortOrder
  suggestionsFeedback?: Prisma.SortOrder
  messageToInstitution?: Prisma.SortOrder
  declarationAccepted?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
}

export type AlumniRegistrationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  profilePhoto?: Prisma.SortOrder
  email?: Prisma.SortOrder
  mobileNumber?: Prisma.SortOrder
  alternatePhone?: Prisma.SortOrder
  currentAddress?: Prisma.SortOrder
  cityStateCountry?: Prisma.SortOrder
  courseProgram?: Prisma.SortOrder
  department?: Prisma.SortOrder
  yearOfAdmission?: Prisma.SortOrder
  yearOfGraduation?: Prisma.SortOrder
  enrollmentRollNumber?: Prisma.SortOrder
  currentOccupation?: Prisma.SortOrder
  companyOrganizationName?: Prisma.SortOrder
  jobTitle?: Prisma.SortOrder
  workLocation?: Prisma.SortOrder
  yearsOfExperience?: Prisma.SortOrder
  linkedInProfile?: Prisma.SortOrder
  socialMedia?: Prisma.SortOrder
  personalWebsite?: Prisma.SortOrder
  willingToMentor?: Prisma.SortOrder
  interestedInEvents?: Prisma.SortOrder
  areasOfInterest?: Prisma.SortOrder
  achievementsAwards?: Prisma.SortOrder
  suggestionsFeedback?: Prisma.SortOrder
  messageToInstitution?: Prisma.SortOrder
  declarationAccepted?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
}

export type AlumniRegistrationSumOrderByAggregateInput = {
  yearOfAdmission?: Prisma.SortOrder
  yearOfGraduation?: Prisma.SortOrder
}



export type AlumniRegistrationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  fullName?: boolean
  gender?: boolean
  dateOfBirth?: boolean
  profilePhoto?: boolean
  email?: boolean
  mobileNumber?: boolean
  alternatePhone?: boolean
  currentAddress?: boolean
  cityStateCountry?: boolean
  courseProgram?: boolean
  department?: boolean
  yearOfAdmission?: boolean
  yearOfGraduation?: boolean
  enrollmentRollNumber?: boolean
  currentOccupation?: boolean
  companyOrganizationName?: boolean
  jobTitle?: boolean
  workLocation?: boolean
  yearsOfExperience?: boolean
  linkedInProfile?: boolean
  socialMedia?: boolean
  personalWebsite?: boolean
  willingToMentor?: boolean
  interestedInEvents?: boolean
  areasOfInterest?: boolean
  achievementsAwards?: boolean
  suggestionsFeedback?: boolean
  messageToInstitution?: boolean
  declarationAccepted?: boolean
  ipAddress?: boolean
  userAgent?: boolean
}, ExtArgs["result"]["alumniRegistration"]>

export type AlumniRegistrationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  fullName?: boolean
  gender?: boolean
  dateOfBirth?: boolean
  profilePhoto?: boolean
  email?: boolean
  mobileNumber?: boolean
  alternatePhone?: boolean
  currentAddress?: boolean
  cityStateCountry?: boolean
  courseProgram?: boolean
  department?: boolean
  yearOfAdmission?: boolean
  yearOfGraduation?: boolean
  enrollmentRollNumber?: boolean
  currentOccupation?: boolean
  companyOrganizationName?: boolean
  jobTitle?: boolean
  workLocation?: boolean
  yearsOfExperience?: boolean
  linkedInProfile?: boolean
  socialMedia?: boolean
  personalWebsite?: boolean
  willingToMentor?: boolean
  interestedInEvents?: boolean
  areasOfInterest?: boolean
  achievementsAwards?: boolean
  suggestionsFeedback?: boolean
  messageToInstitution?: boolean
  declarationAccepted?: boolean
  ipAddress?: boolean
  userAgent?: boolean
}, ExtArgs["result"]["alumniRegistration"]>

export type AlumniRegistrationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  fullName?: boolean
  gender?: boolean
  dateOfBirth?: boolean
  profilePhoto?: boolean
  email?: boolean
  mobileNumber?: boolean
  alternatePhone?: boolean
  currentAddress?: boolean
  cityStateCountry?: boolean
  courseProgram?: boolean
  department?: boolean
  yearOfAdmission?: boolean
  yearOfGraduation?: boolean
  enrollmentRollNumber?: boolean
  currentOccupation?: boolean
  companyOrganizationName?: boolean
  jobTitle?: boolean
  workLocation?: boolean
  yearsOfExperience?: boolean
  linkedInProfile?: boolean
  socialMedia?: boolean
  personalWebsite?: boolean
  willingToMentor?: boolean
  interestedInEvents?: boolean
  areasOfInterest?: boolean
  achievementsAwards?: boolean
  suggestionsFeedback?: boolean
  messageToInstitution?: boolean
  declarationAccepted?: boolean
  ipAddress?: boolean
  userAgent?: boolean
}, ExtArgs["result"]["alumniRegistration"]>

export type AlumniRegistrationSelectScalar = {
  id?: boolean
  createdAt?: boolean
  fullName?: boolean
  gender?: boolean
  dateOfBirth?: boolean
  profilePhoto?: boolean
  email?: boolean
  mobileNumber?: boolean
  alternatePhone?: boolean
  currentAddress?: boolean
  cityStateCountry?: boolean
  courseProgram?: boolean
  department?: boolean
  yearOfAdmission?: boolean
  yearOfGraduation?: boolean
  enrollmentRollNumber?: boolean
  currentOccupation?: boolean
  companyOrganizationName?: boolean
  jobTitle?: boolean
  workLocation?: boolean
  yearsOfExperience?: boolean
  linkedInProfile?: boolean
  socialMedia?: boolean
  personalWebsite?: boolean
  willingToMentor?: boolean
  interestedInEvents?: boolean
  areasOfInterest?: boolean
  achievementsAwards?: boolean
  suggestionsFeedback?: boolean
  messageToInstitution?: boolean
  declarationAccepted?: boolean
  ipAddress?: boolean
  userAgent?: boolean
}

export type AlumniRegistrationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "fullName" | "gender" | "dateOfBirth" | "profilePhoto" | "email" | "mobileNumber" | "alternatePhone" | "currentAddress" | "cityStateCountry" | "courseProgram" | "department" | "yearOfAdmission" | "yearOfGraduation" | "enrollmentRollNumber" | "currentOccupation" | "companyOrganizationName" | "jobTitle" | "workLocation" | "yearsOfExperience" | "linkedInProfile" | "socialMedia" | "personalWebsite" | "willingToMentor" | "interestedInEvents" | "areasOfInterest" | "achievementsAwards" | "suggestionsFeedback" | "messageToInstitution" | "declarationAccepted" | "ipAddress" | "userAgent", ExtArgs["result"]["alumniRegistration"]>

export type $AlumniRegistrationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AlumniRegistration"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    fullName: string
    gender: string
    dateOfBirth: Date
    profilePhoto: string | null
    email: string
    mobileNumber: string
    alternatePhone: string | null
    currentAddress: string
    cityStateCountry: string
    courseProgram: string
    department: string
    yearOfAdmission: number
    yearOfGraduation: number
    enrollmentRollNumber: string
    currentOccupation: string
    companyOrganizationName: string | null
    jobTitle: string | null
    workLocation: string | null
    yearsOfExperience: string | null
    linkedInProfile: string | null
    socialMedia: string | null
    personalWebsite: string | null
    willingToMentor: boolean
    interestedInEvents: boolean
    areasOfInterest: string | null
    achievementsAwards: string | null
    suggestionsFeedback: string | null
    messageToInstitution: string | null
    declarationAccepted: boolean
    ipAddress: string | null
    userAgent: string | null
  }, ExtArgs["result"]["alumniRegistration"]>
  composites: {}
}

export type AlumniRegistrationGetPayload<S extends boolean | null | undefined | AlumniRegistrationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AlumniRegistrationPayload, S>

export type AlumniRegistrationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AlumniRegistrationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AlumniRegistrationCountAggregateInputType | true
  }

export interface AlumniRegistrationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AlumniRegistration'], meta: { name: 'AlumniRegistration' } }
  /**
   * Find zero or one AlumniRegistration that matches the filter.
   * @param {AlumniRegistrationFindUniqueArgs} args - Arguments to find a AlumniRegistration
   * @example
   * // Get one AlumniRegistration
   * const alumniRegistration = await prisma.alumniRegistration.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AlumniRegistrationFindUniqueArgs>(args: Prisma.SelectSubset<T, AlumniRegistrationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AlumniRegistrationClient<runtime.Types.Result.GetResult<Prisma.$AlumniRegistrationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AlumniRegistration that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AlumniRegistrationFindUniqueOrThrowArgs} args - Arguments to find a AlumniRegistration
   * @example
   * // Get one AlumniRegistration
   * const alumniRegistration = await prisma.alumniRegistration.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AlumniRegistrationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AlumniRegistrationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AlumniRegistrationClient<runtime.Types.Result.GetResult<Prisma.$AlumniRegistrationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AlumniRegistration that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AlumniRegistrationFindFirstArgs} args - Arguments to find a AlumniRegistration
   * @example
   * // Get one AlumniRegistration
   * const alumniRegistration = await prisma.alumniRegistration.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AlumniRegistrationFindFirstArgs>(args?: Prisma.SelectSubset<T, AlumniRegistrationFindFirstArgs<ExtArgs>>): Prisma.Prisma__AlumniRegistrationClient<runtime.Types.Result.GetResult<Prisma.$AlumniRegistrationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AlumniRegistration that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AlumniRegistrationFindFirstOrThrowArgs} args - Arguments to find a AlumniRegistration
   * @example
   * // Get one AlumniRegistration
   * const alumniRegistration = await prisma.alumniRegistration.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AlumniRegistrationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AlumniRegistrationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AlumniRegistrationClient<runtime.Types.Result.GetResult<Prisma.$AlumniRegistrationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AlumniRegistrations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AlumniRegistrationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AlumniRegistrations
   * const alumniRegistrations = await prisma.alumniRegistration.findMany()
   * 
   * // Get first 10 AlumniRegistrations
   * const alumniRegistrations = await prisma.alumniRegistration.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const alumniRegistrationWithIdOnly = await prisma.alumniRegistration.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AlumniRegistrationFindManyArgs>(args?: Prisma.SelectSubset<T, AlumniRegistrationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AlumniRegistrationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AlumniRegistration.
   * @param {AlumniRegistrationCreateArgs} args - Arguments to create a AlumniRegistration.
   * @example
   * // Create one AlumniRegistration
   * const AlumniRegistration = await prisma.alumniRegistration.create({
   *   data: {
   *     // ... data to create a AlumniRegistration
   *   }
   * })
   * 
   */
  create<T extends AlumniRegistrationCreateArgs>(args: Prisma.SelectSubset<T, AlumniRegistrationCreateArgs<ExtArgs>>): Prisma.Prisma__AlumniRegistrationClient<runtime.Types.Result.GetResult<Prisma.$AlumniRegistrationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AlumniRegistrations.
   * @param {AlumniRegistrationCreateManyArgs} args - Arguments to create many AlumniRegistrations.
   * @example
   * // Create many AlumniRegistrations
   * const alumniRegistration = await prisma.alumniRegistration.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AlumniRegistrationCreateManyArgs>(args?: Prisma.SelectSubset<T, AlumniRegistrationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AlumniRegistrations and returns the data saved in the database.
   * @param {AlumniRegistrationCreateManyAndReturnArgs} args - Arguments to create many AlumniRegistrations.
   * @example
   * // Create many AlumniRegistrations
   * const alumniRegistration = await prisma.alumniRegistration.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AlumniRegistrations and only return the `id`
   * const alumniRegistrationWithIdOnly = await prisma.alumniRegistration.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AlumniRegistrationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AlumniRegistrationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AlumniRegistrationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AlumniRegistration.
   * @param {AlumniRegistrationDeleteArgs} args - Arguments to delete one AlumniRegistration.
   * @example
   * // Delete one AlumniRegistration
   * const AlumniRegistration = await prisma.alumniRegistration.delete({
   *   where: {
   *     // ... filter to delete one AlumniRegistration
   *   }
   * })
   * 
   */
  delete<T extends AlumniRegistrationDeleteArgs>(args: Prisma.SelectSubset<T, AlumniRegistrationDeleteArgs<ExtArgs>>): Prisma.Prisma__AlumniRegistrationClient<runtime.Types.Result.GetResult<Prisma.$AlumniRegistrationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AlumniRegistration.
   * @param {AlumniRegistrationUpdateArgs} args - Arguments to update one AlumniRegistration.
   * @example
   * // Update one AlumniRegistration
   * const alumniRegistration = await prisma.alumniRegistration.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AlumniRegistrationUpdateArgs>(args: Prisma.SelectSubset<T, AlumniRegistrationUpdateArgs<ExtArgs>>): Prisma.Prisma__AlumniRegistrationClient<runtime.Types.Result.GetResult<Prisma.$AlumniRegistrationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AlumniRegistrations.
   * @param {AlumniRegistrationDeleteManyArgs} args - Arguments to filter AlumniRegistrations to delete.
   * @example
   * // Delete a few AlumniRegistrations
   * const { count } = await prisma.alumniRegistration.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AlumniRegistrationDeleteManyArgs>(args?: Prisma.SelectSubset<T, AlumniRegistrationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AlumniRegistrations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AlumniRegistrationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AlumniRegistrations
   * const alumniRegistration = await prisma.alumniRegistration.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AlumniRegistrationUpdateManyArgs>(args: Prisma.SelectSubset<T, AlumniRegistrationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AlumniRegistrations and returns the data updated in the database.
   * @param {AlumniRegistrationUpdateManyAndReturnArgs} args - Arguments to update many AlumniRegistrations.
   * @example
   * // Update many AlumniRegistrations
   * const alumniRegistration = await prisma.alumniRegistration.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AlumniRegistrations and only return the `id`
   * const alumniRegistrationWithIdOnly = await prisma.alumniRegistration.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AlumniRegistrationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AlumniRegistrationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AlumniRegistrationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AlumniRegistration.
   * @param {AlumniRegistrationUpsertArgs} args - Arguments to update or create a AlumniRegistration.
   * @example
   * // Update or create a AlumniRegistration
   * const alumniRegistration = await prisma.alumniRegistration.upsert({
   *   create: {
   *     // ... data to create a AlumniRegistration
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AlumniRegistration we want to update
   *   }
   * })
   */
  upsert<T extends AlumniRegistrationUpsertArgs>(args: Prisma.SelectSubset<T, AlumniRegistrationUpsertArgs<ExtArgs>>): Prisma.Prisma__AlumniRegistrationClient<runtime.Types.Result.GetResult<Prisma.$AlumniRegistrationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AlumniRegistrations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AlumniRegistrationCountArgs} args - Arguments to filter AlumniRegistrations to count.
   * @example
   * // Count the number of AlumniRegistrations
   * const count = await prisma.alumniRegistration.count({
   *   where: {
   *     // ... the filter for the AlumniRegistrations we want to count
   *   }
   * })
  **/
  count<T extends AlumniRegistrationCountArgs>(
    args?: Prisma.Subset<T, AlumniRegistrationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AlumniRegistrationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AlumniRegistration.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AlumniRegistrationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AlumniRegistrationAggregateArgs>(args: Prisma.Subset<T, AlumniRegistrationAggregateArgs>): Prisma.PrismaPromise<GetAlumniRegistrationAggregateType<T>>

  /**
   * Group by AlumniRegistration.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AlumniRegistrationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AlumniRegistrationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AlumniRegistrationGroupByArgs['orderBy'] }
      : { orderBy?: AlumniRegistrationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AlumniRegistrationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAlumniRegistrationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AlumniRegistration model
 */
readonly fields: AlumniRegistrationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AlumniRegistration.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AlumniRegistrationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AlumniRegistration model
 */
export interface AlumniRegistrationFieldRefs {
  readonly id: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly createdAt: Prisma.FieldRef<"AlumniRegistration", 'DateTime'>
  readonly fullName: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly gender: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly dateOfBirth: Prisma.FieldRef<"AlumniRegistration", 'DateTime'>
  readonly profilePhoto: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly email: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly mobileNumber: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly alternatePhone: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly currentAddress: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly cityStateCountry: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly courseProgram: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly department: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly yearOfAdmission: Prisma.FieldRef<"AlumniRegistration", 'Int'>
  readonly yearOfGraduation: Prisma.FieldRef<"AlumniRegistration", 'Int'>
  readonly enrollmentRollNumber: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly currentOccupation: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly companyOrganizationName: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly jobTitle: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly workLocation: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly yearsOfExperience: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly linkedInProfile: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly socialMedia: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly personalWebsite: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly willingToMentor: Prisma.FieldRef<"AlumniRegistration", 'Boolean'>
  readonly interestedInEvents: Prisma.FieldRef<"AlumniRegistration", 'Boolean'>
  readonly areasOfInterest: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly achievementsAwards: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly suggestionsFeedback: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly messageToInstitution: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly declarationAccepted: Prisma.FieldRef<"AlumniRegistration", 'Boolean'>
  readonly ipAddress: Prisma.FieldRef<"AlumniRegistration", 'String'>
  readonly userAgent: Prisma.FieldRef<"AlumniRegistration", 'String'>
}
    

// Custom InputTypes
/**
 * AlumniRegistration findUnique
 */
export type AlumniRegistrationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AlumniRegistration
   */
  select?: Prisma.AlumniRegistrationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AlumniRegistration
   */
  omit?: Prisma.AlumniRegistrationOmit<ExtArgs> | null
  /**
   * Filter, which AlumniRegistration to fetch.
   */
  where: Prisma.AlumniRegistrationWhereUniqueInput
}

/**
 * AlumniRegistration findUniqueOrThrow
 */
export type AlumniRegistrationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AlumniRegistration
   */
  select?: Prisma.AlumniRegistrationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AlumniRegistration
   */
  omit?: Prisma.AlumniRegistrationOmit<ExtArgs> | null
  /**
   * Filter, which AlumniRegistration to fetch.
   */
  where: Prisma.AlumniRegistrationWhereUniqueInput
}

/**
 * AlumniRegistration findFirst
 */
export type AlumniRegistrationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AlumniRegistration
   */
  select?: Prisma.AlumniRegistrationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AlumniRegistration
   */
  omit?: Prisma.AlumniRegistrationOmit<ExtArgs> | null
  /**
   * Filter, which AlumniRegistration to fetch.
   */
  where?: Prisma.AlumniRegistrationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AlumniRegistrations to fetch.
   */
  orderBy?: Prisma.AlumniRegistrationOrderByWithRelationInput | Prisma.AlumniRegistrationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AlumniRegistrations.
   */
  cursor?: Prisma.AlumniRegistrationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AlumniRegistrations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AlumniRegistrations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AlumniRegistrations.
   */
  distinct?: Prisma.AlumniRegistrationScalarFieldEnum | Prisma.AlumniRegistrationScalarFieldEnum[]
}

/**
 * AlumniRegistration findFirstOrThrow
 */
export type AlumniRegistrationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AlumniRegistration
   */
  select?: Prisma.AlumniRegistrationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AlumniRegistration
   */
  omit?: Prisma.AlumniRegistrationOmit<ExtArgs> | null
  /**
   * Filter, which AlumniRegistration to fetch.
   */
  where?: Prisma.AlumniRegistrationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AlumniRegistrations to fetch.
   */
  orderBy?: Prisma.AlumniRegistrationOrderByWithRelationInput | Prisma.AlumniRegistrationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AlumniRegistrations.
   */
  cursor?: Prisma.AlumniRegistrationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AlumniRegistrations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AlumniRegistrations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AlumniRegistrations.
   */
  distinct?: Prisma.AlumniRegistrationScalarFieldEnum | Prisma.AlumniRegistrationScalarFieldEnum[]
}

/**
 * AlumniRegistration findMany
 */
export type AlumniRegistrationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AlumniRegistration
   */
  select?: Prisma.AlumniRegistrationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AlumniRegistration
   */
  omit?: Prisma.AlumniRegistrationOmit<ExtArgs> | null
  /**
   * Filter, which AlumniRegistrations to fetch.
   */
  where?: Prisma.AlumniRegistrationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AlumniRegistrations to fetch.
   */
  orderBy?: Prisma.AlumniRegistrationOrderByWithRelationInput | Prisma.AlumniRegistrationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AlumniRegistrations.
   */
  cursor?: Prisma.AlumniRegistrationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AlumniRegistrations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AlumniRegistrations.
   */
  skip?: number
  distinct?: Prisma.AlumniRegistrationScalarFieldEnum | Prisma.AlumniRegistrationScalarFieldEnum[]
}

/**
 * AlumniRegistration create
 */
export type AlumniRegistrationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AlumniRegistration
   */
  select?: Prisma.AlumniRegistrationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AlumniRegistration
   */
  omit?: Prisma.AlumniRegistrationOmit<ExtArgs> | null
  /**
   * The data needed to create a AlumniRegistration.
   */
  data: Prisma.XOR<Prisma.AlumniRegistrationCreateInput, Prisma.AlumniRegistrationUncheckedCreateInput>
}

/**
 * AlumniRegistration createMany
 */
export type AlumniRegistrationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AlumniRegistrations.
   */
  data: Prisma.AlumniRegistrationCreateManyInput | Prisma.AlumniRegistrationCreateManyInput[]
}

/**
 * AlumniRegistration createManyAndReturn
 */
export type AlumniRegistrationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AlumniRegistration
   */
  select?: Prisma.AlumniRegistrationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AlumniRegistration
   */
  omit?: Prisma.AlumniRegistrationOmit<ExtArgs> | null
  /**
   * The data used to create many AlumniRegistrations.
   */
  data: Prisma.AlumniRegistrationCreateManyInput | Prisma.AlumniRegistrationCreateManyInput[]
}

/**
 * AlumniRegistration update
 */
export type AlumniRegistrationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AlumniRegistration
   */
  select?: Prisma.AlumniRegistrationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AlumniRegistration
   */
  omit?: Prisma.AlumniRegistrationOmit<ExtArgs> | null
  /**
   * The data needed to update a AlumniRegistration.
   */
  data: Prisma.XOR<Prisma.AlumniRegistrationUpdateInput, Prisma.AlumniRegistrationUncheckedUpdateInput>
  /**
   * Choose, which AlumniRegistration to update.
   */
  where: Prisma.AlumniRegistrationWhereUniqueInput
}

/**
 * AlumniRegistration updateMany
 */
export type AlumniRegistrationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AlumniRegistrations.
   */
  data: Prisma.XOR<Prisma.AlumniRegistrationUpdateManyMutationInput, Prisma.AlumniRegistrationUncheckedUpdateManyInput>
  /**
   * Filter which AlumniRegistrations to update
   */
  where?: Prisma.AlumniRegistrationWhereInput
  /**
   * Limit how many AlumniRegistrations to update.
   */
  limit?: number
}

/**
 * AlumniRegistration updateManyAndReturn
 */
export type AlumniRegistrationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AlumniRegistration
   */
  select?: Prisma.AlumniRegistrationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AlumniRegistration
   */
  omit?: Prisma.AlumniRegistrationOmit<ExtArgs> | null
  /**
   * The data used to update AlumniRegistrations.
   */
  data: Prisma.XOR<Prisma.AlumniRegistrationUpdateManyMutationInput, Prisma.AlumniRegistrationUncheckedUpdateManyInput>
  /**
   * Filter which AlumniRegistrations to update
   */
  where?: Prisma.AlumniRegistrationWhereInput
  /**
   * Limit how many AlumniRegistrations to update.
   */
  limit?: number
}

/**
 * AlumniRegistration upsert
 */
export type AlumniRegistrationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AlumniRegistration
   */
  select?: Prisma.AlumniRegistrationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AlumniRegistration
   */
  omit?: Prisma.AlumniRegistrationOmit<ExtArgs> | null
  /**
   * The filter to search for the AlumniRegistration to update in case it exists.
   */
  where: Prisma.AlumniRegistrationWhereUniqueInput
  /**
   * In case the AlumniRegistration found by the `where` argument doesn't exist, create a new AlumniRegistration with this data.
   */
  create: Prisma.XOR<Prisma.AlumniRegistrationCreateInput, Prisma.AlumniRegistrationUncheckedCreateInput>
  /**
   * In case the AlumniRegistration was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AlumniRegistrationUpdateInput, Prisma.AlumniRegistrationUncheckedUpdateInput>
}

/**
 * AlumniRegistration delete
 */
export type AlumniRegistrationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AlumniRegistration
   */
  select?: Prisma.AlumniRegistrationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AlumniRegistration
   */
  omit?: Prisma.AlumniRegistrationOmit<ExtArgs> | null
  /**
   * Filter which AlumniRegistration to delete.
   */
  where: Prisma.AlumniRegistrationWhereUniqueInput
}

/**
 * AlumniRegistration deleteMany
 */
export type AlumniRegistrationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AlumniRegistrations to delete
   */
  where?: Prisma.AlumniRegistrationWhereInput
  /**
   * Limit how many AlumniRegistrations to delete.
   */
  limit?: number
}

/**
 * AlumniRegistration without action
 */
export type AlumniRegistrationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AlumniRegistration
   */
  select?: Prisma.AlumniRegistrationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AlumniRegistration
   */
  omit?: Prisma.AlumniRegistrationOmit<ExtArgs> | null
}
