
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `FlashNews` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FlashNews
 * 
 */
export type FlashNewsModel = runtime.Types.Result.DefaultSelection<Prisma.$FlashNewsPayload>

export type AggregateFlashNews = {
  _count: FlashNewsCountAggregateOutputType | null
  _avg: FlashNewsAvgAggregateOutputType | null
  _sum: FlashNewsSumAggregateOutputType | null
  _min: FlashNewsMinAggregateOutputType | null
  _max: FlashNewsMaxAggregateOutputType | null
}

export type FlashNewsAvgAggregateOutputType = {
  displayOrder: number | null
  downloadCount: number | null
}

export type FlashNewsSumAggregateOutputType = {
  displayOrder: number | null
  downloadCount: number | null
}

export type FlashNewsMinAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  file: string | null
  fileType: string | null
  displayOrder: number | null
  published: boolean | null
  downloadCount: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FlashNewsMaxAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  file: string | null
  fileType: string | null
  displayOrder: number | null
  published: boolean | null
  downloadCount: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FlashNewsCountAggregateOutputType = {
  id: number
  title: number
  description: number
  file: number
  fileType: number
  displayOrder: number
  published: number
  downloadCount: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FlashNewsAvgAggregateInputType = {
  displayOrder?: true
  downloadCount?: true
}

export type FlashNewsSumAggregateInputType = {
  displayOrder?: true
  downloadCount?: true
}

export type FlashNewsMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  file?: true
  fileType?: true
  displayOrder?: true
  published?: true
  downloadCount?: true
  createdAt?: true
  updatedAt?: true
}

export type FlashNewsMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  file?: true
  fileType?: true
  displayOrder?: true
  published?: true
  downloadCount?: true
  createdAt?: true
  updatedAt?: true
}

export type FlashNewsCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  file?: true
  fileType?: true
  displayOrder?: true
  published?: true
  downloadCount?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FlashNewsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FlashNews to aggregate.
   */
  where?: Prisma.FlashNewsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FlashNews to fetch.
   */
  orderBy?: Prisma.FlashNewsOrderByWithRelationInput | Prisma.FlashNewsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FlashNewsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FlashNews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FlashNews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FlashNews
  **/
  _count?: true | FlashNewsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FlashNewsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FlashNewsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FlashNewsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FlashNewsMaxAggregateInputType
}

export type GetFlashNewsAggregateType<T extends FlashNewsAggregateArgs> = {
      [P in keyof T & keyof AggregateFlashNews]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFlashNews[P]>
    : Prisma.GetScalarType<T[P], AggregateFlashNews[P]>
}




export type FlashNewsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FlashNewsWhereInput
  orderBy?: Prisma.FlashNewsOrderByWithAggregationInput | Prisma.FlashNewsOrderByWithAggregationInput[]
  by: Prisma.FlashNewsScalarFieldEnum[] | Prisma.FlashNewsScalarFieldEnum
  having?: Prisma.FlashNewsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FlashNewsCountAggregateInputType | true
  _avg?: FlashNewsAvgAggregateInputType
  _sum?: FlashNewsSumAggregateInputType
  _min?: FlashNewsMinAggregateInputType
  _max?: FlashNewsMaxAggregateInputType
}

export type FlashNewsGroupByOutputType = {
  id: string
  title: string
  description: string | null
  file: string | null
  fileType: string | null
  displayOrder: number
  published: boolean
  downloadCount: number
  createdAt: Date
  updatedAt: Date
  _count: FlashNewsCountAggregateOutputType | null
  _avg: FlashNewsAvgAggregateOutputType | null
  _sum: FlashNewsSumAggregateOutputType | null
  _min: FlashNewsMinAggregateOutputType | null
  _max: FlashNewsMaxAggregateOutputType | null
}

type GetFlashNewsGroupByPayload<T extends FlashNewsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FlashNewsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FlashNewsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FlashNewsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FlashNewsGroupByOutputType[P]>
      }
    >
  >



export type FlashNewsWhereInput = {
  AND?: Prisma.FlashNewsWhereInput | Prisma.FlashNewsWhereInput[]
  OR?: Prisma.FlashNewsWhereInput[]
  NOT?: Prisma.FlashNewsWhereInput | Prisma.FlashNewsWhereInput[]
  id?: Prisma.StringFilter<"FlashNews"> | string
  title?: Prisma.StringFilter<"FlashNews"> | string
  description?: Prisma.StringNullableFilter<"FlashNews"> | string | null
  file?: Prisma.StringNullableFilter<"FlashNews"> | string | null
  fileType?: Prisma.StringNullableFilter<"FlashNews"> | string | null
  displayOrder?: Prisma.IntFilter<"FlashNews"> | number
  published?: Prisma.BoolFilter<"FlashNews"> | boolean
  downloadCount?: Prisma.IntFilter<"FlashNews"> | number
  createdAt?: Prisma.DateTimeFilter<"FlashNews"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FlashNews"> | Date | string
}

export type FlashNewsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  file?: Prisma.SortOrderInput | Prisma.SortOrder
  fileType?: Prisma.SortOrderInput | Prisma.SortOrder
  displayOrder?: Prisma.SortOrder
  published?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FlashNewsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FlashNewsWhereInput | Prisma.FlashNewsWhereInput[]
  OR?: Prisma.FlashNewsWhereInput[]
  NOT?: Prisma.FlashNewsWhereInput | Prisma.FlashNewsWhereInput[]
  title?: Prisma.StringFilter<"FlashNews"> | string
  description?: Prisma.StringNullableFilter<"FlashNews"> | string | null
  file?: Prisma.StringNullableFilter<"FlashNews"> | string | null
  fileType?: Prisma.StringNullableFilter<"FlashNews"> | string | null
  displayOrder?: Prisma.IntFilter<"FlashNews"> | number
  published?: Prisma.BoolFilter<"FlashNews"> | boolean
  downloadCount?: Prisma.IntFilter<"FlashNews"> | number
  createdAt?: Prisma.DateTimeFilter<"FlashNews"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FlashNews"> | Date | string
}, "id">

export type FlashNewsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  file?: Prisma.SortOrderInput | Prisma.SortOrder
  fileType?: Prisma.SortOrderInput | Prisma.SortOrder
  displayOrder?: Prisma.SortOrder
  published?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FlashNewsCountOrderByAggregateInput
  _avg?: Prisma.FlashNewsAvgOrderByAggregateInput
  _max?: Prisma.FlashNewsMaxOrderByAggregateInput
  _min?: Prisma.FlashNewsMinOrderByAggregateInput
  _sum?: Prisma.FlashNewsSumOrderByAggregateInput
}

export type FlashNewsScalarWhereWithAggregatesInput = {
  AND?: Prisma.FlashNewsScalarWhereWithAggregatesInput | Prisma.FlashNewsScalarWhereWithAggregatesInput[]
  OR?: Prisma.FlashNewsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FlashNewsScalarWhereWithAggregatesInput | Prisma.FlashNewsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FlashNews"> | string
  title?: Prisma.StringWithAggregatesFilter<"FlashNews"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"FlashNews"> | string | null
  file?: Prisma.StringNullableWithAggregatesFilter<"FlashNews"> | string | null
  fileType?: Prisma.StringNullableWithAggregatesFilter<"FlashNews"> | string | null
  displayOrder?: Prisma.IntWithAggregatesFilter<"FlashNews"> | number
  published?: Prisma.BoolWithAggregatesFilter<"FlashNews"> | boolean
  downloadCount?: Prisma.IntWithAggregatesFilter<"FlashNews"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FlashNews"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"FlashNews"> | Date | string
}

export type FlashNewsCreateInput = {
  id?: string
  title: string
  description?: string | null
  file?: string | null
  fileType?: string | null
  displayOrder?: number
  published?: boolean
  downloadCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FlashNewsUncheckedCreateInput = {
  id?: string
  title: string
  description?: string | null
  file?: string | null
  fileType?: string | null
  displayOrder?: number
  published?: boolean
  downloadCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FlashNewsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  file?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayOrder?: Prisma.IntFieldUpdateOperationsInput | number
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  downloadCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FlashNewsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  file?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayOrder?: Prisma.IntFieldUpdateOperationsInput | number
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  downloadCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FlashNewsCreateManyInput = {
  id?: string
  title: string
  description?: string | null
  file?: string | null
  fileType?: string | null
  displayOrder?: number
  published?: boolean
  downloadCount?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FlashNewsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  file?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayOrder?: Prisma.IntFieldUpdateOperationsInput | number
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  downloadCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FlashNewsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  file?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  displayOrder?: Prisma.IntFieldUpdateOperationsInput | number
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  downloadCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FlashNewsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  file?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  displayOrder?: Prisma.SortOrder
  published?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FlashNewsAvgOrderByAggregateInput = {
  displayOrder?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
}

export type FlashNewsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  file?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  displayOrder?: Prisma.SortOrder
  published?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FlashNewsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  file?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  displayOrder?: Prisma.SortOrder
  published?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FlashNewsSumOrderByAggregateInput = {
  displayOrder?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
}



export type FlashNewsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  file?: boolean
  fileType?: boolean
  displayOrder?: boolean
  published?: boolean
  downloadCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["flashNews"]>

export type FlashNewsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  file?: boolean
  fileType?: boolean
  displayOrder?: boolean
  published?: boolean
  downloadCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["flashNews"]>

export type FlashNewsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  file?: boolean
  fileType?: boolean
  displayOrder?: boolean
  published?: boolean
  downloadCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["flashNews"]>

export type FlashNewsSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  file?: boolean
  fileType?: boolean
  displayOrder?: boolean
  published?: boolean
  downloadCount?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FlashNewsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "file" | "fileType" | "displayOrder" | "published" | "downloadCount" | "createdAt" | "updatedAt", ExtArgs["result"]["flashNews"]>

export type $FlashNewsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FlashNews"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    description: string | null
    file: string | null
    fileType: string | null
    displayOrder: number
    published: boolean
    downloadCount: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["flashNews"]>
  composites: {}
}

export type FlashNewsGetPayload<S extends boolean | null | undefined | FlashNewsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FlashNewsPayload, S>

export type FlashNewsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FlashNewsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FlashNewsCountAggregateInputType | true
  }

export interface FlashNewsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FlashNews'], meta: { name: 'FlashNews' } }
  /**
   * Find zero or one FlashNews that matches the filter.
   * @param {FlashNewsFindUniqueArgs} args - Arguments to find a FlashNews
   * @example
   * // Get one FlashNews
   * const flashNews = await prisma.flashNews.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FlashNewsFindUniqueArgs>(args: Prisma.SelectSubset<T, FlashNewsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FlashNewsClient<runtime.Types.Result.GetResult<Prisma.$FlashNewsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FlashNews that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FlashNewsFindUniqueOrThrowArgs} args - Arguments to find a FlashNews
   * @example
   * // Get one FlashNews
   * const flashNews = await prisma.flashNews.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FlashNewsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FlashNewsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FlashNewsClient<runtime.Types.Result.GetResult<Prisma.$FlashNewsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FlashNews that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlashNewsFindFirstArgs} args - Arguments to find a FlashNews
   * @example
   * // Get one FlashNews
   * const flashNews = await prisma.flashNews.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FlashNewsFindFirstArgs>(args?: Prisma.SelectSubset<T, FlashNewsFindFirstArgs<ExtArgs>>): Prisma.Prisma__FlashNewsClient<runtime.Types.Result.GetResult<Prisma.$FlashNewsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FlashNews that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlashNewsFindFirstOrThrowArgs} args - Arguments to find a FlashNews
   * @example
   * // Get one FlashNews
   * const flashNews = await prisma.flashNews.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FlashNewsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FlashNewsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FlashNewsClient<runtime.Types.Result.GetResult<Prisma.$FlashNewsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FlashNews that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlashNewsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FlashNews
   * const flashNews = await prisma.flashNews.findMany()
   * 
   * // Get first 10 FlashNews
   * const flashNews = await prisma.flashNews.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const flashNewsWithIdOnly = await prisma.flashNews.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FlashNewsFindManyArgs>(args?: Prisma.SelectSubset<T, FlashNewsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FlashNewsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FlashNews.
   * @param {FlashNewsCreateArgs} args - Arguments to create a FlashNews.
   * @example
   * // Create one FlashNews
   * const FlashNews = await prisma.flashNews.create({
   *   data: {
   *     // ... data to create a FlashNews
   *   }
   * })
   * 
   */
  create<T extends FlashNewsCreateArgs>(args: Prisma.SelectSubset<T, FlashNewsCreateArgs<ExtArgs>>): Prisma.Prisma__FlashNewsClient<runtime.Types.Result.GetResult<Prisma.$FlashNewsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FlashNews.
   * @param {FlashNewsCreateManyArgs} args - Arguments to create many FlashNews.
   * @example
   * // Create many FlashNews
   * const flashNews = await prisma.flashNews.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FlashNewsCreateManyArgs>(args?: Prisma.SelectSubset<T, FlashNewsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FlashNews and returns the data saved in the database.
   * @param {FlashNewsCreateManyAndReturnArgs} args - Arguments to create many FlashNews.
   * @example
   * // Create many FlashNews
   * const flashNews = await prisma.flashNews.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FlashNews and only return the `id`
   * const flashNewsWithIdOnly = await prisma.flashNews.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FlashNewsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FlashNewsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FlashNewsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FlashNews.
   * @param {FlashNewsDeleteArgs} args - Arguments to delete one FlashNews.
   * @example
   * // Delete one FlashNews
   * const FlashNews = await prisma.flashNews.delete({
   *   where: {
   *     // ... filter to delete one FlashNews
   *   }
   * })
   * 
   */
  delete<T extends FlashNewsDeleteArgs>(args: Prisma.SelectSubset<T, FlashNewsDeleteArgs<ExtArgs>>): Prisma.Prisma__FlashNewsClient<runtime.Types.Result.GetResult<Prisma.$FlashNewsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FlashNews.
   * @param {FlashNewsUpdateArgs} args - Arguments to update one FlashNews.
   * @example
   * // Update one FlashNews
   * const flashNews = await prisma.flashNews.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FlashNewsUpdateArgs>(args: Prisma.SelectSubset<T, FlashNewsUpdateArgs<ExtArgs>>): Prisma.Prisma__FlashNewsClient<runtime.Types.Result.GetResult<Prisma.$FlashNewsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FlashNews.
   * @param {FlashNewsDeleteManyArgs} args - Arguments to filter FlashNews to delete.
   * @example
   * // Delete a few FlashNews
   * const { count } = await prisma.flashNews.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FlashNewsDeleteManyArgs>(args?: Prisma.SelectSubset<T, FlashNewsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FlashNews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlashNewsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FlashNews
   * const flashNews = await prisma.flashNews.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FlashNewsUpdateManyArgs>(args: Prisma.SelectSubset<T, FlashNewsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FlashNews and returns the data updated in the database.
   * @param {FlashNewsUpdateManyAndReturnArgs} args - Arguments to update many FlashNews.
   * @example
   * // Update many FlashNews
   * const flashNews = await prisma.flashNews.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FlashNews and only return the `id`
   * const flashNewsWithIdOnly = await prisma.flashNews.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FlashNewsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FlashNewsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FlashNewsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FlashNews.
   * @param {FlashNewsUpsertArgs} args - Arguments to update or create a FlashNews.
   * @example
   * // Update or create a FlashNews
   * const flashNews = await prisma.flashNews.upsert({
   *   create: {
   *     // ... data to create a FlashNews
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FlashNews we want to update
   *   }
   * })
   */
  upsert<T extends FlashNewsUpsertArgs>(args: Prisma.SelectSubset<T, FlashNewsUpsertArgs<ExtArgs>>): Prisma.Prisma__FlashNewsClient<runtime.Types.Result.GetResult<Prisma.$FlashNewsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FlashNews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlashNewsCountArgs} args - Arguments to filter FlashNews to count.
   * @example
   * // Count the number of FlashNews
   * const count = await prisma.flashNews.count({
   *   where: {
   *     // ... the filter for the FlashNews we want to count
   *   }
   * })
  **/
  count<T extends FlashNewsCountArgs>(
    args?: Prisma.Subset<T, FlashNewsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FlashNewsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FlashNews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlashNewsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FlashNewsAggregateArgs>(args: Prisma.Subset<T, FlashNewsAggregateArgs>): Prisma.PrismaPromise<GetFlashNewsAggregateType<T>>

  /**
   * Group by FlashNews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FlashNewsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FlashNewsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FlashNewsGroupByArgs['orderBy'] }
      : { orderBy?: FlashNewsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FlashNewsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFlashNewsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FlashNews model
 */
readonly fields: FlashNewsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FlashNews.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FlashNewsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FlashNews model
 */
export interface FlashNewsFieldRefs {
  readonly id: Prisma.FieldRef<"FlashNews", 'String'>
  readonly title: Prisma.FieldRef<"FlashNews", 'String'>
  readonly description: Prisma.FieldRef<"FlashNews", 'String'>
  readonly file: Prisma.FieldRef<"FlashNews", 'String'>
  readonly fileType: Prisma.FieldRef<"FlashNews", 'String'>
  readonly displayOrder: Prisma.FieldRef<"FlashNews", 'Int'>
  readonly published: Prisma.FieldRef<"FlashNews", 'Boolean'>
  readonly downloadCount: Prisma.FieldRef<"FlashNews", 'Int'>
  readonly createdAt: Prisma.FieldRef<"FlashNews", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"FlashNews", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FlashNews findUnique
 */
export type FlashNewsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashNews
   */
  select?: Prisma.FlashNewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashNews
   */
  omit?: Prisma.FlashNewsOmit<ExtArgs> | null
  /**
   * Filter, which FlashNews to fetch.
   */
  where: Prisma.FlashNewsWhereUniqueInput
}

/**
 * FlashNews findUniqueOrThrow
 */
export type FlashNewsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashNews
   */
  select?: Prisma.FlashNewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashNews
   */
  omit?: Prisma.FlashNewsOmit<ExtArgs> | null
  /**
   * Filter, which FlashNews to fetch.
   */
  where: Prisma.FlashNewsWhereUniqueInput
}

/**
 * FlashNews findFirst
 */
export type FlashNewsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashNews
   */
  select?: Prisma.FlashNewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashNews
   */
  omit?: Prisma.FlashNewsOmit<ExtArgs> | null
  /**
   * Filter, which FlashNews to fetch.
   */
  where?: Prisma.FlashNewsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FlashNews to fetch.
   */
  orderBy?: Prisma.FlashNewsOrderByWithRelationInput | Prisma.FlashNewsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FlashNews.
   */
  cursor?: Prisma.FlashNewsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FlashNews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FlashNews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FlashNews.
   */
  distinct?: Prisma.FlashNewsScalarFieldEnum | Prisma.FlashNewsScalarFieldEnum[]
}

/**
 * FlashNews findFirstOrThrow
 */
export type FlashNewsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashNews
   */
  select?: Prisma.FlashNewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashNews
   */
  omit?: Prisma.FlashNewsOmit<ExtArgs> | null
  /**
   * Filter, which FlashNews to fetch.
   */
  where?: Prisma.FlashNewsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FlashNews to fetch.
   */
  orderBy?: Prisma.FlashNewsOrderByWithRelationInput | Prisma.FlashNewsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FlashNews.
   */
  cursor?: Prisma.FlashNewsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FlashNews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FlashNews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FlashNews.
   */
  distinct?: Prisma.FlashNewsScalarFieldEnum | Prisma.FlashNewsScalarFieldEnum[]
}

/**
 * FlashNews findMany
 */
export type FlashNewsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashNews
   */
  select?: Prisma.FlashNewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashNews
   */
  omit?: Prisma.FlashNewsOmit<ExtArgs> | null
  /**
   * Filter, which FlashNews to fetch.
   */
  where?: Prisma.FlashNewsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FlashNews to fetch.
   */
  orderBy?: Prisma.FlashNewsOrderByWithRelationInput | Prisma.FlashNewsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FlashNews.
   */
  cursor?: Prisma.FlashNewsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FlashNews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FlashNews.
   */
  skip?: number
  distinct?: Prisma.FlashNewsScalarFieldEnum | Prisma.FlashNewsScalarFieldEnum[]
}

/**
 * FlashNews create
 */
export type FlashNewsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashNews
   */
  select?: Prisma.FlashNewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashNews
   */
  omit?: Prisma.FlashNewsOmit<ExtArgs> | null
  /**
   * The data needed to create a FlashNews.
   */
  data: Prisma.XOR<Prisma.FlashNewsCreateInput, Prisma.FlashNewsUncheckedCreateInput>
}

/**
 * FlashNews createMany
 */
export type FlashNewsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FlashNews.
   */
  data: Prisma.FlashNewsCreateManyInput | Prisma.FlashNewsCreateManyInput[]
}

/**
 * FlashNews createManyAndReturn
 */
export type FlashNewsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashNews
   */
  select?: Prisma.FlashNewsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FlashNews
   */
  omit?: Prisma.FlashNewsOmit<ExtArgs> | null
  /**
   * The data used to create many FlashNews.
   */
  data: Prisma.FlashNewsCreateManyInput | Prisma.FlashNewsCreateManyInput[]
}

/**
 * FlashNews update
 */
export type FlashNewsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashNews
   */
  select?: Prisma.FlashNewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashNews
   */
  omit?: Prisma.FlashNewsOmit<ExtArgs> | null
  /**
   * The data needed to update a FlashNews.
   */
  data: Prisma.XOR<Prisma.FlashNewsUpdateInput, Prisma.FlashNewsUncheckedUpdateInput>
  /**
   * Choose, which FlashNews to update.
   */
  where: Prisma.FlashNewsWhereUniqueInput
}

/**
 * FlashNews updateMany
 */
export type FlashNewsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FlashNews.
   */
  data: Prisma.XOR<Prisma.FlashNewsUpdateManyMutationInput, Prisma.FlashNewsUncheckedUpdateManyInput>
  /**
   * Filter which FlashNews to update
   */
  where?: Prisma.FlashNewsWhereInput
  /**
   * Limit how many FlashNews to update.
   */
  limit?: number
}

/**
 * FlashNews updateManyAndReturn
 */
export type FlashNewsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashNews
   */
  select?: Prisma.FlashNewsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FlashNews
   */
  omit?: Prisma.FlashNewsOmit<ExtArgs> | null
  /**
   * The data used to update FlashNews.
   */
  data: Prisma.XOR<Prisma.FlashNewsUpdateManyMutationInput, Prisma.FlashNewsUncheckedUpdateManyInput>
  /**
   * Filter which FlashNews to update
   */
  where?: Prisma.FlashNewsWhereInput
  /**
   * Limit how many FlashNews to update.
   */
  limit?: number
}

/**
 * FlashNews upsert
 */
export type FlashNewsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashNews
   */
  select?: Prisma.FlashNewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashNews
   */
  omit?: Prisma.FlashNewsOmit<ExtArgs> | null
  /**
   * The filter to search for the FlashNews to update in case it exists.
   */
  where: Prisma.FlashNewsWhereUniqueInput
  /**
   * In case the FlashNews found by the `where` argument doesn't exist, create a new FlashNews with this data.
   */
  create: Prisma.XOR<Prisma.FlashNewsCreateInput, Prisma.FlashNewsUncheckedCreateInput>
  /**
   * In case the FlashNews was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FlashNewsUpdateInput, Prisma.FlashNewsUncheckedUpdateInput>
}

/**
 * FlashNews delete
 */
export type FlashNewsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashNews
   */
  select?: Prisma.FlashNewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashNews
   */
  omit?: Prisma.FlashNewsOmit<ExtArgs> | null
  /**
   * Filter which FlashNews to delete.
   */
  where: Prisma.FlashNewsWhereUniqueInput
}

/**
 * FlashNews deleteMany
 */
export type FlashNewsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FlashNews to delete
   */
  where?: Prisma.FlashNewsWhereInput
  /**
   * Limit how many FlashNews to delete.
   */
  limit?: number
}

/**
 * FlashNews without action
 */
export type FlashNewsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FlashNews
   */
  select?: Prisma.FlashNewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FlashNews
   */
  omit?: Prisma.FlashNewsOmit<ExtArgs> | null
}
