
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `FyugAdmissionSequence` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FyugAdmissionSequence
 * Atomic counter for FYUG application numbers (e.g. FYUG26-000001).
 */
export type FyugAdmissionSequenceModel = runtime.Types.Result.DefaultSelection<Prisma.$FyugAdmissionSequencePayload>

export type AggregateFyugAdmissionSequence = {
  _count: FyugAdmissionSequenceCountAggregateOutputType | null
  _avg: FyugAdmissionSequenceAvgAggregateOutputType | null
  _sum: FyugAdmissionSequenceSumAggregateOutputType | null
  _min: FyugAdmissionSequenceMinAggregateOutputType | null
  _max: FyugAdmissionSequenceMaxAggregateOutputType | null
}

export type FyugAdmissionSequenceAvgAggregateOutputType = {
  lastValue: number | null
}

export type FyugAdmissionSequenceSumAggregateOutputType = {
  lastValue: number | null
}

export type FyugAdmissionSequenceMinAggregateOutputType = {
  id: string | null
  prefix: string | null
  lastValue: number | null
  updatedAt: Date | null
}

export type FyugAdmissionSequenceMaxAggregateOutputType = {
  id: string | null
  prefix: string | null
  lastValue: number | null
  updatedAt: Date | null
}

export type FyugAdmissionSequenceCountAggregateOutputType = {
  id: number
  prefix: number
  lastValue: number
  updatedAt: number
  _all: number
}


export type FyugAdmissionSequenceAvgAggregateInputType = {
  lastValue?: true
}

export type FyugAdmissionSequenceSumAggregateInputType = {
  lastValue?: true
}

export type FyugAdmissionSequenceMinAggregateInputType = {
  id?: true
  prefix?: true
  lastValue?: true
  updatedAt?: true
}

export type FyugAdmissionSequenceMaxAggregateInputType = {
  id?: true
  prefix?: true
  lastValue?: true
  updatedAt?: true
}

export type FyugAdmissionSequenceCountAggregateInputType = {
  id?: true
  prefix?: true
  lastValue?: true
  updatedAt?: true
  _all?: true
}

export type FyugAdmissionSequenceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FyugAdmissionSequence to aggregate.
   */
  where?: Prisma.FyugAdmissionSequenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FyugAdmissionSequences to fetch.
   */
  orderBy?: Prisma.FyugAdmissionSequenceOrderByWithRelationInput | Prisma.FyugAdmissionSequenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FyugAdmissionSequenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FyugAdmissionSequences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FyugAdmissionSequences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FyugAdmissionSequences
  **/
  _count?: true | FyugAdmissionSequenceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FyugAdmissionSequenceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FyugAdmissionSequenceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FyugAdmissionSequenceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FyugAdmissionSequenceMaxAggregateInputType
}

export type GetFyugAdmissionSequenceAggregateType<T extends FyugAdmissionSequenceAggregateArgs> = {
      [P in keyof T & keyof AggregateFyugAdmissionSequence]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFyugAdmissionSequence[P]>
    : Prisma.GetScalarType<T[P], AggregateFyugAdmissionSequence[P]>
}




export type FyugAdmissionSequenceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FyugAdmissionSequenceWhereInput
  orderBy?: Prisma.FyugAdmissionSequenceOrderByWithAggregationInput | Prisma.FyugAdmissionSequenceOrderByWithAggregationInput[]
  by: Prisma.FyugAdmissionSequenceScalarFieldEnum[] | Prisma.FyugAdmissionSequenceScalarFieldEnum
  having?: Prisma.FyugAdmissionSequenceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FyugAdmissionSequenceCountAggregateInputType | true
  _avg?: FyugAdmissionSequenceAvgAggregateInputType
  _sum?: FyugAdmissionSequenceSumAggregateInputType
  _min?: FyugAdmissionSequenceMinAggregateInputType
  _max?: FyugAdmissionSequenceMaxAggregateInputType
}

export type FyugAdmissionSequenceGroupByOutputType = {
  id: string
  prefix: string
  lastValue: number
  updatedAt: Date
  _count: FyugAdmissionSequenceCountAggregateOutputType | null
  _avg: FyugAdmissionSequenceAvgAggregateOutputType | null
  _sum: FyugAdmissionSequenceSumAggregateOutputType | null
  _min: FyugAdmissionSequenceMinAggregateOutputType | null
  _max: FyugAdmissionSequenceMaxAggregateOutputType | null
}

type GetFyugAdmissionSequenceGroupByPayload<T extends FyugAdmissionSequenceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FyugAdmissionSequenceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FyugAdmissionSequenceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FyugAdmissionSequenceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FyugAdmissionSequenceGroupByOutputType[P]>
      }
    >
  >



export type FyugAdmissionSequenceWhereInput = {
  AND?: Prisma.FyugAdmissionSequenceWhereInput | Prisma.FyugAdmissionSequenceWhereInput[]
  OR?: Prisma.FyugAdmissionSequenceWhereInput[]
  NOT?: Prisma.FyugAdmissionSequenceWhereInput | Prisma.FyugAdmissionSequenceWhereInput[]
  id?: Prisma.StringFilter<"FyugAdmissionSequence"> | string
  prefix?: Prisma.StringFilter<"FyugAdmissionSequence"> | string
  lastValue?: Prisma.IntFilter<"FyugAdmissionSequence"> | number
  updatedAt?: Prisma.DateTimeFilter<"FyugAdmissionSequence"> | Date | string
}

export type FyugAdmissionSequenceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  prefix?: Prisma.SortOrder
  lastValue?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FyugAdmissionSequenceWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  prefix?: string
  AND?: Prisma.FyugAdmissionSequenceWhereInput | Prisma.FyugAdmissionSequenceWhereInput[]
  OR?: Prisma.FyugAdmissionSequenceWhereInput[]
  NOT?: Prisma.FyugAdmissionSequenceWhereInput | Prisma.FyugAdmissionSequenceWhereInput[]
  lastValue?: Prisma.IntFilter<"FyugAdmissionSequence"> | number
  updatedAt?: Prisma.DateTimeFilter<"FyugAdmissionSequence"> | Date | string
}, "id" | "prefix">

export type FyugAdmissionSequenceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  prefix?: Prisma.SortOrder
  lastValue?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FyugAdmissionSequenceCountOrderByAggregateInput
  _avg?: Prisma.FyugAdmissionSequenceAvgOrderByAggregateInput
  _max?: Prisma.FyugAdmissionSequenceMaxOrderByAggregateInput
  _min?: Prisma.FyugAdmissionSequenceMinOrderByAggregateInput
  _sum?: Prisma.FyugAdmissionSequenceSumOrderByAggregateInput
}

export type FyugAdmissionSequenceScalarWhereWithAggregatesInput = {
  AND?: Prisma.FyugAdmissionSequenceScalarWhereWithAggregatesInput | Prisma.FyugAdmissionSequenceScalarWhereWithAggregatesInput[]
  OR?: Prisma.FyugAdmissionSequenceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FyugAdmissionSequenceScalarWhereWithAggregatesInput | Prisma.FyugAdmissionSequenceScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FyugAdmissionSequence"> | string
  prefix?: Prisma.StringWithAggregatesFilter<"FyugAdmissionSequence"> | string
  lastValue?: Prisma.IntWithAggregatesFilter<"FyugAdmissionSequence"> | number
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"FyugAdmissionSequence"> | Date | string
}

export type FyugAdmissionSequenceCreateInput = {
  id?: string
  prefix: string
  lastValue?: number
  updatedAt?: Date | string
}

export type FyugAdmissionSequenceUncheckedCreateInput = {
  id?: string
  prefix: string
  lastValue?: number
  updatedAt?: Date | string
}

export type FyugAdmissionSequenceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  prefix?: Prisma.StringFieldUpdateOperationsInput | string
  lastValue?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FyugAdmissionSequenceUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  prefix?: Prisma.StringFieldUpdateOperationsInput | string
  lastValue?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FyugAdmissionSequenceCreateManyInput = {
  id?: string
  prefix: string
  lastValue?: number
  updatedAt?: Date | string
}

export type FyugAdmissionSequenceUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  prefix?: Prisma.StringFieldUpdateOperationsInput | string
  lastValue?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FyugAdmissionSequenceUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  prefix?: Prisma.StringFieldUpdateOperationsInput | string
  lastValue?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FyugAdmissionSequenceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  prefix?: Prisma.SortOrder
  lastValue?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FyugAdmissionSequenceAvgOrderByAggregateInput = {
  lastValue?: Prisma.SortOrder
}

export type FyugAdmissionSequenceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  prefix?: Prisma.SortOrder
  lastValue?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FyugAdmissionSequenceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  prefix?: Prisma.SortOrder
  lastValue?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FyugAdmissionSequenceSumOrderByAggregateInput = {
  lastValue?: Prisma.SortOrder
}



export type FyugAdmissionSequenceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  prefix?: boolean
  lastValue?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["fyugAdmissionSequence"]>

export type FyugAdmissionSequenceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  prefix?: boolean
  lastValue?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["fyugAdmissionSequence"]>

export type FyugAdmissionSequenceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  prefix?: boolean
  lastValue?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["fyugAdmissionSequence"]>

export type FyugAdmissionSequenceSelectScalar = {
  id?: boolean
  prefix?: boolean
  lastValue?: boolean
  updatedAt?: boolean
}

export type FyugAdmissionSequenceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "prefix" | "lastValue" | "updatedAt", ExtArgs["result"]["fyugAdmissionSequence"]>

export type $FyugAdmissionSequencePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FyugAdmissionSequence"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    prefix: string
    lastValue: number
    updatedAt: Date
  }, ExtArgs["result"]["fyugAdmissionSequence"]>
  composites: {}
}

export type FyugAdmissionSequenceGetPayload<S extends boolean | null | undefined | FyugAdmissionSequenceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FyugAdmissionSequencePayload, S>

export type FyugAdmissionSequenceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FyugAdmissionSequenceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FyugAdmissionSequenceCountAggregateInputType | true
  }

export interface FyugAdmissionSequenceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FyugAdmissionSequence'], meta: { name: 'FyugAdmissionSequence' } }
  /**
   * Find zero or one FyugAdmissionSequence that matches the filter.
   * @param {FyugAdmissionSequenceFindUniqueArgs} args - Arguments to find a FyugAdmissionSequence
   * @example
   * // Get one FyugAdmissionSequence
   * const fyugAdmissionSequence = await prisma.fyugAdmissionSequence.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FyugAdmissionSequenceFindUniqueArgs>(args: Prisma.SelectSubset<T, FyugAdmissionSequenceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FyugAdmissionSequenceClient<runtime.Types.Result.GetResult<Prisma.$FyugAdmissionSequencePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FyugAdmissionSequence that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FyugAdmissionSequenceFindUniqueOrThrowArgs} args - Arguments to find a FyugAdmissionSequence
   * @example
   * // Get one FyugAdmissionSequence
   * const fyugAdmissionSequence = await prisma.fyugAdmissionSequence.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FyugAdmissionSequenceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FyugAdmissionSequenceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FyugAdmissionSequenceClient<runtime.Types.Result.GetResult<Prisma.$FyugAdmissionSequencePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FyugAdmissionSequence that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FyugAdmissionSequenceFindFirstArgs} args - Arguments to find a FyugAdmissionSequence
   * @example
   * // Get one FyugAdmissionSequence
   * const fyugAdmissionSequence = await prisma.fyugAdmissionSequence.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FyugAdmissionSequenceFindFirstArgs>(args?: Prisma.SelectSubset<T, FyugAdmissionSequenceFindFirstArgs<ExtArgs>>): Prisma.Prisma__FyugAdmissionSequenceClient<runtime.Types.Result.GetResult<Prisma.$FyugAdmissionSequencePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FyugAdmissionSequence that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FyugAdmissionSequenceFindFirstOrThrowArgs} args - Arguments to find a FyugAdmissionSequence
   * @example
   * // Get one FyugAdmissionSequence
   * const fyugAdmissionSequence = await prisma.fyugAdmissionSequence.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FyugAdmissionSequenceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FyugAdmissionSequenceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FyugAdmissionSequenceClient<runtime.Types.Result.GetResult<Prisma.$FyugAdmissionSequencePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FyugAdmissionSequences that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FyugAdmissionSequenceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FyugAdmissionSequences
   * const fyugAdmissionSequences = await prisma.fyugAdmissionSequence.findMany()
   * 
   * // Get first 10 FyugAdmissionSequences
   * const fyugAdmissionSequences = await prisma.fyugAdmissionSequence.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const fyugAdmissionSequenceWithIdOnly = await prisma.fyugAdmissionSequence.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FyugAdmissionSequenceFindManyArgs>(args?: Prisma.SelectSubset<T, FyugAdmissionSequenceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FyugAdmissionSequencePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FyugAdmissionSequence.
   * @param {FyugAdmissionSequenceCreateArgs} args - Arguments to create a FyugAdmissionSequence.
   * @example
   * // Create one FyugAdmissionSequence
   * const FyugAdmissionSequence = await prisma.fyugAdmissionSequence.create({
   *   data: {
   *     // ... data to create a FyugAdmissionSequence
   *   }
   * })
   * 
   */
  create<T extends FyugAdmissionSequenceCreateArgs>(args: Prisma.SelectSubset<T, FyugAdmissionSequenceCreateArgs<ExtArgs>>): Prisma.Prisma__FyugAdmissionSequenceClient<runtime.Types.Result.GetResult<Prisma.$FyugAdmissionSequencePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FyugAdmissionSequences.
   * @param {FyugAdmissionSequenceCreateManyArgs} args - Arguments to create many FyugAdmissionSequences.
   * @example
   * // Create many FyugAdmissionSequences
   * const fyugAdmissionSequence = await prisma.fyugAdmissionSequence.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FyugAdmissionSequenceCreateManyArgs>(args?: Prisma.SelectSubset<T, FyugAdmissionSequenceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FyugAdmissionSequences and returns the data saved in the database.
   * @param {FyugAdmissionSequenceCreateManyAndReturnArgs} args - Arguments to create many FyugAdmissionSequences.
   * @example
   * // Create many FyugAdmissionSequences
   * const fyugAdmissionSequence = await prisma.fyugAdmissionSequence.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FyugAdmissionSequences and only return the `id`
   * const fyugAdmissionSequenceWithIdOnly = await prisma.fyugAdmissionSequence.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FyugAdmissionSequenceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FyugAdmissionSequenceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FyugAdmissionSequencePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FyugAdmissionSequence.
   * @param {FyugAdmissionSequenceDeleteArgs} args - Arguments to delete one FyugAdmissionSequence.
   * @example
   * // Delete one FyugAdmissionSequence
   * const FyugAdmissionSequence = await prisma.fyugAdmissionSequence.delete({
   *   where: {
   *     // ... filter to delete one FyugAdmissionSequence
   *   }
   * })
   * 
   */
  delete<T extends FyugAdmissionSequenceDeleteArgs>(args: Prisma.SelectSubset<T, FyugAdmissionSequenceDeleteArgs<ExtArgs>>): Prisma.Prisma__FyugAdmissionSequenceClient<runtime.Types.Result.GetResult<Prisma.$FyugAdmissionSequencePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FyugAdmissionSequence.
   * @param {FyugAdmissionSequenceUpdateArgs} args - Arguments to update one FyugAdmissionSequence.
   * @example
   * // Update one FyugAdmissionSequence
   * const fyugAdmissionSequence = await prisma.fyugAdmissionSequence.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FyugAdmissionSequenceUpdateArgs>(args: Prisma.SelectSubset<T, FyugAdmissionSequenceUpdateArgs<ExtArgs>>): Prisma.Prisma__FyugAdmissionSequenceClient<runtime.Types.Result.GetResult<Prisma.$FyugAdmissionSequencePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FyugAdmissionSequences.
   * @param {FyugAdmissionSequenceDeleteManyArgs} args - Arguments to filter FyugAdmissionSequences to delete.
   * @example
   * // Delete a few FyugAdmissionSequences
   * const { count } = await prisma.fyugAdmissionSequence.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FyugAdmissionSequenceDeleteManyArgs>(args?: Prisma.SelectSubset<T, FyugAdmissionSequenceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FyugAdmissionSequences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FyugAdmissionSequenceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FyugAdmissionSequences
   * const fyugAdmissionSequence = await prisma.fyugAdmissionSequence.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FyugAdmissionSequenceUpdateManyArgs>(args: Prisma.SelectSubset<T, FyugAdmissionSequenceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FyugAdmissionSequences and returns the data updated in the database.
   * @param {FyugAdmissionSequenceUpdateManyAndReturnArgs} args - Arguments to update many FyugAdmissionSequences.
   * @example
   * // Update many FyugAdmissionSequences
   * const fyugAdmissionSequence = await prisma.fyugAdmissionSequence.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FyugAdmissionSequences and only return the `id`
   * const fyugAdmissionSequenceWithIdOnly = await prisma.fyugAdmissionSequence.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FyugAdmissionSequenceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FyugAdmissionSequenceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FyugAdmissionSequencePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FyugAdmissionSequence.
   * @param {FyugAdmissionSequenceUpsertArgs} args - Arguments to update or create a FyugAdmissionSequence.
   * @example
   * // Update or create a FyugAdmissionSequence
   * const fyugAdmissionSequence = await prisma.fyugAdmissionSequence.upsert({
   *   create: {
   *     // ... data to create a FyugAdmissionSequence
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FyugAdmissionSequence we want to update
   *   }
   * })
   */
  upsert<T extends FyugAdmissionSequenceUpsertArgs>(args: Prisma.SelectSubset<T, FyugAdmissionSequenceUpsertArgs<ExtArgs>>): Prisma.Prisma__FyugAdmissionSequenceClient<runtime.Types.Result.GetResult<Prisma.$FyugAdmissionSequencePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FyugAdmissionSequences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FyugAdmissionSequenceCountArgs} args - Arguments to filter FyugAdmissionSequences to count.
   * @example
   * // Count the number of FyugAdmissionSequences
   * const count = await prisma.fyugAdmissionSequence.count({
   *   where: {
   *     // ... the filter for the FyugAdmissionSequences we want to count
   *   }
   * })
  **/
  count<T extends FyugAdmissionSequenceCountArgs>(
    args?: Prisma.Subset<T, FyugAdmissionSequenceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FyugAdmissionSequenceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FyugAdmissionSequence.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FyugAdmissionSequenceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FyugAdmissionSequenceAggregateArgs>(args: Prisma.Subset<T, FyugAdmissionSequenceAggregateArgs>): Prisma.PrismaPromise<GetFyugAdmissionSequenceAggregateType<T>>

  /**
   * Group by FyugAdmissionSequence.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FyugAdmissionSequenceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FyugAdmissionSequenceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FyugAdmissionSequenceGroupByArgs['orderBy'] }
      : { orderBy?: FyugAdmissionSequenceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FyugAdmissionSequenceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFyugAdmissionSequenceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FyugAdmissionSequence model
 */
readonly fields: FyugAdmissionSequenceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FyugAdmissionSequence.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FyugAdmissionSequenceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FyugAdmissionSequence model
 */
export interface FyugAdmissionSequenceFieldRefs {
  readonly id: Prisma.FieldRef<"FyugAdmissionSequence", 'String'>
  readonly prefix: Prisma.FieldRef<"FyugAdmissionSequence", 'String'>
  readonly lastValue: Prisma.FieldRef<"FyugAdmissionSequence", 'Int'>
  readonly updatedAt: Prisma.FieldRef<"FyugAdmissionSequence", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FyugAdmissionSequence findUnique
 */
export type FyugAdmissionSequenceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FyugAdmissionSequence
   */
  select?: Prisma.FyugAdmissionSequenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FyugAdmissionSequence
   */
  omit?: Prisma.FyugAdmissionSequenceOmit<ExtArgs> | null
  /**
   * Filter, which FyugAdmissionSequence to fetch.
   */
  where: Prisma.FyugAdmissionSequenceWhereUniqueInput
}

/**
 * FyugAdmissionSequence findUniqueOrThrow
 */
export type FyugAdmissionSequenceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FyugAdmissionSequence
   */
  select?: Prisma.FyugAdmissionSequenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FyugAdmissionSequence
   */
  omit?: Prisma.FyugAdmissionSequenceOmit<ExtArgs> | null
  /**
   * Filter, which FyugAdmissionSequence to fetch.
   */
  where: Prisma.FyugAdmissionSequenceWhereUniqueInput
}

/**
 * FyugAdmissionSequence findFirst
 */
export type FyugAdmissionSequenceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FyugAdmissionSequence
   */
  select?: Prisma.FyugAdmissionSequenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FyugAdmissionSequence
   */
  omit?: Prisma.FyugAdmissionSequenceOmit<ExtArgs> | null
  /**
   * Filter, which FyugAdmissionSequence to fetch.
   */
  where?: Prisma.FyugAdmissionSequenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FyugAdmissionSequences to fetch.
   */
  orderBy?: Prisma.FyugAdmissionSequenceOrderByWithRelationInput | Prisma.FyugAdmissionSequenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FyugAdmissionSequences.
   */
  cursor?: Prisma.FyugAdmissionSequenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FyugAdmissionSequences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FyugAdmissionSequences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FyugAdmissionSequences.
   */
  distinct?: Prisma.FyugAdmissionSequenceScalarFieldEnum | Prisma.FyugAdmissionSequenceScalarFieldEnum[]
}

/**
 * FyugAdmissionSequence findFirstOrThrow
 */
export type FyugAdmissionSequenceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FyugAdmissionSequence
   */
  select?: Prisma.FyugAdmissionSequenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FyugAdmissionSequence
   */
  omit?: Prisma.FyugAdmissionSequenceOmit<ExtArgs> | null
  /**
   * Filter, which FyugAdmissionSequence to fetch.
   */
  where?: Prisma.FyugAdmissionSequenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FyugAdmissionSequences to fetch.
   */
  orderBy?: Prisma.FyugAdmissionSequenceOrderByWithRelationInput | Prisma.FyugAdmissionSequenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FyugAdmissionSequences.
   */
  cursor?: Prisma.FyugAdmissionSequenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FyugAdmissionSequences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FyugAdmissionSequences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FyugAdmissionSequences.
   */
  distinct?: Prisma.FyugAdmissionSequenceScalarFieldEnum | Prisma.FyugAdmissionSequenceScalarFieldEnum[]
}

/**
 * FyugAdmissionSequence findMany
 */
export type FyugAdmissionSequenceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FyugAdmissionSequence
   */
  select?: Prisma.FyugAdmissionSequenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FyugAdmissionSequence
   */
  omit?: Prisma.FyugAdmissionSequenceOmit<ExtArgs> | null
  /**
   * Filter, which FyugAdmissionSequences to fetch.
   */
  where?: Prisma.FyugAdmissionSequenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FyugAdmissionSequences to fetch.
   */
  orderBy?: Prisma.FyugAdmissionSequenceOrderByWithRelationInput | Prisma.FyugAdmissionSequenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FyugAdmissionSequences.
   */
  cursor?: Prisma.FyugAdmissionSequenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FyugAdmissionSequences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FyugAdmissionSequences.
   */
  skip?: number
  distinct?: Prisma.FyugAdmissionSequenceScalarFieldEnum | Prisma.FyugAdmissionSequenceScalarFieldEnum[]
}

/**
 * FyugAdmissionSequence create
 */
export type FyugAdmissionSequenceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FyugAdmissionSequence
   */
  select?: Prisma.FyugAdmissionSequenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FyugAdmissionSequence
   */
  omit?: Prisma.FyugAdmissionSequenceOmit<ExtArgs> | null
  /**
   * The data needed to create a FyugAdmissionSequence.
   */
  data: Prisma.XOR<Prisma.FyugAdmissionSequenceCreateInput, Prisma.FyugAdmissionSequenceUncheckedCreateInput>
}

/**
 * FyugAdmissionSequence createMany
 */
export type FyugAdmissionSequenceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FyugAdmissionSequences.
   */
  data: Prisma.FyugAdmissionSequenceCreateManyInput | Prisma.FyugAdmissionSequenceCreateManyInput[]
}

/**
 * FyugAdmissionSequence createManyAndReturn
 */
export type FyugAdmissionSequenceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FyugAdmissionSequence
   */
  select?: Prisma.FyugAdmissionSequenceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FyugAdmissionSequence
   */
  omit?: Prisma.FyugAdmissionSequenceOmit<ExtArgs> | null
  /**
   * The data used to create many FyugAdmissionSequences.
   */
  data: Prisma.FyugAdmissionSequenceCreateManyInput | Prisma.FyugAdmissionSequenceCreateManyInput[]
}

/**
 * FyugAdmissionSequence update
 */
export type FyugAdmissionSequenceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FyugAdmissionSequence
   */
  select?: Prisma.FyugAdmissionSequenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FyugAdmissionSequence
   */
  omit?: Prisma.FyugAdmissionSequenceOmit<ExtArgs> | null
  /**
   * The data needed to update a FyugAdmissionSequence.
   */
  data: Prisma.XOR<Prisma.FyugAdmissionSequenceUpdateInput, Prisma.FyugAdmissionSequenceUncheckedUpdateInput>
  /**
   * Choose, which FyugAdmissionSequence to update.
   */
  where: Prisma.FyugAdmissionSequenceWhereUniqueInput
}

/**
 * FyugAdmissionSequence updateMany
 */
export type FyugAdmissionSequenceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FyugAdmissionSequences.
   */
  data: Prisma.XOR<Prisma.FyugAdmissionSequenceUpdateManyMutationInput, Prisma.FyugAdmissionSequenceUncheckedUpdateManyInput>
  /**
   * Filter which FyugAdmissionSequences to update
   */
  where?: Prisma.FyugAdmissionSequenceWhereInput
  /**
   * Limit how many FyugAdmissionSequences to update.
   */
  limit?: number
}

/**
 * FyugAdmissionSequence updateManyAndReturn
 */
export type FyugAdmissionSequenceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FyugAdmissionSequence
   */
  select?: Prisma.FyugAdmissionSequenceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FyugAdmissionSequence
   */
  omit?: Prisma.FyugAdmissionSequenceOmit<ExtArgs> | null
  /**
   * The data used to update FyugAdmissionSequences.
   */
  data: Prisma.XOR<Prisma.FyugAdmissionSequenceUpdateManyMutationInput, Prisma.FyugAdmissionSequenceUncheckedUpdateManyInput>
  /**
   * Filter which FyugAdmissionSequences to update
   */
  where?: Prisma.FyugAdmissionSequenceWhereInput
  /**
   * Limit how many FyugAdmissionSequences to update.
   */
  limit?: number
}

/**
 * FyugAdmissionSequence upsert
 */
export type FyugAdmissionSequenceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FyugAdmissionSequence
   */
  select?: Prisma.FyugAdmissionSequenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FyugAdmissionSequence
   */
  omit?: Prisma.FyugAdmissionSequenceOmit<ExtArgs> | null
  /**
   * The filter to search for the FyugAdmissionSequence to update in case it exists.
   */
  where: Prisma.FyugAdmissionSequenceWhereUniqueInput
  /**
   * In case the FyugAdmissionSequence found by the `where` argument doesn't exist, create a new FyugAdmissionSequence with this data.
   */
  create: Prisma.XOR<Prisma.FyugAdmissionSequenceCreateInput, Prisma.FyugAdmissionSequenceUncheckedCreateInput>
  /**
   * In case the FyugAdmissionSequence was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FyugAdmissionSequenceUpdateInput, Prisma.FyugAdmissionSequenceUncheckedUpdateInput>
}

/**
 * FyugAdmissionSequence delete
 */
export type FyugAdmissionSequenceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FyugAdmissionSequence
   */
  select?: Prisma.FyugAdmissionSequenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FyugAdmissionSequence
   */
  omit?: Prisma.FyugAdmissionSequenceOmit<ExtArgs> | null
  /**
   * Filter which FyugAdmissionSequence to delete.
   */
  where: Prisma.FyugAdmissionSequenceWhereUniqueInput
}

/**
 * FyugAdmissionSequence deleteMany
 */
export type FyugAdmissionSequenceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FyugAdmissionSequences to delete
   */
  where?: Prisma.FyugAdmissionSequenceWhereInput
  /**
   * Limit how many FyugAdmissionSequences to delete.
   */
  limit?: number
}

/**
 * FyugAdmissionSequence without action
 */
export type FyugAdmissionSequenceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FyugAdmissionSequence
   */
  select?: Prisma.FyugAdmissionSequenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FyugAdmissionSequence
   */
  omit?: Prisma.FyugAdmissionSequenceOmit<ExtArgs> | null
}
