
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `NoticeBoardEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model NoticeBoardEvent
 * 
 */
export type NoticeBoardEventModel = runtime.Types.Result.DefaultSelection<Prisma.$NoticeBoardEventPayload>

export type AggregateNoticeBoardEvent = {
  _count: NoticeBoardEventCountAggregateOutputType | null
  _avg: NoticeBoardEventAvgAggregateOutputType | null
  _sum: NoticeBoardEventSumAggregateOutputType | null
  _min: NoticeBoardEventMinAggregateOutputType | null
  _max: NoticeBoardEventMaxAggregateOutputType | null
}

export type NoticeBoardEventAvgAggregateOutputType = {
  displayOrder: number | null
}

export type NoticeBoardEventSumAggregateOutputType = {
  displayOrder: number | null
}

export type NoticeBoardEventMinAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  eventDate: Date | null
  displayOrder: number | null
  published: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type NoticeBoardEventMaxAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  eventDate: Date | null
  displayOrder: number | null
  published: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type NoticeBoardEventCountAggregateOutputType = {
  id: number
  title: number
  description: number
  eventDate: number
  displayOrder: number
  published: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type NoticeBoardEventAvgAggregateInputType = {
  displayOrder?: true
}

export type NoticeBoardEventSumAggregateInputType = {
  displayOrder?: true
}

export type NoticeBoardEventMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  eventDate?: true
  displayOrder?: true
  published?: true
  createdAt?: true
  updatedAt?: true
}

export type NoticeBoardEventMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  eventDate?: true
  displayOrder?: true
  published?: true
  createdAt?: true
  updatedAt?: true
}

export type NoticeBoardEventCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  eventDate?: true
  displayOrder?: true
  published?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type NoticeBoardEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NoticeBoardEvent to aggregate.
   */
  where?: Prisma.NoticeBoardEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NoticeBoardEvents to fetch.
   */
  orderBy?: Prisma.NoticeBoardEventOrderByWithRelationInput | Prisma.NoticeBoardEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NoticeBoardEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NoticeBoardEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NoticeBoardEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned NoticeBoardEvents
  **/
  _count?: true | NoticeBoardEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NoticeBoardEventAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NoticeBoardEventSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NoticeBoardEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NoticeBoardEventMaxAggregateInputType
}

export type GetNoticeBoardEventAggregateType<T extends NoticeBoardEventAggregateArgs> = {
      [P in keyof T & keyof AggregateNoticeBoardEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNoticeBoardEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateNoticeBoardEvent[P]>
}




export type NoticeBoardEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NoticeBoardEventWhereInput
  orderBy?: Prisma.NoticeBoardEventOrderByWithAggregationInput | Prisma.NoticeBoardEventOrderByWithAggregationInput[]
  by: Prisma.NoticeBoardEventScalarFieldEnum[] | Prisma.NoticeBoardEventScalarFieldEnum
  having?: Prisma.NoticeBoardEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NoticeBoardEventCountAggregateInputType | true
  _avg?: NoticeBoardEventAvgAggregateInputType
  _sum?: NoticeBoardEventSumAggregateInputType
  _min?: NoticeBoardEventMinAggregateInputType
  _max?: NoticeBoardEventMaxAggregateInputType
}

export type NoticeBoardEventGroupByOutputType = {
  id: string
  title: string
  description: string | null
  eventDate: Date
  displayOrder: number
  published: boolean
  createdAt: Date
  updatedAt: Date
  _count: NoticeBoardEventCountAggregateOutputType | null
  _avg: NoticeBoardEventAvgAggregateOutputType | null
  _sum: NoticeBoardEventSumAggregateOutputType | null
  _min: NoticeBoardEventMinAggregateOutputType | null
  _max: NoticeBoardEventMaxAggregateOutputType | null
}

type GetNoticeBoardEventGroupByPayload<T extends NoticeBoardEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NoticeBoardEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NoticeBoardEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NoticeBoardEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NoticeBoardEventGroupByOutputType[P]>
      }
    >
  >



export type NoticeBoardEventWhereInput = {
  AND?: Prisma.NoticeBoardEventWhereInput | Prisma.NoticeBoardEventWhereInput[]
  OR?: Prisma.NoticeBoardEventWhereInput[]
  NOT?: Prisma.NoticeBoardEventWhereInput | Prisma.NoticeBoardEventWhereInput[]
  id?: Prisma.StringFilter<"NoticeBoardEvent"> | string
  title?: Prisma.StringFilter<"NoticeBoardEvent"> | string
  description?: Prisma.StringNullableFilter<"NoticeBoardEvent"> | string | null
  eventDate?: Prisma.DateTimeFilter<"NoticeBoardEvent"> | Date | string
  displayOrder?: Prisma.IntFilter<"NoticeBoardEvent"> | number
  published?: Prisma.BoolFilter<"NoticeBoardEvent"> | boolean
  createdAt?: Prisma.DateTimeFilter<"NoticeBoardEvent"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"NoticeBoardEvent"> | Date | string
}

export type NoticeBoardEventOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  eventDate?: Prisma.SortOrder
  displayOrder?: Prisma.SortOrder
  published?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NoticeBoardEventWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.NoticeBoardEventWhereInput | Prisma.NoticeBoardEventWhereInput[]
  OR?: Prisma.NoticeBoardEventWhereInput[]
  NOT?: Prisma.NoticeBoardEventWhereInput | Prisma.NoticeBoardEventWhereInput[]
  title?: Prisma.StringFilter<"NoticeBoardEvent"> | string
  description?: Prisma.StringNullableFilter<"NoticeBoardEvent"> | string | null
  eventDate?: Prisma.DateTimeFilter<"NoticeBoardEvent"> | Date | string
  displayOrder?: Prisma.IntFilter<"NoticeBoardEvent"> | number
  published?: Prisma.BoolFilter<"NoticeBoardEvent"> | boolean
  createdAt?: Prisma.DateTimeFilter<"NoticeBoardEvent"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"NoticeBoardEvent"> | Date | string
}, "id">

export type NoticeBoardEventOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  eventDate?: Prisma.SortOrder
  displayOrder?: Prisma.SortOrder
  published?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.NoticeBoardEventCountOrderByAggregateInput
  _avg?: Prisma.NoticeBoardEventAvgOrderByAggregateInput
  _max?: Prisma.NoticeBoardEventMaxOrderByAggregateInput
  _min?: Prisma.NoticeBoardEventMinOrderByAggregateInput
  _sum?: Prisma.NoticeBoardEventSumOrderByAggregateInput
}

export type NoticeBoardEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.NoticeBoardEventScalarWhereWithAggregatesInput | Prisma.NoticeBoardEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.NoticeBoardEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NoticeBoardEventScalarWhereWithAggregatesInput | Prisma.NoticeBoardEventScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"NoticeBoardEvent"> | string
  title?: Prisma.StringWithAggregatesFilter<"NoticeBoardEvent"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"NoticeBoardEvent"> | string | null
  eventDate?: Prisma.DateTimeWithAggregatesFilter<"NoticeBoardEvent"> | Date | string
  displayOrder?: Prisma.IntWithAggregatesFilter<"NoticeBoardEvent"> | number
  published?: Prisma.BoolWithAggregatesFilter<"NoticeBoardEvent"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"NoticeBoardEvent"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"NoticeBoardEvent"> | Date | string
}

export type NoticeBoardEventCreateInput = {
  id?: string
  title: string
  description?: string | null
  eventDate: Date | string
  displayOrder?: number
  published?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NoticeBoardEventUncheckedCreateInput = {
  id?: string
  title: string
  description?: string | null
  eventDate: Date | string
  displayOrder?: number
  published?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NoticeBoardEventUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eventDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  displayOrder?: Prisma.IntFieldUpdateOperationsInput | number
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NoticeBoardEventUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eventDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  displayOrder?: Prisma.IntFieldUpdateOperationsInput | number
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NoticeBoardEventCreateManyInput = {
  id?: string
  title: string
  description?: string | null
  eventDate: Date | string
  displayOrder?: number
  published?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NoticeBoardEventUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eventDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  displayOrder?: Prisma.IntFieldUpdateOperationsInput | number
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NoticeBoardEventUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eventDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  displayOrder?: Prisma.IntFieldUpdateOperationsInput | number
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NoticeBoardEventCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  eventDate?: Prisma.SortOrder
  displayOrder?: Prisma.SortOrder
  published?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NoticeBoardEventAvgOrderByAggregateInput = {
  displayOrder?: Prisma.SortOrder
}

export type NoticeBoardEventMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  eventDate?: Prisma.SortOrder
  displayOrder?: Prisma.SortOrder
  published?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NoticeBoardEventMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  eventDate?: Prisma.SortOrder
  displayOrder?: Prisma.SortOrder
  published?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NoticeBoardEventSumOrderByAggregateInput = {
  displayOrder?: Prisma.SortOrder
}



export type NoticeBoardEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  eventDate?: boolean
  displayOrder?: boolean
  published?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["noticeBoardEvent"]>

export type NoticeBoardEventSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  eventDate?: boolean
  displayOrder?: boolean
  published?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["noticeBoardEvent"]>

export type NoticeBoardEventSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  eventDate?: boolean
  displayOrder?: boolean
  published?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["noticeBoardEvent"]>

export type NoticeBoardEventSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  eventDate?: boolean
  displayOrder?: boolean
  published?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type NoticeBoardEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "eventDate" | "displayOrder" | "published" | "createdAt" | "updatedAt", ExtArgs["result"]["noticeBoardEvent"]>

export type $NoticeBoardEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "NoticeBoardEvent"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    description: string | null
    eventDate: Date
    displayOrder: number
    published: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["noticeBoardEvent"]>
  composites: {}
}

export type NoticeBoardEventGetPayload<S extends boolean | null | undefined | NoticeBoardEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NoticeBoardEventPayload, S>

export type NoticeBoardEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NoticeBoardEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NoticeBoardEventCountAggregateInputType | true
  }

export interface NoticeBoardEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['NoticeBoardEvent'], meta: { name: 'NoticeBoardEvent' } }
  /**
   * Find zero or one NoticeBoardEvent that matches the filter.
   * @param {NoticeBoardEventFindUniqueArgs} args - Arguments to find a NoticeBoardEvent
   * @example
   * // Get one NoticeBoardEvent
   * const noticeBoardEvent = await prisma.noticeBoardEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NoticeBoardEventFindUniqueArgs>(args: Prisma.SelectSubset<T, NoticeBoardEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NoticeBoardEventClient<runtime.Types.Result.GetResult<Prisma.$NoticeBoardEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one NoticeBoardEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NoticeBoardEventFindUniqueOrThrowArgs} args - Arguments to find a NoticeBoardEvent
   * @example
   * // Get one NoticeBoardEvent
   * const noticeBoardEvent = await prisma.noticeBoardEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NoticeBoardEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NoticeBoardEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NoticeBoardEventClient<runtime.Types.Result.GetResult<Prisma.$NoticeBoardEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NoticeBoardEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NoticeBoardEventFindFirstArgs} args - Arguments to find a NoticeBoardEvent
   * @example
   * // Get one NoticeBoardEvent
   * const noticeBoardEvent = await prisma.noticeBoardEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NoticeBoardEventFindFirstArgs>(args?: Prisma.SelectSubset<T, NoticeBoardEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__NoticeBoardEventClient<runtime.Types.Result.GetResult<Prisma.$NoticeBoardEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NoticeBoardEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NoticeBoardEventFindFirstOrThrowArgs} args - Arguments to find a NoticeBoardEvent
   * @example
   * // Get one NoticeBoardEvent
   * const noticeBoardEvent = await prisma.noticeBoardEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NoticeBoardEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NoticeBoardEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NoticeBoardEventClient<runtime.Types.Result.GetResult<Prisma.$NoticeBoardEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more NoticeBoardEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NoticeBoardEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all NoticeBoardEvents
   * const noticeBoardEvents = await prisma.noticeBoardEvent.findMany()
   * 
   * // Get first 10 NoticeBoardEvents
   * const noticeBoardEvents = await prisma.noticeBoardEvent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const noticeBoardEventWithIdOnly = await prisma.noticeBoardEvent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NoticeBoardEventFindManyArgs>(args?: Prisma.SelectSubset<T, NoticeBoardEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NoticeBoardEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a NoticeBoardEvent.
   * @param {NoticeBoardEventCreateArgs} args - Arguments to create a NoticeBoardEvent.
   * @example
   * // Create one NoticeBoardEvent
   * const NoticeBoardEvent = await prisma.noticeBoardEvent.create({
   *   data: {
   *     // ... data to create a NoticeBoardEvent
   *   }
   * })
   * 
   */
  create<T extends NoticeBoardEventCreateArgs>(args: Prisma.SelectSubset<T, NoticeBoardEventCreateArgs<ExtArgs>>): Prisma.Prisma__NoticeBoardEventClient<runtime.Types.Result.GetResult<Prisma.$NoticeBoardEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many NoticeBoardEvents.
   * @param {NoticeBoardEventCreateManyArgs} args - Arguments to create many NoticeBoardEvents.
   * @example
   * // Create many NoticeBoardEvents
   * const noticeBoardEvent = await prisma.noticeBoardEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NoticeBoardEventCreateManyArgs>(args?: Prisma.SelectSubset<T, NoticeBoardEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many NoticeBoardEvents and returns the data saved in the database.
   * @param {NoticeBoardEventCreateManyAndReturnArgs} args - Arguments to create many NoticeBoardEvents.
   * @example
   * // Create many NoticeBoardEvents
   * const noticeBoardEvent = await prisma.noticeBoardEvent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many NoticeBoardEvents and only return the `id`
   * const noticeBoardEventWithIdOnly = await prisma.noticeBoardEvent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NoticeBoardEventCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NoticeBoardEventCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NoticeBoardEventPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a NoticeBoardEvent.
   * @param {NoticeBoardEventDeleteArgs} args - Arguments to delete one NoticeBoardEvent.
   * @example
   * // Delete one NoticeBoardEvent
   * const NoticeBoardEvent = await prisma.noticeBoardEvent.delete({
   *   where: {
   *     // ... filter to delete one NoticeBoardEvent
   *   }
   * })
   * 
   */
  delete<T extends NoticeBoardEventDeleteArgs>(args: Prisma.SelectSubset<T, NoticeBoardEventDeleteArgs<ExtArgs>>): Prisma.Prisma__NoticeBoardEventClient<runtime.Types.Result.GetResult<Prisma.$NoticeBoardEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one NoticeBoardEvent.
   * @param {NoticeBoardEventUpdateArgs} args - Arguments to update one NoticeBoardEvent.
   * @example
   * // Update one NoticeBoardEvent
   * const noticeBoardEvent = await prisma.noticeBoardEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NoticeBoardEventUpdateArgs>(args: Prisma.SelectSubset<T, NoticeBoardEventUpdateArgs<ExtArgs>>): Prisma.Prisma__NoticeBoardEventClient<runtime.Types.Result.GetResult<Prisma.$NoticeBoardEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more NoticeBoardEvents.
   * @param {NoticeBoardEventDeleteManyArgs} args - Arguments to filter NoticeBoardEvents to delete.
   * @example
   * // Delete a few NoticeBoardEvents
   * const { count } = await prisma.noticeBoardEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NoticeBoardEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, NoticeBoardEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NoticeBoardEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NoticeBoardEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many NoticeBoardEvents
   * const noticeBoardEvent = await prisma.noticeBoardEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NoticeBoardEventUpdateManyArgs>(args: Prisma.SelectSubset<T, NoticeBoardEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NoticeBoardEvents and returns the data updated in the database.
   * @param {NoticeBoardEventUpdateManyAndReturnArgs} args - Arguments to update many NoticeBoardEvents.
   * @example
   * // Update many NoticeBoardEvents
   * const noticeBoardEvent = await prisma.noticeBoardEvent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more NoticeBoardEvents and only return the `id`
   * const noticeBoardEventWithIdOnly = await prisma.noticeBoardEvent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NoticeBoardEventUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NoticeBoardEventUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NoticeBoardEventPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one NoticeBoardEvent.
   * @param {NoticeBoardEventUpsertArgs} args - Arguments to update or create a NoticeBoardEvent.
   * @example
   * // Update or create a NoticeBoardEvent
   * const noticeBoardEvent = await prisma.noticeBoardEvent.upsert({
   *   create: {
   *     // ... data to create a NoticeBoardEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the NoticeBoardEvent we want to update
   *   }
   * })
   */
  upsert<T extends NoticeBoardEventUpsertArgs>(args: Prisma.SelectSubset<T, NoticeBoardEventUpsertArgs<ExtArgs>>): Prisma.Prisma__NoticeBoardEventClient<runtime.Types.Result.GetResult<Prisma.$NoticeBoardEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of NoticeBoardEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NoticeBoardEventCountArgs} args - Arguments to filter NoticeBoardEvents to count.
   * @example
   * // Count the number of NoticeBoardEvents
   * const count = await prisma.noticeBoardEvent.count({
   *   where: {
   *     // ... the filter for the NoticeBoardEvents we want to count
   *   }
   * })
  **/
  count<T extends NoticeBoardEventCountArgs>(
    args?: Prisma.Subset<T, NoticeBoardEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NoticeBoardEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a NoticeBoardEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NoticeBoardEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NoticeBoardEventAggregateArgs>(args: Prisma.Subset<T, NoticeBoardEventAggregateArgs>): Prisma.PrismaPromise<GetNoticeBoardEventAggregateType<T>>

  /**
   * Group by NoticeBoardEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NoticeBoardEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NoticeBoardEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NoticeBoardEventGroupByArgs['orderBy'] }
      : { orderBy?: NoticeBoardEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NoticeBoardEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNoticeBoardEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the NoticeBoardEvent model
 */
readonly fields: NoticeBoardEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for NoticeBoardEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NoticeBoardEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the NoticeBoardEvent model
 */
export interface NoticeBoardEventFieldRefs {
  readonly id: Prisma.FieldRef<"NoticeBoardEvent", 'String'>
  readonly title: Prisma.FieldRef<"NoticeBoardEvent", 'String'>
  readonly description: Prisma.FieldRef<"NoticeBoardEvent", 'String'>
  readonly eventDate: Prisma.FieldRef<"NoticeBoardEvent", 'DateTime'>
  readonly displayOrder: Prisma.FieldRef<"NoticeBoardEvent", 'Int'>
  readonly published: Prisma.FieldRef<"NoticeBoardEvent", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"NoticeBoardEvent", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"NoticeBoardEvent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * NoticeBoardEvent findUnique
 */
export type NoticeBoardEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NoticeBoardEvent
   */
  select?: Prisma.NoticeBoardEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NoticeBoardEvent
   */
  omit?: Prisma.NoticeBoardEventOmit<ExtArgs> | null
  /**
   * Filter, which NoticeBoardEvent to fetch.
   */
  where: Prisma.NoticeBoardEventWhereUniqueInput
}

/**
 * NoticeBoardEvent findUniqueOrThrow
 */
export type NoticeBoardEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NoticeBoardEvent
   */
  select?: Prisma.NoticeBoardEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NoticeBoardEvent
   */
  omit?: Prisma.NoticeBoardEventOmit<ExtArgs> | null
  /**
   * Filter, which NoticeBoardEvent to fetch.
   */
  where: Prisma.NoticeBoardEventWhereUniqueInput
}

/**
 * NoticeBoardEvent findFirst
 */
export type NoticeBoardEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NoticeBoardEvent
   */
  select?: Prisma.NoticeBoardEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NoticeBoardEvent
   */
  omit?: Prisma.NoticeBoardEventOmit<ExtArgs> | null
  /**
   * Filter, which NoticeBoardEvent to fetch.
   */
  where?: Prisma.NoticeBoardEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NoticeBoardEvents to fetch.
   */
  orderBy?: Prisma.NoticeBoardEventOrderByWithRelationInput | Prisma.NoticeBoardEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NoticeBoardEvents.
   */
  cursor?: Prisma.NoticeBoardEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NoticeBoardEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NoticeBoardEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NoticeBoardEvents.
   */
  distinct?: Prisma.NoticeBoardEventScalarFieldEnum | Prisma.NoticeBoardEventScalarFieldEnum[]
}

/**
 * NoticeBoardEvent findFirstOrThrow
 */
export type NoticeBoardEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NoticeBoardEvent
   */
  select?: Prisma.NoticeBoardEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NoticeBoardEvent
   */
  omit?: Prisma.NoticeBoardEventOmit<ExtArgs> | null
  /**
   * Filter, which NoticeBoardEvent to fetch.
   */
  where?: Prisma.NoticeBoardEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NoticeBoardEvents to fetch.
   */
  orderBy?: Prisma.NoticeBoardEventOrderByWithRelationInput | Prisma.NoticeBoardEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NoticeBoardEvents.
   */
  cursor?: Prisma.NoticeBoardEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NoticeBoardEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NoticeBoardEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NoticeBoardEvents.
   */
  distinct?: Prisma.NoticeBoardEventScalarFieldEnum | Prisma.NoticeBoardEventScalarFieldEnum[]
}

/**
 * NoticeBoardEvent findMany
 */
export type NoticeBoardEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NoticeBoardEvent
   */
  select?: Prisma.NoticeBoardEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NoticeBoardEvent
   */
  omit?: Prisma.NoticeBoardEventOmit<ExtArgs> | null
  /**
   * Filter, which NoticeBoardEvents to fetch.
   */
  where?: Prisma.NoticeBoardEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NoticeBoardEvents to fetch.
   */
  orderBy?: Prisma.NoticeBoardEventOrderByWithRelationInput | Prisma.NoticeBoardEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing NoticeBoardEvents.
   */
  cursor?: Prisma.NoticeBoardEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NoticeBoardEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NoticeBoardEvents.
   */
  skip?: number
  distinct?: Prisma.NoticeBoardEventScalarFieldEnum | Prisma.NoticeBoardEventScalarFieldEnum[]
}

/**
 * NoticeBoardEvent create
 */
export type NoticeBoardEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NoticeBoardEvent
   */
  select?: Prisma.NoticeBoardEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NoticeBoardEvent
   */
  omit?: Prisma.NoticeBoardEventOmit<ExtArgs> | null
  /**
   * The data needed to create a NoticeBoardEvent.
   */
  data: Prisma.XOR<Prisma.NoticeBoardEventCreateInput, Prisma.NoticeBoardEventUncheckedCreateInput>
}

/**
 * NoticeBoardEvent createMany
 */
export type NoticeBoardEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many NoticeBoardEvents.
   */
  data: Prisma.NoticeBoardEventCreateManyInput | Prisma.NoticeBoardEventCreateManyInput[]
}

/**
 * NoticeBoardEvent createManyAndReturn
 */
export type NoticeBoardEventCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NoticeBoardEvent
   */
  select?: Prisma.NoticeBoardEventSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NoticeBoardEvent
   */
  omit?: Prisma.NoticeBoardEventOmit<ExtArgs> | null
  /**
   * The data used to create many NoticeBoardEvents.
   */
  data: Prisma.NoticeBoardEventCreateManyInput | Prisma.NoticeBoardEventCreateManyInput[]
}

/**
 * NoticeBoardEvent update
 */
export type NoticeBoardEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NoticeBoardEvent
   */
  select?: Prisma.NoticeBoardEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NoticeBoardEvent
   */
  omit?: Prisma.NoticeBoardEventOmit<ExtArgs> | null
  /**
   * The data needed to update a NoticeBoardEvent.
   */
  data: Prisma.XOR<Prisma.NoticeBoardEventUpdateInput, Prisma.NoticeBoardEventUncheckedUpdateInput>
  /**
   * Choose, which NoticeBoardEvent to update.
   */
  where: Prisma.NoticeBoardEventWhereUniqueInput
}

/**
 * NoticeBoardEvent updateMany
 */
export type NoticeBoardEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update NoticeBoardEvents.
   */
  data: Prisma.XOR<Prisma.NoticeBoardEventUpdateManyMutationInput, Prisma.NoticeBoardEventUncheckedUpdateManyInput>
  /**
   * Filter which NoticeBoardEvents to update
   */
  where?: Prisma.NoticeBoardEventWhereInput
  /**
   * Limit how many NoticeBoardEvents to update.
   */
  limit?: number
}

/**
 * NoticeBoardEvent updateManyAndReturn
 */
export type NoticeBoardEventUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NoticeBoardEvent
   */
  select?: Prisma.NoticeBoardEventSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NoticeBoardEvent
   */
  omit?: Prisma.NoticeBoardEventOmit<ExtArgs> | null
  /**
   * The data used to update NoticeBoardEvents.
   */
  data: Prisma.XOR<Prisma.NoticeBoardEventUpdateManyMutationInput, Prisma.NoticeBoardEventUncheckedUpdateManyInput>
  /**
   * Filter which NoticeBoardEvents to update
   */
  where?: Prisma.NoticeBoardEventWhereInput
  /**
   * Limit how many NoticeBoardEvents to update.
   */
  limit?: number
}

/**
 * NoticeBoardEvent upsert
 */
export type NoticeBoardEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NoticeBoardEvent
   */
  select?: Prisma.NoticeBoardEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NoticeBoardEvent
   */
  omit?: Prisma.NoticeBoardEventOmit<ExtArgs> | null
  /**
   * The filter to search for the NoticeBoardEvent to update in case it exists.
   */
  where: Prisma.NoticeBoardEventWhereUniqueInput
  /**
   * In case the NoticeBoardEvent found by the `where` argument doesn't exist, create a new NoticeBoardEvent with this data.
   */
  create: Prisma.XOR<Prisma.NoticeBoardEventCreateInput, Prisma.NoticeBoardEventUncheckedCreateInput>
  /**
   * In case the NoticeBoardEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NoticeBoardEventUpdateInput, Prisma.NoticeBoardEventUncheckedUpdateInput>
}

/**
 * NoticeBoardEvent delete
 */
export type NoticeBoardEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NoticeBoardEvent
   */
  select?: Prisma.NoticeBoardEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NoticeBoardEvent
   */
  omit?: Prisma.NoticeBoardEventOmit<ExtArgs> | null
  /**
   * Filter which NoticeBoardEvent to delete.
   */
  where: Prisma.NoticeBoardEventWhereUniqueInput
}

/**
 * NoticeBoardEvent deleteMany
 */
export type NoticeBoardEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NoticeBoardEvents to delete
   */
  where?: Prisma.NoticeBoardEventWhereInput
  /**
   * Limit how many NoticeBoardEvents to delete.
   */
  limit?: number
}

/**
 * NoticeBoardEvent without action
 */
export type NoticeBoardEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NoticeBoardEvent
   */
  select?: Prisma.NoticeBoardEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NoticeBoardEvent
   */
  omit?: Prisma.NoticeBoardEventOmit<ExtArgs> | null
}
