
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `PopupViewSession` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PopupViewSession
 * 
 */
export type PopupViewSessionModel = runtime.Types.Result.DefaultSelection<Prisma.$PopupViewSessionPayload>

export type AggregatePopupViewSession = {
  _count: PopupViewSessionCountAggregateOutputType | null
  _min: PopupViewSessionMinAggregateOutputType | null
  _max: PopupViewSessionMaxAggregateOutputType | null
}

export type PopupViewSessionMinAggregateOutputType = {
  id: string | null
  popupId: string | null
  sessionId: string | null
  createdAt: Date | null
}

export type PopupViewSessionMaxAggregateOutputType = {
  id: string | null
  popupId: string | null
  sessionId: string | null
  createdAt: Date | null
}

export type PopupViewSessionCountAggregateOutputType = {
  id: number
  popupId: number
  sessionId: number
  createdAt: number
  _all: number
}


export type PopupViewSessionMinAggregateInputType = {
  id?: true
  popupId?: true
  sessionId?: true
  createdAt?: true
}

export type PopupViewSessionMaxAggregateInputType = {
  id?: true
  popupId?: true
  sessionId?: true
  createdAt?: true
}

export type PopupViewSessionCountAggregateInputType = {
  id?: true
  popupId?: true
  sessionId?: true
  createdAt?: true
  _all?: true
}

export type PopupViewSessionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PopupViewSession to aggregate.
   */
  where?: Prisma.PopupViewSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PopupViewSessions to fetch.
   */
  orderBy?: Prisma.PopupViewSessionOrderByWithRelationInput | Prisma.PopupViewSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PopupViewSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PopupViewSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PopupViewSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PopupViewSessions
  **/
  _count?: true | PopupViewSessionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PopupViewSessionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PopupViewSessionMaxAggregateInputType
}

export type GetPopupViewSessionAggregateType<T extends PopupViewSessionAggregateArgs> = {
      [P in keyof T & keyof AggregatePopupViewSession]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePopupViewSession[P]>
    : Prisma.GetScalarType<T[P], AggregatePopupViewSession[P]>
}




export type PopupViewSessionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PopupViewSessionWhereInput
  orderBy?: Prisma.PopupViewSessionOrderByWithAggregationInput | Prisma.PopupViewSessionOrderByWithAggregationInput[]
  by: Prisma.PopupViewSessionScalarFieldEnum[] | Prisma.PopupViewSessionScalarFieldEnum
  having?: Prisma.PopupViewSessionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PopupViewSessionCountAggregateInputType | true
  _min?: PopupViewSessionMinAggregateInputType
  _max?: PopupViewSessionMaxAggregateInputType
}

export type PopupViewSessionGroupByOutputType = {
  id: string
  popupId: string
  sessionId: string
  createdAt: Date
  _count: PopupViewSessionCountAggregateOutputType | null
  _min: PopupViewSessionMinAggregateOutputType | null
  _max: PopupViewSessionMaxAggregateOutputType | null
}

type GetPopupViewSessionGroupByPayload<T extends PopupViewSessionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PopupViewSessionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PopupViewSessionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PopupViewSessionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PopupViewSessionGroupByOutputType[P]>
      }
    >
  >



export type PopupViewSessionWhereInput = {
  AND?: Prisma.PopupViewSessionWhereInput | Prisma.PopupViewSessionWhereInput[]
  OR?: Prisma.PopupViewSessionWhereInput[]
  NOT?: Prisma.PopupViewSessionWhereInput | Prisma.PopupViewSessionWhereInput[]
  id?: Prisma.StringFilter<"PopupViewSession"> | string
  popupId?: Prisma.StringFilter<"PopupViewSession"> | string
  sessionId?: Prisma.StringFilter<"PopupViewSession"> | string
  createdAt?: Prisma.DateTimeFilter<"PopupViewSession"> | Date | string
  popup?: Prisma.XOR<Prisma.PopupBannerScalarRelationFilter, Prisma.PopupBannerWhereInput>
}

export type PopupViewSessionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  popupId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  popup?: Prisma.PopupBannerOrderByWithRelationInput
}

export type PopupViewSessionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  popupId_sessionId?: Prisma.PopupViewSessionPopupIdSessionIdCompoundUniqueInput
  AND?: Prisma.PopupViewSessionWhereInput | Prisma.PopupViewSessionWhereInput[]
  OR?: Prisma.PopupViewSessionWhereInput[]
  NOT?: Prisma.PopupViewSessionWhereInput | Prisma.PopupViewSessionWhereInput[]
  popupId?: Prisma.StringFilter<"PopupViewSession"> | string
  sessionId?: Prisma.StringFilter<"PopupViewSession"> | string
  createdAt?: Prisma.DateTimeFilter<"PopupViewSession"> | Date | string
  popup?: Prisma.XOR<Prisma.PopupBannerScalarRelationFilter, Prisma.PopupBannerWhereInput>
}, "id" | "popupId_sessionId">

export type PopupViewSessionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  popupId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.PopupViewSessionCountOrderByAggregateInput
  _max?: Prisma.PopupViewSessionMaxOrderByAggregateInput
  _min?: Prisma.PopupViewSessionMinOrderByAggregateInput
}

export type PopupViewSessionScalarWhereWithAggregatesInput = {
  AND?: Prisma.PopupViewSessionScalarWhereWithAggregatesInput | Prisma.PopupViewSessionScalarWhereWithAggregatesInput[]
  OR?: Prisma.PopupViewSessionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PopupViewSessionScalarWhereWithAggregatesInput | Prisma.PopupViewSessionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PopupViewSession"> | string
  popupId?: Prisma.StringWithAggregatesFilter<"PopupViewSession"> | string
  sessionId?: Prisma.StringWithAggregatesFilter<"PopupViewSession"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PopupViewSession"> | Date | string
}

export type PopupViewSessionCreateInput = {
  id?: string
  sessionId: string
  createdAt?: Date | string
  popup: Prisma.PopupBannerCreateNestedOneWithoutViewSessionsInput
}

export type PopupViewSessionUncheckedCreateInput = {
  id?: string
  popupId: string
  sessionId: string
  createdAt?: Date | string
}

export type PopupViewSessionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  popup?: Prisma.PopupBannerUpdateOneRequiredWithoutViewSessionsNestedInput
}

export type PopupViewSessionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  popupId?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PopupViewSessionCreateManyInput = {
  id?: string
  popupId: string
  sessionId: string
  createdAt?: Date | string
}

export type PopupViewSessionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PopupViewSessionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  popupId?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PopupViewSessionListRelationFilter = {
  every?: Prisma.PopupViewSessionWhereInput
  some?: Prisma.PopupViewSessionWhereInput
  none?: Prisma.PopupViewSessionWhereInput
}

export type PopupViewSessionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PopupViewSessionPopupIdSessionIdCompoundUniqueInput = {
  popupId: string
  sessionId: string
}

export type PopupViewSessionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  popupId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PopupViewSessionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  popupId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PopupViewSessionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  popupId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PopupViewSessionCreateNestedManyWithoutPopupInput = {
  create?: Prisma.XOR<Prisma.PopupViewSessionCreateWithoutPopupInput, Prisma.PopupViewSessionUncheckedCreateWithoutPopupInput> | Prisma.PopupViewSessionCreateWithoutPopupInput[] | Prisma.PopupViewSessionUncheckedCreateWithoutPopupInput[]
  connectOrCreate?: Prisma.PopupViewSessionCreateOrConnectWithoutPopupInput | Prisma.PopupViewSessionCreateOrConnectWithoutPopupInput[]
  createMany?: Prisma.PopupViewSessionCreateManyPopupInputEnvelope
  connect?: Prisma.PopupViewSessionWhereUniqueInput | Prisma.PopupViewSessionWhereUniqueInput[]
}

export type PopupViewSessionUncheckedCreateNestedManyWithoutPopupInput = {
  create?: Prisma.XOR<Prisma.PopupViewSessionCreateWithoutPopupInput, Prisma.PopupViewSessionUncheckedCreateWithoutPopupInput> | Prisma.PopupViewSessionCreateWithoutPopupInput[] | Prisma.PopupViewSessionUncheckedCreateWithoutPopupInput[]
  connectOrCreate?: Prisma.PopupViewSessionCreateOrConnectWithoutPopupInput | Prisma.PopupViewSessionCreateOrConnectWithoutPopupInput[]
  createMany?: Prisma.PopupViewSessionCreateManyPopupInputEnvelope
  connect?: Prisma.PopupViewSessionWhereUniqueInput | Prisma.PopupViewSessionWhereUniqueInput[]
}

export type PopupViewSessionUpdateManyWithoutPopupNestedInput = {
  create?: Prisma.XOR<Prisma.PopupViewSessionCreateWithoutPopupInput, Prisma.PopupViewSessionUncheckedCreateWithoutPopupInput> | Prisma.PopupViewSessionCreateWithoutPopupInput[] | Prisma.PopupViewSessionUncheckedCreateWithoutPopupInput[]
  connectOrCreate?: Prisma.PopupViewSessionCreateOrConnectWithoutPopupInput | Prisma.PopupViewSessionCreateOrConnectWithoutPopupInput[]
  upsert?: Prisma.PopupViewSessionUpsertWithWhereUniqueWithoutPopupInput | Prisma.PopupViewSessionUpsertWithWhereUniqueWithoutPopupInput[]
  createMany?: Prisma.PopupViewSessionCreateManyPopupInputEnvelope
  set?: Prisma.PopupViewSessionWhereUniqueInput | Prisma.PopupViewSessionWhereUniqueInput[]
  disconnect?: Prisma.PopupViewSessionWhereUniqueInput | Prisma.PopupViewSessionWhereUniqueInput[]
  delete?: Prisma.PopupViewSessionWhereUniqueInput | Prisma.PopupViewSessionWhereUniqueInput[]
  connect?: Prisma.PopupViewSessionWhereUniqueInput | Prisma.PopupViewSessionWhereUniqueInput[]
  update?: Prisma.PopupViewSessionUpdateWithWhereUniqueWithoutPopupInput | Prisma.PopupViewSessionUpdateWithWhereUniqueWithoutPopupInput[]
  updateMany?: Prisma.PopupViewSessionUpdateManyWithWhereWithoutPopupInput | Prisma.PopupViewSessionUpdateManyWithWhereWithoutPopupInput[]
  deleteMany?: Prisma.PopupViewSessionScalarWhereInput | Prisma.PopupViewSessionScalarWhereInput[]
}

export type PopupViewSessionUncheckedUpdateManyWithoutPopupNestedInput = {
  create?: Prisma.XOR<Prisma.PopupViewSessionCreateWithoutPopupInput, Prisma.PopupViewSessionUncheckedCreateWithoutPopupInput> | Prisma.PopupViewSessionCreateWithoutPopupInput[] | Prisma.PopupViewSessionUncheckedCreateWithoutPopupInput[]
  connectOrCreate?: Prisma.PopupViewSessionCreateOrConnectWithoutPopupInput | Prisma.PopupViewSessionCreateOrConnectWithoutPopupInput[]
  upsert?: Prisma.PopupViewSessionUpsertWithWhereUniqueWithoutPopupInput | Prisma.PopupViewSessionUpsertWithWhereUniqueWithoutPopupInput[]
  createMany?: Prisma.PopupViewSessionCreateManyPopupInputEnvelope
  set?: Prisma.PopupViewSessionWhereUniqueInput | Prisma.PopupViewSessionWhereUniqueInput[]
  disconnect?: Prisma.PopupViewSessionWhereUniqueInput | Prisma.PopupViewSessionWhereUniqueInput[]
  delete?: Prisma.PopupViewSessionWhereUniqueInput | Prisma.PopupViewSessionWhereUniqueInput[]
  connect?: Prisma.PopupViewSessionWhereUniqueInput | Prisma.PopupViewSessionWhereUniqueInput[]
  update?: Prisma.PopupViewSessionUpdateWithWhereUniqueWithoutPopupInput | Prisma.PopupViewSessionUpdateWithWhereUniqueWithoutPopupInput[]
  updateMany?: Prisma.PopupViewSessionUpdateManyWithWhereWithoutPopupInput | Prisma.PopupViewSessionUpdateManyWithWhereWithoutPopupInput[]
  deleteMany?: Prisma.PopupViewSessionScalarWhereInput | Prisma.PopupViewSessionScalarWhereInput[]
}

export type PopupViewSessionCreateWithoutPopupInput = {
  id?: string
  sessionId: string
  createdAt?: Date | string
}

export type PopupViewSessionUncheckedCreateWithoutPopupInput = {
  id?: string
  sessionId: string
  createdAt?: Date | string
}

export type PopupViewSessionCreateOrConnectWithoutPopupInput = {
  where: Prisma.PopupViewSessionWhereUniqueInput
  create: Prisma.XOR<Prisma.PopupViewSessionCreateWithoutPopupInput, Prisma.PopupViewSessionUncheckedCreateWithoutPopupInput>
}

export type PopupViewSessionCreateManyPopupInputEnvelope = {
  data: Prisma.PopupViewSessionCreateManyPopupInput | Prisma.PopupViewSessionCreateManyPopupInput[]
}

export type PopupViewSessionUpsertWithWhereUniqueWithoutPopupInput = {
  where: Prisma.PopupViewSessionWhereUniqueInput
  update: Prisma.XOR<Prisma.PopupViewSessionUpdateWithoutPopupInput, Prisma.PopupViewSessionUncheckedUpdateWithoutPopupInput>
  create: Prisma.XOR<Prisma.PopupViewSessionCreateWithoutPopupInput, Prisma.PopupViewSessionUncheckedCreateWithoutPopupInput>
}

export type PopupViewSessionUpdateWithWhereUniqueWithoutPopupInput = {
  where: Prisma.PopupViewSessionWhereUniqueInput
  data: Prisma.XOR<Prisma.PopupViewSessionUpdateWithoutPopupInput, Prisma.PopupViewSessionUncheckedUpdateWithoutPopupInput>
}

export type PopupViewSessionUpdateManyWithWhereWithoutPopupInput = {
  where: Prisma.PopupViewSessionScalarWhereInput
  data: Prisma.XOR<Prisma.PopupViewSessionUpdateManyMutationInput, Prisma.PopupViewSessionUncheckedUpdateManyWithoutPopupInput>
}

export type PopupViewSessionScalarWhereInput = {
  AND?: Prisma.PopupViewSessionScalarWhereInput | Prisma.PopupViewSessionScalarWhereInput[]
  OR?: Prisma.PopupViewSessionScalarWhereInput[]
  NOT?: Prisma.PopupViewSessionScalarWhereInput | Prisma.PopupViewSessionScalarWhereInput[]
  id?: Prisma.StringFilter<"PopupViewSession"> | string
  popupId?: Prisma.StringFilter<"PopupViewSession"> | string
  sessionId?: Prisma.StringFilter<"PopupViewSession"> | string
  createdAt?: Prisma.DateTimeFilter<"PopupViewSession"> | Date | string
}

export type PopupViewSessionCreateManyPopupInput = {
  id?: string
  sessionId: string
  createdAt?: Date | string
}

export type PopupViewSessionUpdateWithoutPopupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PopupViewSessionUncheckedUpdateWithoutPopupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PopupViewSessionUncheckedUpdateManyWithoutPopupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PopupViewSessionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  popupId?: boolean
  sessionId?: boolean
  createdAt?: boolean
  popup?: boolean | Prisma.PopupBannerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["popupViewSession"]>

export type PopupViewSessionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  popupId?: boolean
  sessionId?: boolean
  createdAt?: boolean
  popup?: boolean | Prisma.PopupBannerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["popupViewSession"]>

export type PopupViewSessionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  popupId?: boolean
  sessionId?: boolean
  createdAt?: boolean
  popup?: boolean | Prisma.PopupBannerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["popupViewSession"]>

export type PopupViewSessionSelectScalar = {
  id?: boolean
  popupId?: boolean
  sessionId?: boolean
  createdAt?: boolean
}

export type PopupViewSessionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "popupId" | "sessionId" | "createdAt", ExtArgs["result"]["popupViewSession"]>
export type PopupViewSessionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  popup?: boolean | Prisma.PopupBannerDefaultArgs<ExtArgs>
}
export type PopupViewSessionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  popup?: boolean | Prisma.PopupBannerDefaultArgs<ExtArgs>
}
export type PopupViewSessionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  popup?: boolean | Prisma.PopupBannerDefaultArgs<ExtArgs>
}

export type $PopupViewSessionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PopupViewSession"
  objects: {
    popup: Prisma.$PopupBannerPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    popupId: string
    sessionId: string
    createdAt: Date
  }, ExtArgs["result"]["popupViewSession"]>
  composites: {}
}

export type PopupViewSessionGetPayload<S extends boolean | null | undefined | PopupViewSessionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PopupViewSessionPayload, S>

export type PopupViewSessionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PopupViewSessionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PopupViewSessionCountAggregateInputType | true
  }

export interface PopupViewSessionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PopupViewSession'], meta: { name: 'PopupViewSession' } }
  /**
   * Find zero or one PopupViewSession that matches the filter.
   * @param {PopupViewSessionFindUniqueArgs} args - Arguments to find a PopupViewSession
   * @example
   * // Get one PopupViewSession
   * const popupViewSession = await prisma.popupViewSession.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PopupViewSessionFindUniqueArgs>(args: Prisma.SelectSubset<T, PopupViewSessionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PopupViewSessionClient<runtime.Types.Result.GetResult<Prisma.$PopupViewSessionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PopupViewSession that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PopupViewSessionFindUniqueOrThrowArgs} args - Arguments to find a PopupViewSession
   * @example
   * // Get one PopupViewSession
   * const popupViewSession = await prisma.popupViewSession.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PopupViewSessionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PopupViewSessionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PopupViewSessionClient<runtime.Types.Result.GetResult<Prisma.$PopupViewSessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PopupViewSession that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PopupViewSessionFindFirstArgs} args - Arguments to find a PopupViewSession
   * @example
   * // Get one PopupViewSession
   * const popupViewSession = await prisma.popupViewSession.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PopupViewSessionFindFirstArgs>(args?: Prisma.SelectSubset<T, PopupViewSessionFindFirstArgs<ExtArgs>>): Prisma.Prisma__PopupViewSessionClient<runtime.Types.Result.GetResult<Prisma.$PopupViewSessionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PopupViewSession that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PopupViewSessionFindFirstOrThrowArgs} args - Arguments to find a PopupViewSession
   * @example
   * // Get one PopupViewSession
   * const popupViewSession = await prisma.popupViewSession.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PopupViewSessionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PopupViewSessionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PopupViewSessionClient<runtime.Types.Result.GetResult<Prisma.$PopupViewSessionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PopupViewSessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PopupViewSessionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PopupViewSessions
   * const popupViewSessions = await prisma.popupViewSession.findMany()
   * 
   * // Get first 10 PopupViewSessions
   * const popupViewSessions = await prisma.popupViewSession.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const popupViewSessionWithIdOnly = await prisma.popupViewSession.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PopupViewSessionFindManyArgs>(args?: Prisma.SelectSubset<T, PopupViewSessionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PopupViewSessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PopupViewSession.
   * @param {PopupViewSessionCreateArgs} args - Arguments to create a PopupViewSession.
   * @example
   * // Create one PopupViewSession
   * const PopupViewSession = await prisma.popupViewSession.create({
   *   data: {
   *     // ... data to create a PopupViewSession
   *   }
   * })
   * 
   */
  create<T extends PopupViewSessionCreateArgs>(args: Prisma.SelectSubset<T, PopupViewSessionCreateArgs<ExtArgs>>): Prisma.Prisma__PopupViewSessionClient<runtime.Types.Result.GetResult<Prisma.$PopupViewSessionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PopupViewSessions.
   * @param {PopupViewSessionCreateManyArgs} args - Arguments to create many PopupViewSessions.
   * @example
   * // Create many PopupViewSessions
   * const popupViewSession = await prisma.popupViewSession.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PopupViewSessionCreateManyArgs>(args?: Prisma.SelectSubset<T, PopupViewSessionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PopupViewSessions and returns the data saved in the database.
   * @param {PopupViewSessionCreateManyAndReturnArgs} args - Arguments to create many PopupViewSessions.
   * @example
   * // Create many PopupViewSessions
   * const popupViewSession = await prisma.popupViewSession.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PopupViewSessions and only return the `id`
   * const popupViewSessionWithIdOnly = await prisma.popupViewSession.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PopupViewSessionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PopupViewSessionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PopupViewSessionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PopupViewSession.
   * @param {PopupViewSessionDeleteArgs} args - Arguments to delete one PopupViewSession.
   * @example
   * // Delete one PopupViewSession
   * const PopupViewSession = await prisma.popupViewSession.delete({
   *   where: {
   *     // ... filter to delete one PopupViewSession
   *   }
   * })
   * 
   */
  delete<T extends PopupViewSessionDeleteArgs>(args: Prisma.SelectSubset<T, PopupViewSessionDeleteArgs<ExtArgs>>): Prisma.Prisma__PopupViewSessionClient<runtime.Types.Result.GetResult<Prisma.$PopupViewSessionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PopupViewSession.
   * @param {PopupViewSessionUpdateArgs} args - Arguments to update one PopupViewSession.
   * @example
   * // Update one PopupViewSession
   * const popupViewSession = await prisma.popupViewSession.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PopupViewSessionUpdateArgs>(args: Prisma.SelectSubset<T, PopupViewSessionUpdateArgs<ExtArgs>>): Prisma.Prisma__PopupViewSessionClient<runtime.Types.Result.GetResult<Prisma.$PopupViewSessionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PopupViewSessions.
   * @param {PopupViewSessionDeleteManyArgs} args - Arguments to filter PopupViewSessions to delete.
   * @example
   * // Delete a few PopupViewSessions
   * const { count } = await prisma.popupViewSession.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PopupViewSessionDeleteManyArgs>(args?: Prisma.SelectSubset<T, PopupViewSessionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PopupViewSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PopupViewSessionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PopupViewSessions
   * const popupViewSession = await prisma.popupViewSession.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PopupViewSessionUpdateManyArgs>(args: Prisma.SelectSubset<T, PopupViewSessionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PopupViewSessions and returns the data updated in the database.
   * @param {PopupViewSessionUpdateManyAndReturnArgs} args - Arguments to update many PopupViewSessions.
   * @example
   * // Update many PopupViewSessions
   * const popupViewSession = await prisma.popupViewSession.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PopupViewSessions and only return the `id`
   * const popupViewSessionWithIdOnly = await prisma.popupViewSession.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PopupViewSessionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PopupViewSessionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PopupViewSessionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PopupViewSession.
   * @param {PopupViewSessionUpsertArgs} args - Arguments to update or create a PopupViewSession.
   * @example
   * // Update or create a PopupViewSession
   * const popupViewSession = await prisma.popupViewSession.upsert({
   *   create: {
   *     // ... data to create a PopupViewSession
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PopupViewSession we want to update
   *   }
   * })
   */
  upsert<T extends PopupViewSessionUpsertArgs>(args: Prisma.SelectSubset<T, PopupViewSessionUpsertArgs<ExtArgs>>): Prisma.Prisma__PopupViewSessionClient<runtime.Types.Result.GetResult<Prisma.$PopupViewSessionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PopupViewSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PopupViewSessionCountArgs} args - Arguments to filter PopupViewSessions to count.
   * @example
   * // Count the number of PopupViewSessions
   * const count = await prisma.popupViewSession.count({
   *   where: {
   *     // ... the filter for the PopupViewSessions we want to count
   *   }
   * })
  **/
  count<T extends PopupViewSessionCountArgs>(
    args?: Prisma.Subset<T, PopupViewSessionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PopupViewSessionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PopupViewSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PopupViewSessionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PopupViewSessionAggregateArgs>(args: Prisma.Subset<T, PopupViewSessionAggregateArgs>): Prisma.PrismaPromise<GetPopupViewSessionAggregateType<T>>

  /**
   * Group by PopupViewSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PopupViewSessionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PopupViewSessionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PopupViewSessionGroupByArgs['orderBy'] }
      : { orderBy?: PopupViewSessionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PopupViewSessionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPopupViewSessionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PopupViewSession model
 */
readonly fields: PopupViewSessionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PopupViewSession.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PopupViewSessionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  popup<T extends Prisma.PopupBannerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PopupBannerDefaultArgs<ExtArgs>>): Prisma.Prisma__PopupBannerClient<runtime.Types.Result.GetResult<Prisma.$PopupBannerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PopupViewSession model
 */
export interface PopupViewSessionFieldRefs {
  readonly id: Prisma.FieldRef<"PopupViewSession", 'String'>
  readonly popupId: Prisma.FieldRef<"PopupViewSession", 'String'>
  readonly sessionId: Prisma.FieldRef<"PopupViewSession", 'String'>
  readonly createdAt: Prisma.FieldRef<"PopupViewSession", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PopupViewSession findUnique
 */
export type PopupViewSessionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupViewSession
   */
  select?: Prisma.PopupViewSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupViewSession
   */
  omit?: Prisma.PopupViewSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PopupViewSessionInclude<ExtArgs> | null
  /**
   * Filter, which PopupViewSession to fetch.
   */
  where: Prisma.PopupViewSessionWhereUniqueInput
}

/**
 * PopupViewSession findUniqueOrThrow
 */
export type PopupViewSessionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupViewSession
   */
  select?: Prisma.PopupViewSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupViewSession
   */
  omit?: Prisma.PopupViewSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PopupViewSessionInclude<ExtArgs> | null
  /**
   * Filter, which PopupViewSession to fetch.
   */
  where: Prisma.PopupViewSessionWhereUniqueInput
}

/**
 * PopupViewSession findFirst
 */
export type PopupViewSessionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupViewSession
   */
  select?: Prisma.PopupViewSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupViewSession
   */
  omit?: Prisma.PopupViewSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PopupViewSessionInclude<ExtArgs> | null
  /**
   * Filter, which PopupViewSession to fetch.
   */
  where?: Prisma.PopupViewSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PopupViewSessions to fetch.
   */
  orderBy?: Prisma.PopupViewSessionOrderByWithRelationInput | Prisma.PopupViewSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PopupViewSessions.
   */
  cursor?: Prisma.PopupViewSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PopupViewSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PopupViewSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PopupViewSessions.
   */
  distinct?: Prisma.PopupViewSessionScalarFieldEnum | Prisma.PopupViewSessionScalarFieldEnum[]
}

/**
 * PopupViewSession findFirstOrThrow
 */
export type PopupViewSessionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupViewSession
   */
  select?: Prisma.PopupViewSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupViewSession
   */
  omit?: Prisma.PopupViewSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PopupViewSessionInclude<ExtArgs> | null
  /**
   * Filter, which PopupViewSession to fetch.
   */
  where?: Prisma.PopupViewSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PopupViewSessions to fetch.
   */
  orderBy?: Prisma.PopupViewSessionOrderByWithRelationInput | Prisma.PopupViewSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PopupViewSessions.
   */
  cursor?: Prisma.PopupViewSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PopupViewSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PopupViewSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PopupViewSessions.
   */
  distinct?: Prisma.PopupViewSessionScalarFieldEnum | Prisma.PopupViewSessionScalarFieldEnum[]
}

/**
 * PopupViewSession findMany
 */
export type PopupViewSessionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupViewSession
   */
  select?: Prisma.PopupViewSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupViewSession
   */
  omit?: Prisma.PopupViewSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PopupViewSessionInclude<ExtArgs> | null
  /**
   * Filter, which PopupViewSessions to fetch.
   */
  where?: Prisma.PopupViewSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PopupViewSessions to fetch.
   */
  orderBy?: Prisma.PopupViewSessionOrderByWithRelationInput | Prisma.PopupViewSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PopupViewSessions.
   */
  cursor?: Prisma.PopupViewSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PopupViewSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PopupViewSessions.
   */
  skip?: number
  distinct?: Prisma.PopupViewSessionScalarFieldEnum | Prisma.PopupViewSessionScalarFieldEnum[]
}

/**
 * PopupViewSession create
 */
export type PopupViewSessionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupViewSession
   */
  select?: Prisma.PopupViewSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupViewSession
   */
  omit?: Prisma.PopupViewSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PopupViewSessionInclude<ExtArgs> | null
  /**
   * The data needed to create a PopupViewSession.
   */
  data: Prisma.XOR<Prisma.PopupViewSessionCreateInput, Prisma.PopupViewSessionUncheckedCreateInput>
}

/**
 * PopupViewSession createMany
 */
export type PopupViewSessionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PopupViewSessions.
   */
  data: Prisma.PopupViewSessionCreateManyInput | Prisma.PopupViewSessionCreateManyInput[]
}

/**
 * PopupViewSession createManyAndReturn
 */
export type PopupViewSessionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupViewSession
   */
  select?: Prisma.PopupViewSessionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PopupViewSession
   */
  omit?: Prisma.PopupViewSessionOmit<ExtArgs> | null
  /**
   * The data used to create many PopupViewSessions.
   */
  data: Prisma.PopupViewSessionCreateManyInput | Prisma.PopupViewSessionCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PopupViewSessionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PopupViewSession update
 */
export type PopupViewSessionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupViewSession
   */
  select?: Prisma.PopupViewSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupViewSession
   */
  omit?: Prisma.PopupViewSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PopupViewSessionInclude<ExtArgs> | null
  /**
   * The data needed to update a PopupViewSession.
   */
  data: Prisma.XOR<Prisma.PopupViewSessionUpdateInput, Prisma.PopupViewSessionUncheckedUpdateInput>
  /**
   * Choose, which PopupViewSession to update.
   */
  where: Prisma.PopupViewSessionWhereUniqueInput
}

/**
 * PopupViewSession updateMany
 */
export type PopupViewSessionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PopupViewSessions.
   */
  data: Prisma.XOR<Prisma.PopupViewSessionUpdateManyMutationInput, Prisma.PopupViewSessionUncheckedUpdateManyInput>
  /**
   * Filter which PopupViewSessions to update
   */
  where?: Prisma.PopupViewSessionWhereInput
  /**
   * Limit how many PopupViewSessions to update.
   */
  limit?: number
}

/**
 * PopupViewSession updateManyAndReturn
 */
export type PopupViewSessionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupViewSession
   */
  select?: Prisma.PopupViewSessionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PopupViewSession
   */
  omit?: Prisma.PopupViewSessionOmit<ExtArgs> | null
  /**
   * The data used to update PopupViewSessions.
   */
  data: Prisma.XOR<Prisma.PopupViewSessionUpdateManyMutationInput, Prisma.PopupViewSessionUncheckedUpdateManyInput>
  /**
   * Filter which PopupViewSessions to update
   */
  where?: Prisma.PopupViewSessionWhereInput
  /**
   * Limit how many PopupViewSessions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PopupViewSessionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PopupViewSession upsert
 */
export type PopupViewSessionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupViewSession
   */
  select?: Prisma.PopupViewSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupViewSession
   */
  omit?: Prisma.PopupViewSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PopupViewSessionInclude<ExtArgs> | null
  /**
   * The filter to search for the PopupViewSession to update in case it exists.
   */
  where: Prisma.PopupViewSessionWhereUniqueInput
  /**
   * In case the PopupViewSession found by the `where` argument doesn't exist, create a new PopupViewSession with this data.
   */
  create: Prisma.XOR<Prisma.PopupViewSessionCreateInput, Prisma.PopupViewSessionUncheckedCreateInput>
  /**
   * In case the PopupViewSession was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PopupViewSessionUpdateInput, Prisma.PopupViewSessionUncheckedUpdateInput>
}

/**
 * PopupViewSession delete
 */
export type PopupViewSessionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupViewSession
   */
  select?: Prisma.PopupViewSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupViewSession
   */
  omit?: Prisma.PopupViewSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PopupViewSessionInclude<ExtArgs> | null
  /**
   * Filter which PopupViewSession to delete.
   */
  where: Prisma.PopupViewSessionWhereUniqueInput
}

/**
 * PopupViewSession deleteMany
 */
export type PopupViewSessionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PopupViewSessions to delete
   */
  where?: Prisma.PopupViewSessionWhereInput
  /**
   * Limit how many PopupViewSessions to delete.
   */
  limit?: number
}

/**
 * PopupViewSession without action
 */
export type PopupViewSessionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupViewSession
   */
  select?: Prisma.PopupViewSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupViewSession
   */
  omit?: Prisma.PopupViewSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PopupViewSessionInclude<ExtArgs> | null
}
