
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `PopupBanner` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PopupBanner
 * 
 */
export type PopupBannerModel = runtime.Types.Result.DefaultSelection<Prisma.$PopupBannerPayload>

export type AggregatePopupBanner = {
  _count: PopupBannerCountAggregateOutputType | null
  _min: PopupBannerMinAggregateOutputType | null
  _max: PopupBannerMaxAggregateOutputType | null
}

export type PopupBannerMinAggregateOutputType = {
  id: string | null
  title: string | null
  content: string | null
  enabled: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PopupBannerMaxAggregateOutputType = {
  id: string | null
  title: string | null
  content: string | null
  enabled: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PopupBannerCountAggregateOutputType = {
  id: number
  title: number
  content: number
  enabled: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PopupBannerMinAggregateInputType = {
  id?: true
  title?: true
  content?: true
  enabled?: true
  createdAt?: true
  updatedAt?: true
}

export type PopupBannerMaxAggregateInputType = {
  id?: true
  title?: true
  content?: true
  enabled?: true
  createdAt?: true
  updatedAt?: true
}

export type PopupBannerCountAggregateInputType = {
  id?: true
  title?: true
  content?: true
  enabled?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PopupBannerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PopupBanner to aggregate.
   */
  where?: Prisma.PopupBannerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PopupBanners to fetch.
   */
  orderBy?: Prisma.PopupBannerOrderByWithRelationInput | Prisma.PopupBannerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PopupBannerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PopupBanners from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PopupBanners.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PopupBanners
  **/
  _count?: true | PopupBannerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PopupBannerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PopupBannerMaxAggregateInputType
}

export type GetPopupBannerAggregateType<T extends PopupBannerAggregateArgs> = {
      [P in keyof T & keyof AggregatePopupBanner]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePopupBanner[P]>
    : Prisma.GetScalarType<T[P], AggregatePopupBanner[P]>
}




export type PopupBannerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PopupBannerWhereInput
  orderBy?: Prisma.PopupBannerOrderByWithAggregationInput | Prisma.PopupBannerOrderByWithAggregationInput[]
  by: Prisma.PopupBannerScalarFieldEnum[] | Prisma.PopupBannerScalarFieldEnum
  having?: Prisma.PopupBannerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PopupBannerCountAggregateInputType | true
  _min?: PopupBannerMinAggregateInputType
  _max?: PopupBannerMaxAggregateInputType
}

export type PopupBannerGroupByOutputType = {
  id: string
  title: string
  content: string
  enabled: boolean
  createdAt: Date
  updatedAt: Date
  _count: PopupBannerCountAggregateOutputType | null
  _min: PopupBannerMinAggregateOutputType | null
  _max: PopupBannerMaxAggregateOutputType | null
}

type GetPopupBannerGroupByPayload<T extends PopupBannerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PopupBannerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PopupBannerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PopupBannerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PopupBannerGroupByOutputType[P]>
      }
    >
  >



export type PopupBannerWhereInput = {
  AND?: Prisma.PopupBannerWhereInput | Prisma.PopupBannerWhereInput[]
  OR?: Prisma.PopupBannerWhereInput[]
  NOT?: Prisma.PopupBannerWhereInput | Prisma.PopupBannerWhereInput[]
  id?: Prisma.StringFilter<"PopupBanner"> | string
  title?: Prisma.StringFilter<"PopupBanner"> | string
  content?: Prisma.StringFilter<"PopupBanner"> | string
  enabled?: Prisma.BoolFilter<"PopupBanner"> | boolean
  createdAt?: Prisma.DateTimeFilter<"PopupBanner"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PopupBanner"> | Date | string
}

export type PopupBannerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PopupBannerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PopupBannerWhereInput | Prisma.PopupBannerWhereInput[]
  OR?: Prisma.PopupBannerWhereInput[]
  NOT?: Prisma.PopupBannerWhereInput | Prisma.PopupBannerWhereInput[]
  title?: Prisma.StringFilter<"PopupBanner"> | string
  content?: Prisma.StringFilter<"PopupBanner"> | string
  enabled?: Prisma.BoolFilter<"PopupBanner"> | boolean
  createdAt?: Prisma.DateTimeFilter<"PopupBanner"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PopupBanner"> | Date | string
}, "id">

export type PopupBannerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PopupBannerCountOrderByAggregateInput
  _max?: Prisma.PopupBannerMaxOrderByAggregateInput
  _min?: Prisma.PopupBannerMinOrderByAggregateInput
}

export type PopupBannerScalarWhereWithAggregatesInput = {
  AND?: Prisma.PopupBannerScalarWhereWithAggregatesInput | Prisma.PopupBannerScalarWhereWithAggregatesInput[]
  OR?: Prisma.PopupBannerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PopupBannerScalarWhereWithAggregatesInput | Prisma.PopupBannerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PopupBanner"> | string
  title?: Prisma.StringWithAggregatesFilter<"PopupBanner"> | string
  content?: Prisma.StringWithAggregatesFilter<"PopupBanner"> | string
  enabled?: Prisma.BoolWithAggregatesFilter<"PopupBanner"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PopupBanner"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PopupBanner"> | Date | string
}

export type PopupBannerCreateInput = {
  id?: string
  title: string
  content: string
  enabled?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PopupBannerUncheckedCreateInput = {
  id?: string
  title: string
  content: string
  enabled?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PopupBannerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PopupBannerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PopupBannerCreateManyInput = {
  id?: string
  title: string
  content: string
  enabled?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PopupBannerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PopupBannerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PopupBannerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PopupBannerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PopupBannerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type PopupBannerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  enabled?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["popupBanner"]>

export type PopupBannerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  enabled?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["popupBanner"]>

export type PopupBannerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  enabled?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["popupBanner"]>

export type PopupBannerSelectScalar = {
  id?: boolean
  title?: boolean
  content?: boolean
  enabled?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PopupBannerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "content" | "enabled" | "createdAt" | "updatedAt", ExtArgs["result"]["popupBanner"]>

export type $PopupBannerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PopupBanner"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    content: string
    enabled: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["popupBanner"]>
  composites: {}
}

export type PopupBannerGetPayload<S extends boolean | null | undefined | PopupBannerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PopupBannerPayload, S>

export type PopupBannerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PopupBannerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PopupBannerCountAggregateInputType | true
  }

export interface PopupBannerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PopupBanner'], meta: { name: 'PopupBanner' } }
  /**
   * Find zero or one PopupBanner that matches the filter.
   * @param {PopupBannerFindUniqueArgs} args - Arguments to find a PopupBanner
   * @example
   * // Get one PopupBanner
   * const popupBanner = await prisma.popupBanner.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PopupBannerFindUniqueArgs>(args: Prisma.SelectSubset<T, PopupBannerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PopupBannerClient<runtime.Types.Result.GetResult<Prisma.$PopupBannerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PopupBanner that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PopupBannerFindUniqueOrThrowArgs} args - Arguments to find a PopupBanner
   * @example
   * // Get one PopupBanner
   * const popupBanner = await prisma.popupBanner.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PopupBannerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PopupBannerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PopupBannerClient<runtime.Types.Result.GetResult<Prisma.$PopupBannerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PopupBanner that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PopupBannerFindFirstArgs} args - Arguments to find a PopupBanner
   * @example
   * // Get one PopupBanner
   * const popupBanner = await prisma.popupBanner.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PopupBannerFindFirstArgs>(args?: Prisma.SelectSubset<T, PopupBannerFindFirstArgs<ExtArgs>>): Prisma.Prisma__PopupBannerClient<runtime.Types.Result.GetResult<Prisma.$PopupBannerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PopupBanner that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PopupBannerFindFirstOrThrowArgs} args - Arguments to find a PopupBanner
   * @example
   * // Get one PopupBanner
   * const popupBanner = await prisma.popupBanner.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PopupBannerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PopupBannerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PopupBannerClient<runtime.Types.Result.GetResult<Prisma.$PopupBannerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PopupBanners that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PopupBannerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PopupBanners
   * const popupBanners = await prisma.popupBanner.findMany()
   * 
   * // Get first 10 PopupBanners
   * const popupBanners = await prisma.popupBanner.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const popupBannerWithIdOnly = await prisma.popupBanner.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PopupBannerFindManyArgs>(args?: Prisma.SelectSubset<T, PopupBannerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PopupBannerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PopupBanner.
   * @param {PopupBannerCreateArgs} args - Arguments to create a PopupBanner.
   * @example
   * // Create one PopupBanner
   * const PopupBanner = await prisma.popupBanner.create({
   *   data: {
   *     // ... data to create a PopupBanner
   *   }
   * })
   * 
   */
  create<T extends PopupBannerCreateArgs>(args: Prisma.SelectSubset<T, PopupBannerCreateArgs<ExtArgs>>): Prisma.Prisma__PopupBannerClient<runtime.Types.Result.GetResult<Prisma.$PopupBannerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PopupBanners.
   * @param {PopupBannerCreateManyArgs} args - Arguments to create many PopupBanners.
   * @example
   * // Create many PopupBanners
   * const popupBanner = await prisma.popupBanner.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PopupBannerCreateManyArgs>(args?: Prisma.SelectSubset<T, PopupBannerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PopupBanners and returns the data saved in the database.
   * @param {PopupBannerCreateManyAndReturnArgs} args - Arguments to create many PopupBanners.
   * @example
   * // Create many PopupBanners
   * const popupBanner = await prisma.popupBanner.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PopupBanners and only return the `id`
   * const popupBannerWithIdOnly = await prisma.popupBanner.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PopupBannerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PopupBannerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PopupBannerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PopupBanner.
   * @param {PopupBannerDeleteArgs} args - Arguments to delete one PopupBanner.
   * @example
   * // Delete one PopupBanner
   * const PopupBanner = await prisma.popupBanner.delete({
   *   where: {
   *     // ... filter to delete one PopupBanner
   *   }
   * })
   * 
   */
  delete<T extends PopupBannerDeleteArgs>(args: Prisma.SelectSubset<T, PopupBannerDeleteArgs<ExtArgs>>): Prisma.Prisma__PopupBannerClient<runtime.Types.Result.GetResult<Prisma.$PopupBannerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PopupBanner.
   * @param {PopupBannerUpdateArgs} args - Arguments to update one PopupBanner.
   * @example
   * // Update one PopupBanner
   * const popupBanner = await prisma.popupBanner.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PopupBannerUpdateArgs>(args: Prisma.SelectSubset<T, PopupBannerUpdateArgs<ExtArgs>>): Prisma.Prisma__PopupBannerClient<runtime.Types.Result.GetResult<Prisma.$PopupBannerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PopupBanners.
   * @param {PopupBannerDeleteManyArgs} args - Arguments to filter PopupBanners to delete.
   * @example
   * // Delete a few PopupBanners
   * const { count } = await prisma.popupBanner.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PopupBannerDeleteManyArgs>(args?: Prisma.SelectSubset<T, PopupBannerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PopupBanners.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PopupBannerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PopupBanners
   * const popupBanner = await prisma.popupBanner.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PopupBannerUpdateManyArgs>(args: Prisma.SelectSubset<T, PopupBannerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PopupBanners and returns the data updated in the database.
   * @param {PopupBannerUpdateManyAndReturnArgs} args - Arguments to update many PopupBanners.
   * @example
   * // Update many PopupBanners
   * const popupBanner = await prisma.popupBanner.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PopupBanners and only return the `id`
   * const popupBannerWithIdOnly = await prisma.popupBanner.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PopupBannerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PopupBannerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PopupBannerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PopupBanner.
   * @param {PopupBannerUpsertArgs} args - Arguments to update or create a PopupBanner.
   * @example
   * // Update or create a PopupBanner
   * const popupBanner = await prisma.popupBanner.upsert({
   *   create: {
   *     // ... data to create a PopupBanner
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PopupBanner we want to update
   *   }
   * })
   */
  upsert<T extends PopupBannerUpsertArgs>(args: Prisma.SelectSubset<T, PopupBannerUpsertArgs<ExtArgs>>): Prisma.Prisma__PopupBannerClient<runtime.Types.Result.GetResult<Prisma.$PopupBannerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PopupBanners.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PopupBannerCountArgs} args - Arguments to filter PopupBanners to count.
   * @example
   * // Count the number of PopupBanners
   * const count = await prisma.popupBanner.count({
   *   where: {
   *     // ... the filter for the PopupBanners we want to count
   *   }
   * })
  **/
  count<T extends PopupBannerCountArgs>(
    args?: Prisma.Subset<T, PopupBannerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PopupBannerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PopupBanner.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PopupBannerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PopupBannerAggregateArgs>(args: Prisma.Subset<T, PopupBannerAggregateArgs>): Prisma.PrismaPromise<GetPopupBannerAggregateType<T>>

  /**
   * Group by PopupBanner.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PopupBannerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PopupBannerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PopupBannerGroupByArgs['orderBy'] }
      : { orderBy?: PopupBannerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PopupBannerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPopupBannerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PopupBanner model
 */
readonly fields: PopupBannerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PopupBanner.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PopupBannerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PopupBanner model
 */
export interface PopupBannerFieldRefs {
  readonly id: Prisma.FieldRef<"PopupBanner", 'String'>
  readonly title: Prisma.FieldRef<"PopupBanner", 'String'>
  readonly content: Prisma.FieldRef<"PopupBanner", 'String'>
  readonly enabled: Prisma.FieldRef<"PopupBanner", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"PopupBanner", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PopupBanner", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PopupBanner findUnique
 */
export type PopupBannerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupBanner
   */
  select?: Prisma.PopupBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupBanner
   */
  omit?: Prisma.PopupBannerOmit<ExtArgs> | null
  /**
   * Filter, which PopupBanner to fetch.
   */
  where: Prisma.PopupBannerWhereUniqueInput
}

/**
 * PopupBanner findUniqueOrThrow
 */
export type PopupBannerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupBanner
   */
  select?: Prisma.PopupBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupBanner
   */
  omit?: Prisma.PopupBannerOmit<ExtArgs> | null
  /**
   * Filter, which PopupBanner to fetch.
   */
  where: Prisma.PopupBannerWhereUniqueInput
}

/**
 * PopupBanner findFirst
 */
export type PopupBannerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupBanner
   */
  select?: Prisma.PopupBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupBanner
   */
  omit?: Prisma.PopupBannerOmit<ExtArgs> | null
  /**
   * Filter, which PopupBanner to fetch.
   */
  where?: Prisma.PopupBannerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PopupBanners to fetch.
   */
  orderBy?: Prisma.PopupBannerOrderByWithRelationInput | Prisma.PopupBannerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PopupBanners.
   */
  cursor?: Prisma.PopupBannerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PopupBanners from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PopupBanners.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PopupBanners.
   */
  distinct?: Prisma.PopupBannerScalarFieldEnum | Prisma.PopupBannerScalarFieldEnum[]
}

/**
 * PopupBanner findFirstOrThrow
 */
export type PopupBannerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupBanner
   */
  select?: Prisma.PopupBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupBanner
   */
  omit?: Prisma.PopupBannerOmit<ExtArgs> | null
  /**
   * Filter, which PopupBanner to fetch.
   */
  where?: Prisma.PopupBannerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PopupBanners to fetch.
   */
  orderBy?: Prisma.PopupBannerOrderByWithRelationInput | Prisma.PopupBannerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PopupBanners.
   */
  cursor?: Prisma.PopupBannerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PopupBanners from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PopupBanners.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PopupBanners.
   */
  distinct?: Prisma.PopupBannerScalarFieldEnum | Prisma.PopupBannerScalarFieldEnum[]
}

/**
 * PopupBanner findMany
 */
export type PopupBannerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupBanner
   */
  select?: Prisma.PopupBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupBanner
   */
  omit?: Prisma.PopupBannerOmit<ExtArgs> | null
  /**
   * Filter, which PopupBanners to fetch.
   */
  where?: Prisma.PopupBannerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PopupBanners to fetch.
   */
  orderBy?: Prisma.PopupBannerOrderByWithRelationInput | Prisma.PopupBannerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PopupBanners.
   */
  cursor?: Prisma.PopupBannerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PopupBanners from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PopupBanners.
   */
  skip?: number
  distinct?: Prisma.PopupBannerScalarFieldEnum | Prisma.PopupBannerScalarFieldEnum[]
}

/**
 * PopupBanner create
 */
export type PopupBannerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupBanner
   */
  select?: Prisma.PopupBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupBanner
   */
  omit?: Prisma.PopupBannerOmit<ExtArgs> | null
  /**
   * The data needed to create a PopupBanner.
   */
  data: Prisma.XOR<Prisma.PopupBannerCreateInput, Prisma.PopupBannerUncheckedCreateInput>
}

/**
 * PopupBanner createMany
 */
export type PopupBannerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PopupBanners.
   */
  data: Prisma.PopupBannerCreateManyInput | Prisma.PopupBannerCreateManyInput[]
}

/**
 * PopupBanner createManyAndReturn
 */
export type PopupBannerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupBanner
   */
  select?: Prisma.PopupBannerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PopupBanner
   */
  omit?: Prisma.PopupBannerOmit<ExtArgs> | null
  /**
   * The data used to create many PopupBanners.
   */
  data: Prisma.PopupBannerCreateManyInput | Prisma.PopupBannerCreateManyInput[]
}

/**
 * PopupBanner update
 */
export type PopupBannerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupBanner
   */
  select?: Prisma.PopupBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupBanner
   */
  omit?: Prisma.PopupBannerOmit<ExtArgs> | null
  /**
   * The data needed to update a PopupBanner.
   */
  data: Prisma.XOR<Prisma.PopupBannerUpdateInput, Prisma.PopupBannerUncheckedUpdateInput>
  /**
   * Choose, which PopupBanner to update.
   */
  where: Prisma.PopupBannerWhereUniqueInput
}

/**
 * PopupBanner updateMany
 */
export type PopupBannerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PopupBanners.
   */
  data: Prisma.XOR<Prisma.PopupBannerUpdateManyMutationInput, Prisma.PopupBannerUncheckedUpdateManyInput>
  /**
   * Filter which PopupBanners to update
   */
  where?: Prisma.PopupBannerWhereInput
  /**
   * Limit how many PopupBanners to update.
   */
  limit?: number
}

/**
 * PopupBanner updateManyAndReturn
 */
export type PopupBannerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupBanner
   */
  select?: Prisma.PopupBannerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PopupBanner
   */
  omit?: Prisma.PopupBannerOmit<ExtArgs> | null
  /**
   * The data used to update PopupBanners.
   */
  data: Prisma.XOR<Prisma.PopupBannerUpdateManyMutationInput, Prisma.PopupBannerUncheckedUpdateManyInput>
  /**
   * Filter which PopupBanners to update
   */
  where?: Prisma.PopupBannerWhereInput
  /**
   * Limit how many PopupBanners to update.
   */
  limit?: number
}

/**
 * PopupBanner upsert
 */
export type PopupBannerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupBanner
   */
  select?: Prisma.PopupBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupBanner
   */
  omit?: Prisma.PopupBannerOmit<ExtArgs> | null
  /**
   * The filter to search for the PopupBanner to update in case it exists.
   */
  where: Prisma.PopupBannerWhereUniqueInput
  /**
   * In case the PopupBanner found by the `where` argument doesn't exist, create a new PopupBanner with this data.
   */
  create: Prisma.XOR<Prisma.PopupBannerCreateInput, Prisma.PopupBannerUncheckedCreateInput>
  /**
   * In case the PopupBanner was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PopupBannerUpdateInput, Prisma.PopupBannerUncheckedUpdateInput>
}

/**
 * PopupBanner delete
 */
export type PopupBannerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupBanner
   */
  select?: Prisma.PopupBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupBanner
   */
  omit?: Prisma.PopupBannerOmit<ExtArgs> | null
  /**
   * Filter which PopupBanner to delete.
   */
  where: Prisma.PopupBannerWhereUniqueInput
}

/**
 * PopupBanner deleteMany
 */
export type PopupBannerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PopupBanners to delete
   */
  where?: Prisma.PopupBannerWhereInput
  /**
   * Limit how many PopupBanners to delete.
   */
  limit?: number
}

/**
 * PopupBanner without action
 */
export type PopupBannerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PopupBanner
   */
  select?: Prisma.PopupBannerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PopupBanner
   */
  omit?: Prisma.PopupBannerOmit<ExtArgs> | null
}
