
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `QuestionPaper` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model QuestionPaper
 * 
 */
export type QuestionPaperModel = runtime.Types.Result.DefaultSelection<Prisma.$QuestionPaperPayload>

export type AggregateQuestionPaper = {
  _count: QuestionPaperCountAggregateOutputType | null
  _avg: QuestionPaperAvgAggregateOutputType | null
  _sum: QuestionPaperSumAggregateOutputType | null
  _min: QuestionPaperMinAggregateOutputType | null
  _max: QuestionPaperMaxAggregateOutputType | null
}

export type QuestionPaperAvgAggregateOutputType = {
  semester: number | null
  examYear: number | null
  fileSize: number | null
  downloadCount: number | null
}

export type QuestionPaperSumAggregateOutputType = {
  semester: number | null
  examYear: number | null
  fileSize: number | null
  downloadCount: number | null
}

export type QuestionPaperMinAggregateOutputType = {
  id: string | null
  academicYear: string | null
  department: string | null
  programme: string | null
  semester: number | null
  courseName: string | null
  courseCode: string | null
  examType: string | null
  examMonth: string | null
  examYear: number | null
  description: string | null
  fileUrl: string | null
  originalName: string | null
  fileType: string | null
  fileSize: number | null
  downloadCount: number | null
  published: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type QuestionPaperMaxAggregateOutputType = {
  id: string | null
  academicYear: string | null
  department: string | null
  programme: string | null
  semester: number | null
  courseName: string | null
  courseCode: string | null
  examType: string | null
  examMonth: string | null
  examYear: number | null
  description: string | null
  fileUrl: string | null
  originalName: string | null
  fileType: string | null
  fileSize: number | null
  downloadCount: number | null
  published: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type QuestionPaperCountAggregateOutputType = {
  id: number
  academicYear: number
  department: number
  programme: number
  semester: number
  courseName: number
  courseCode: number
  examType: number
  examMonth: number
  examYear: number
  description: number
  fileUrl: number
  originalName: number
  fileType: number
  fileSize: number
  downloadCount: number
  published: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type QuestionPaperAvgAggregateInputType = {
  semester?: true
  examYear?: true
  fileSize?: true
  downloadCount?: true
}

export type QuestionPaperSumAggregateInputType = {
  semester?: true
  examYear?: true
  fileSize?: true
  downloadCount?: true
}

export type QuestionPaperMinAggregateInputType = {
  id?: true
  academicYear?: true
  department?: true
  programme?: true
  semester?: true
  courseName?: true
  courseCode?: true
  examType?: true
  examMonth?: true
  examYear?: true
  description?: true
  fileUrl?: true
  originalName?: true
  fileType?: true
  fileSize?: true
  downloadCount?: true
  published?: true
  createdAt?: true
  updatedAt?: true
}

export type QuestionPaperMaxAggregateInputType = {
  id?: true
  academicYear?: true
  department?: true
  programme?: true
  semester?: true
  courseName?: true
  courseCode?: true
  examType?: true
  examMonth?: true
  examYear?: true
  description?: true
  fileUrl?: true
  originalName?: true
  fileType?: true
  fileSize?: true
  downloadCount?: true
  published?: true
  createdAt?: true
  updatedAt?: true
}

export type QuestionPaperCountAggregateInputType = {
  id?: true
  academicYear?: true
  department?: true
  programme?: true
  semester?: true
  courseName?: true
  courseCode?: true
  examType?: true
  examMonth?: true
  examYear?: true
  description?: true
  fileUrl?: true
  originalName?: true
  fileType?: true
  fileSize?: true
  downloadCount?: true
  published?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type QuestionPaperAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuestionPaper to aggregate.
   */
  where?: Prisma.QuestionPaperWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionPapers to fetch.
   */
  orderBy?: Prisma.QuestionPaperOrderByWithRelationInput | Prisma.QuestionPaperOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QuestionPaperWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionPapers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionPapers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned QuestionPapers
  **/
  _count?: true | QuestionPaperCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: QuestionPaperAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: QuestionPaperSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QuestionPaperMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QuestionPaperMaxAggregateInputType
}

export type GetQuestionPaperAggregateType<T extends QuestionPaperAggregateArgs> = {
      [P in keyof T & keyof AggregateQuestionPaper]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQuestionPaper[P]>
    : Prisma.GetScalarType<T[P], AggregateQuestionPaper[P]>
}




export type QuestionPaperGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuestionPaperWhereInput
  orderBy?: Prisma.QuestionPaperOrderByWithAggregationInput | Prisma.QuestionPaperOrderByWithAggregationInput[]
  by: Prisma.QuestionPaperScalarFieldEnum[] | Prisma.QuestionPaperScalarFieldEnum
  having?: Prisma.QuestionPaperScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QuestionPaperCountAggregateInputType | true
  _avg?: QuestionPaperAvgAggregateInputType
  _sum?: QuestionPaperSumAggregateInputType
  _min?: QuestionPaperMinAggregateInputType
  _max?: QuestionPaperMaxAggregateInputType
}

export type QuestionPaperGroupByOutputType = {
  id: string
  academicYear: string
  department: string
  programme: string
  semester: number
  courseName: string
  courseCode: string
  examType: string
  examMonth: string | null
  examYear: number
  description: string | null
  fileUrl: string
  originalName: string
  fileType: string | null
  fileSize: number | null
  downloadCount: number
  published: boolean
  createdAt: Date
  updatedAt: Date
  _count: QuestionPaperCountAggregateOutputType | null
  _avg: QuestionPaperAvgAggregateOutputType | null
  _sum: QuestionPaperSumAggregateOutputType | null
  _min: QuestionPaperMinAggregateOutputType | null
  _max: QuestionPaperMaxAggregateOutputType | null
}

type GetQuestionPaperGroupByPayload<T extends QuestionPaperGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QuestionPaperGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QuestionPaperGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QuestionPaperGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QuestionPaperGroupByOutputType[P]>
      }
    >
  >



export type QuestionPaperWhereInput = {
  AND?: Prisma.QuestionPaperWhereInput | Prisma.QuestionPaperWhereInput[]
  OR?: Prisma.QuestionPaperWhereInput[]
  NOT?: Prisma.QuestionPaperWhereInput | Prisma.QuestionPaperWhereInput[]
  id?: Prisma.StringFilter<"QuestionPaper"> | string
  academicYear?: Prisma.StringFilter<"QuestionPaper"> | string
  department?: Prisma.StringFilter<"QuestionPaper"> | string
  programme?: Prisma.StringFilter<"QuestionPaper"> | string
  semester?: Prisma.IntFilter<"QuestionPaper"> | number
  courseName?: Prisma.StringFilter<"QuestionPaper"> | string
  courseCode?: Prisma.StringFilter<"QuestionPaper"> | string
  examType?: Prisma.StringFilter<"QuestionPaper"> | string
  examMonth?: Prisma.StringNullableFilter<"QuestionPaper"> | string | null
  examYear?: Prisma.IntFilter<"QuestionPaper"> | number
  description?: Prisma.StringNullableFilter<"QuestionPaper"> | string | null
  fileUrl?: Prisma.StringFilter<"QuestionPaper"> | string
  originalName?: Prisma.StringFilter<"QuestionPaper"> | string
  fileType?: Prisma.StringNullableFilter<"QuestionPaper"> | string | null
  fileSize?: Prisma.IntNullableFilter<"QuestionPaper"> | number | null
  downloadCount?: Prisma.IntFilter<"QuestionPaper"> | number
  published?: Prisma.BoolFilter<"QuestionPaper"> | boolean
  createdAt?: Prisma.DateTimeFilter<"QuestionPaper"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QuestionPaper"> | Date | string
}

export type QuestionPaperOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  academicYear?: Prisma.SortOrder
  department?: Prisma.SortOrder
  programme?: Prisma.SortOrder
  semester?: Prisma.SortOrder
  courseName?: Prisma.SortOrder
  courseCode?: Prisma.SortOrder
  examType?: Prisma.SortOrder
  examMonth?: Prisma.SortOrderInput | Prisma.SortOrder
  examYear?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  originalName?: Prisma.SortOrder
  fileType?: Prisma.SortOrderInput | Prisma.SortOrder
  fileSize?: Prisma.SortOrderInput | Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  published?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuestionPaperWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  academicYear_department_programme_semester_courseCode_examType_examYear?: Prisma.QuestionPaperAcademicYearDepartmentProgrammeSemesterCourseCodeExamTypeExamYearCompoundUniqueInput
  AND?: Prisma.QuestionPaperWhereInput | Prisma.QuestionPaperWhereInput[]
  OR?: Prisma.QuestionPaperWhereInput[]
  NOT?: Prisma.QuestionPaperWhereInput | Prisma.QuestionPaperWhereInput[]
  academicYear?: Prisma.StringFilter<"QuestionPaper"> | string
  department?: Prisma.StringFilter<"QuestionPaper"> | string
  programme?: Prisma.StringFilter<"QuestionPaper"> | string
  semester?: Prisma.IntFilter<"QuestionPaper"> | number
  courseName?: Prisma.StringFilter<"QuestionPaper"> | string
  courseCode?: Prisma.StringFilter<"QuestionPaper"> | string
  examType?: Prisma.StringFilter<"QuestionPaper"> | string
  examMonth?: Prisma.StringNullableFilter<"QuestionPaper"> | string | null
  examYear?: Prisma.IntFilter<"QuestionPaper"> | number
  description?: Prisma.StringNullableFilter<"QuestionPaper"> | string | null
  fileUrl?: Prisma.StringFilter<"QuestionPaper"> | string
  originalName?: Prisma.StringFilter<"QuestionPaper"> | string
  fileType?: Prisma.StringNullableFilter<"QuestionPaper"> | string | null
  fileSize?: Prisma.IntNullableFilter<"QuestionPaper"> | number | null
  downloadCount?: Prisma.IntFilter<"QuestionPaper"> | number
  published?: Prisma.BoolFilter<"QuestionPaper"> | boolean
  createdAt?: Prisma.DateTimeFilter<"QuestionPaper"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QuestionPaper"> | Date | string
}, "id" | "academicYear_department_programme_semester_courseCode_examType_examYear">

export type QuestionPaperOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  academicYear?: Prisma.SortOrder
  department?: Prisma.SortOrder
  programme?: Prisma.SortOrder
  semester?: Prisma.SortOrder
  courseName?: Prisma.SortOrder
  courseCode?: Prisma.SortOrder
  examType?: Prisma.SortOrder
  examMonth?: Prisma.SortOrderInput | Prisma.SortOrder
  examYear?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  originalName?: Prisma.SortOrder
  fileType?: Prisma.SortOrderInput | Prisma.SortOrder
  fileSize?: Prisma.SortOrderInput | Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  published?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.QuestionPaperCountOrderByAggregateInput
  _avg?: Prisma.QuestionPaperAvgOrderByAggregateInput
  _max?: Prisma.QuestionPaperMaxOrderByAggregateInput
  _min?: Prisma.QuestionPaperMinOrderByAggregateInput
  _sum?: Prisma.QuestionPaperSumOrderByAggregateInput
}

export type QuestionPaperScalarWhereWithAggregatesInput = {
  AND?: Prisma.QuestionPaperScalarWhereWithAggregatesInput | Prisma.QuestionPaperScalarWhereWithAggregatesInput[]
  OR?: Prisma.QuestionPaperScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QuestionPaperScalarWhereWithAggregatesInput | Prisma.QuestionPaperScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"QuestionPaper"> | string
  academicYear?: Prisma.StringWithAggregatesFilter<"QuestionPaper"> | string
  department?: Prisma.StringWithAggregatesFilter<"QuestionPaper"> | string
  programme?: Prisma.StringWithAggregatesFilter<"QuestionPaper"> | string
  semester?: Prisma.IntWithAggregatesFilter<"QuestionPaper"> | number
  courseName?: Prisma.StringWithAggregatesFilter<"QuestionPaper"> | string
  courseCode?: Prisma.StringWithAggregatesFilter<"QuestionPaper"> | string
  examType?: Prisma.StringWithAggregatesFilter<"QuestionPaper"> | string
  examMonth?: Prisma.StringNullableWithAggregatesFilter<"QuestionPaper"> | string | null
  examYear?: Prisma.IntWithAggregatesFilter<"QuestionPaper"> | number
  description?: Prisma.StringNullableWithAggregatesFilter<"QuestionPaper"> | string | null
  fileUrl?: Prisma.StringWithAggregatesFilter<"QuestionPaper"> | string
  originalName?: Prisma.StringWithAggregatesFilter<"QuestionPaper"> | string
  fileType?: Prisma.StringNullableWithAggregatesFilter<"QuestionPaper"> | string | null
  fileSize?: Prisma.IntNullableWithAggregatesFilter<"QuestionPaper"> | number | null
  downloadCount?: Prisma.IntWithAggregatesFilter<"QuestionPaper"> | number
  published?: Prisma.BoolWithAggregatesFilter<"QuestionPaper"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"QuestionPaper"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"QuestionPaper"> | Date | string
}

export type QuestionPaperCreateInput = {
  id?: string
  academicYear: string
  department: string
  programme?: string
  semester?: number
  courseName: string
  courseCode: string
  examType: string
  examMonth?: string | null
  examYear: number
  description?: string | null
  fileUrl: string
  originalName: string
  fileType?: string | null
  fileSize?: number | null
  downloadCount?: number
  published?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionPaperUncheckedCreateInput = {
  id?: string
  academicYear: string
  department: string
  programme?: string
  semester?: number
  courseName: string
  courseCode: string
  examType: string
  examMonth?: string | null
  examYear: number
  description?: string | null
  fileUrl: string
  originalName: string
  fileType?: string | null
  fileSize?: number | null
  downloadCount?: number
  published?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionPaperUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  academicYear?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  programme?: Prisma.StringFieldUpdateOperationsInput | string
  semester?: Prisma.IntFieldUpdateOperationsInput | number
  courseName?: Prisma.StringFieldUpdateOperationsInput | string
  courseCode?: Prisma.StringFieldUpdateOperationsInput | string
  examType?: Prisma.StringFieldUpdateOperationsInput | string
  examMonth?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  examYear?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  originalName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  downloadCount?: Prisma.IntFieldUpdateOperationsInput | number
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionPaperUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  academicYear?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  programme?: Prisma.StringFieldUpdateOperationsInput | string
  semester?: Prisma.IntFieldUpdateOperationsInput | number
  courseName?: Prisma.StringFieldUpdateOperationsInput | string
  courseCode?: Prisma.StringFieldUpdateOperationsInput | string
  examType?: Prisma.StringFieldUpdateOperationsInput | string
  examMonth?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  examYear?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  originalName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  downloadCount?: Prisma.IntFieldUpdateOperationsInput | number
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionPaperCreateManyInput = {
  id?: string
  academicYear: string
  department: string
  programme?: string
  semester?: number
  courseName: string
  courseCode: string
  examType: string
  examMonth?: string | null
  examYear: number
  description?: string | null
  fileUrl: string
  originalName: string
  fileType?: string | null
  fileSize?: number | null
  downloadCount?: number
  published?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionPaperUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  academicYear?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  programme?: Prisma.StringFieldUpdateOperationsInput | string
  semester?: Prisma.IntFieldUpdateOperationsInput | number
  courseName?: Prisma.StringFieldUpdateOperationsInput | string
  courseCode?: Prisma.StringFieldUpdateOperationsInput | string
  examType?: Prisma.StringFieldUpdateOperationsInput | string
  examMonth?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  examYear?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  originalName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  downloadCount?: Prisma.IntFieldUpdateOperationsInput | number
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionPaperUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  academicYear?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  programme?: Prisma.StringFieldUpdateOperationsInput | string
  semester?: Prisma.IntFieldUpdateOperationsInput | number
  courseName?: Prisma.StringFieldUpdateOperationsInput | string
  courseCode?: Prisma.StringFieldUpdateOperationsInput | string
  examType?: Prisma.StringFieldUpdateOperationsInput | string
  examMonth?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  examYear?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  originalName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  downloadCount?: Prisma.IntFieldUpdateOperationsInput | number
  published?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionPaperAcademicYearDepartmentProgrammeSemesterCourseCodeExamTypeExamYearCompoundUniqueInput = {
  academicYear: string
  department: string
  programme: string
  semester: number
  courseCode: string
  examType: string
  examYear: number
}

export type QuestionPaperCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  academicYear?: Prisma.SortOrder
  department?: Prisma.SortOrder
  programme?: Prisma.SortOrder
  semester?: Prisma.SortOrder
  courseName?: Prisma.SortOrder
  courseCode?: Prisma.SortOrder
  examType?: Prisma.SortOrder
  examMonth?: Prisma.SortOrder
  examYear?: Prisma.SortOrder
  description?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  originalName?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  published?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuestionPaperAvgOrderByAggregateInput = {
  semester?: Prisma.SortOrder
  examYear?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
}

export type QuestionPaperMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  academicYear?: Prisma.SortOrder
  department?: Prisma.SortOrder
  programme?: Prisma.SortOrder
  semester?: Prisma.SortOrder
  courseName?: Prisma.SortOrder
  courseCode?: Prisma.SortOrder
  examType?: Prisma.SortOrder
  examMonth?: Prisma.SortOrder
  examYear?: Prisma.SortOrder
  description?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  originalName?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  published?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuestionPaperMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  academicYear?: Prisma.SortOrder
  department?: Prisma.SortOrder
  programme?: Prisma.SortOrder
  semester?: Prisma.SortOrder
  courseName?: Prisma.SortOrder
  courseCode?: Prisma.SortOrder
  examType?: Prisma.SortOrder
  examMonth?: Prisma.SortOrder
  examYear?: Prisma.SortOrder
  description?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  originalName?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  published?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuestionPaperSumOrderByAggregateInput = {
  semester?: Prisma.SortOrder
  examYear?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type QuestionPaperSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  academicYear?: boolean
  department?: boolean
  programme?: boolean
  semester?: boolean
  courseName?: boolean
  courseCode?: boolean
  examType?: boolean
  examMonth?: boolean
  examYear?: boolean
  description?: boolean
  fileUrl?: boolean
  originalName?: boolean
  fileType?: boolean
  fileSize?: boolean
  downloadCount?: boolean
  published?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["questionPaper"]>

export type QuestionPaperSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  academicYear?: boolean
  department?: boolean
  programme?: boolean
  semester?: boolean
  courseName?: boolean
  courseCode?: boolean
  examType?: boolean
  examMonth?: boolean
  examYear?: boolean
  description?: boolean
  fileUrl?: boolean
  originalName?: boolean
  fileType?: boolean
  fileSize?: boolean
  downloadCount?: boolean
  published?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["questionPaper"]>

export type QuestionPaperSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  academicYear?: boolean
  department?: boolean
  programme?: boolean
  semester?: boolean
  courseName?: boolean
  courseCode?: boolean
  examType?: boolean
  examMonth?: boolean
  examYear?: boolean
  description?: boolean
  fileUrl?: boolean
  originalName?: boolean
  fileType?: boolean
  fileSize?: boolean
  downloadCount?: boolean
  published?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["questionPaper"]>

export type QuestionPaperSelectScalar = {
  id?: boolean
  academicYear?: boolean
  department?: boolean
  programme?: boolean
  semester?: boolean
  courseName?: boolean
  courseCode?: boolean
  examType?: boolean
  examMonth?: boolean
  examYear?: boolean
  description?: boolean
  fileUrl?: boolean
  originalName?: boolean
  fileType?: boolean
  fileSize?: boolean
  downloadCount?: boolean
  published?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type QuestionPaperOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "academicYear" | "department" | "programme" | "semester" | "courseName" | "courseCode" | "examType" | "examMonth" | "examYear" | "description" | "fileUrl" | "originalName" | "fileType" | "fileSize" | "downloadCount" | "published" | "createdAt" | "updatedAt", ExtArgs["result"]["questionPaper"]>

export type $QuestionPaperPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "QuestionPaper"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    academicYear: string
    department: string
    programme: string
    semester: number
    courseName: string
    courseCode: string
    examType: string
    examMonth: string | null
    examYear: number
    description: string | null
    fileUrl: string
    originalName: string
    fileType: string | null
    fileSize: number | null
    downloadCount: number
    published: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["questionPaper"]>
  composites: {}
}

export type QuestionPaperGetPayload<S extends boolean | null | undefined | QuestionPaperDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QuestionPaperPayload, S>

export type QuestionPaperCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QuestionPaperFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QuestionPaperCountAggregateInputType | true
  }

export interface QuestionPaperDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['QuestionPaper'], meta: { name: 'QuestionPaper' } }
  /**
   * Find zero or one QuestionPaper that matches the filter.
   * @param {QuestionPaperFindUniqueArgs} args - Arguments to find a QuestionPaper
   * @example
   * // Get one QuestionPaper
   * const questionPaper = await prisma.questionPaper.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QuestionPaperFindUniqueArgs>(args: Prisma.SelectSubset<T, QuestionPaperFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QuestionPaperClient<runtime.Types.Result.GetResult<Prisma.$QuestionPaperPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one QuestionPaper that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QuestionPaperFindUniqueOrThrowArgs} args - Arguments to find a QuestionPaper
   * @example
   * // Get one QuestionPaper
   * const questionPaper = await prisma.questionPaper.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QuestionPaperFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QuestionPaperFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuestionPaperClient<runtime.Types.Result.GetResult<Prisma.$QuestionPaperPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuestionPaper that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionPaperFindFirstArgs} args - Arguments to find a QuestionPaper
   * @example
   * // Get one QuestionPaper
   * const questionPaper = await prisma.questionPaper.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QuestionPaperFindFirstArgs>(args?: Prisma.SelectSubset<T, QuestionPaperFindFirstArgs<ExtArgs>>): Prisma.Prisma__QuestionPaperClient<runtime.Types.Result.GetResult<Prisma.$QuestionPaperPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuestionPaper that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionPaperFindFirstOrThrowArgs} args - Arguments to find a QuestionPaper
   * @example
   * // Get one QuestionPaper
   * const questionPaper = await prisma.questionPaper.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QuestionPaperFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QuestionPaperFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuestionPaperClient<runtime.Types.Result.GetResult<Prisma.$QuestionPaperPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more QuestionPapers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionPaperFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all QuestionPapers
   * const questionPapers = await prisma.questionPaper.findMany()
   * 
   * // Get first 10 QuestionPapers
   * const questionPapers = await prisma.questionPaper.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const questionPaperWithIdOnly = await prisma.questionPaper.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends QuestionPaperFindManyArgs>(args?: Prisma.SelectSubset<T, QuestionPaperFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionPaperPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a QuestionPaper.
   * @param {QuestionPaperCreateArgs} args - Arguments to create a QuestionPaper.
   * @example
   * // Create one QuestionPaper
   * const QuestionPaper = await prisma.questionPaper.create({
   *   data: {
   *     // ... data to create a QuestionPaper
   *   }
   * })
   * 
   */
  create<T extends QuestionPaperCreateArgs>(args: Prisma.SelectSubset<T, QuestionPaperCreateArgs<ExtArgs>>): Prisma.Prisma__QuestionPaperClient<runtime.Types.Result.GetResult<Prisma.$QuestionPaperPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many QuestionPapers.
   * @param {QuestionPaperCreateManyArgs} args - Arguments to create many QuestionPapers.
   * @example
   * // Create many QuestionPapers
   * const questionPaper = await prisma.questionPaper.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QuestionPaperCreateManyArgs>(args?: Prisma.SelectSubset<T, QuestionPaperCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many QuestionPapers and returns the data saved in the database.
   * @param {QuestionPaperCreateManyAndReturnArgs} args - Arguments to create many QuestionPapers.
   * @example
   * // Create many QuestionPapers
   * const questionPaper = await prisma.questionPaper.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many QuestionPapers and only return the `id`
   * const questionPaperWithIdOnly = await prisma.questionPaper.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QuestionPaperCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QuestionPaperCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionPaperPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a QuestionPaper.
   * @param {QuestionPaperDeleteArgs} args - Arguments to delete one QuestionPaper.
   * @example
   * // Delete one QuestionPaper
   * const QuestionPaper = await prisma.questionPaper.delete({
   *   where: {
   *     // ... filter to delete one QuestionPaper
   *   }
   * })
   * 
   */
  delete<T extends QuestionPaperDeleteArgs>(args: Prisma.SelectSubset<T, QuestionPaperDeleteArgs<ExtArgs>>): Prisma.Prisma__QuestionPaperClient<runtime.Types.Result.GetResult<Prisma.$QuestionPaperPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one QuestionPaper.
   * @param {QuestionPaperUpdateArgs} args - Arguments to update one QuestionPaper.
   * @example
   * // Update one QuestionPaper
   * const questionPaper = await prisma.questionPaper.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QuestionPaperUpdateArgs>(args: Prisma.SelectSubset<T, QuestionPaperUpdateArgs<ExtArgs>>): Prisma.Prisma__QuestionPaperClient<runtime.Types.Result.GetResult<Prisma.$QuestionPaperPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more QuestionPapers.
   * @param {QuestionPaperDeleteManyArgs} args - Arguments to filter QuestionPapers to delete.
   * @example
   * // Delete a few QuestionPapers
   * const { count } = await prisma.questionPaper.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QuestionPaperDeleteManyArgs>(args?: Prisma.SelectSubset<T, QuestionPaperDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuestionPapers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionPaperUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many QuestionPapers
   * const questionPaper = await prisma.questionPaper.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QuestionPaperUpdateManyArgs>(args: Prisma.SelectSubset<T, QuestionPaperUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuestionPapers and returns the data updated in the database.
   * @param {QuestionPaperUpdateManyAndReturnArgs} args - Arguments to update many QuestionPapers.
   * @example
   * // Update many QuestionPapers
   * const questionPaper = await prisma.questionPaper.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more QuestionPapers and only return the `id`
   * const questionPaperWithIdOnly = await prisma.questionPaper.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QuestionPaperUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QuestionPaperUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionPaperPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one QuestionPaper.
   * @param {QuestionPaperUpsertArgs} args - Arguments to update or create a QuestionPaper.
   * @example
   * // Update or create a QuestionPaper
   * const questionPaper = await prisma.questionPaper.upsert({
   *   create: {
   *     // ... data to create a QuestionPaper
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the QuestionPaper we want to update
   *   }
   * })
   */
  upsert<T extends QuestionPaperUpsertArgs>(args: Prisma.SelectSubset<T, QuestionPaperUpsertArgs<ExtArgs>>): Prisma.Prisma__QuestionPaperClient<runtime.Types.Result.GetResult<Prisma.$QuestionPaperPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of QuestionPapers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionPaperCountArgs} args - Arguments to filter QuestionPapers to count.
   * @example
   * // Count the number of QuestionPapers
   * const count = await prisma.questionPaper.count({
   *   where: {
   *     // ... the filter for the QuestionPapers we want to count
   *   }
   * })
  **/
  count<T extends QuestionPaperCountArgs>(
    args?: Prisma.Subset<T, QuestionPaperCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QuestionPaperCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a QuestionPaper.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionPaperAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QuestionPaperAggregateArgs>(args: Prisma.Subset<T, QuestionPaperAggregateArgs>): Prisma.PrismaPromise<GetQuestionPaperAggregateType<T>>

  /**
   * Group by QuestionPaper.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionPaperGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QuestionPaperGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QuestionPaperGroupByArgs['orderBy'] }
      : { orderBy?: QuestionPaperGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QuestionPaperGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQuestionPaperGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the QuestionPaper model
 */
readonly fields: QuestionPaperFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QuestionPaper.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuestionPaperClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the QuestionPaper model
 */
export interface QuestionPaperFieldRefs {
  readonly id: Prisma.FieldRef<"QuestionPaper", 'String'>
  readonly academicYear: Prisma.FieldRef<"QuestionPaper", 'String'>
  readonly department: Prisma.FieldRef<"QuestionPaper", 'String'>
  readonly programme: Prisma.FieldRef<"QuestionPaper", 'String'>
  readonly semester: Prisma.FieldRef<"QuestionPaper", 'Int'>
  readonly courseName: Prisma.FieldRef<"QuestionPaper", 'String'>
  readonly courseCode: Prisma.FieldRef<"QuestionPaper", 'String'>
  readonly examType: Prisma.FieldRef<"QuestionPaper", 'String'>
  readonly examMonth: Prisma.FieldRef<"QuestionPaper", 'String'>
  readonly examYear: Prisma.FieldRef<"QuestionPaper", 'Int'>
  readonly description: Prisma.FieldRef<"QuestionPaper", 'String'>
  readonly fileUrl: Prisma.FieldRef<"QuestionPaper", 'String'>
  readonly originalName: Prisma.FieldRef<"QuestionPaper", 'String'>
  readonly fileType: Prisma.FieldRef<"QuestionPaper", 'String'>
  readonly fileSize: Prisma.FieldRef<"QuestionPaper", 'Int'>
  readonly downloadCount: Prisma.FieldRef<"QuestionPaper", 'Int'>
  readonly published: Prisma.FieldRef<"QuestionPaper", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"QuestionPaper", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"QuestionPaper", 'DateTime'>
}
    

// Custom InputTypes
/**
 * QuestionPaper findUnique
 */
export type QuestionPaperFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaper
   */
  select?: Prisma.QuestionPaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaper
   */
  omit?: Prisma.QuestionPaperOmit<ExtArgs> | null
  /**
   * Filter, which QuestionPaper to fetch.
   */
  where: Prisma.QuestionPaperWhereUniqueInput
}

/**
 * QuestionPaper findUniqueOrThrow
 */
export type QuestionPaperFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaper
   */
  select?: Prisma.QuestionPaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaper
   */
  omit?: Prisma.QuestionPaperOmit<ExtArgs> | null
  /**
   * Filter, which QuestionPaper to fetch.
   */
  where: Prisma.QuestionPaperWhereUniqueInput
}

/**
 * QuestionPaper findFirst
 */
export type QuestionPaperFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaper
   */
  select?: Prisma.QuestionPaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaper
   */
  omit?: Prisma.QuestionPaperOmit<ExtArgs> | null
  /**
   * Filter, which QuestionPaper to fetch.
   */
  where?: Prisma.QuestionPaperWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionPapers to fetch.
   */
  orderBy?: Prisma.QuestionPaperOrderByWithRelationInput | Prisma.QuestionPaperOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuestionPapers.
   */
  cursor?: Prisma.QuestionPaperWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionPapers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionPapers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuestionPapers.
   */
  distinct?: Prisma.QuestionPaperScalarFieldEnum | Prisma.QuestionPaperScalarFieldEnum[]
}

/**
 * QuestionPaper findFirstOrThrow
 */
export type QuestionPaperFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaper
   */
  select?: Prisma.QuestionPaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaper
   */
  omit?: Prisma.QuestionPaperOmit<ExtArgs> | null
  /**
   * Filter, which QuestionPaper to fetch.
   */
  where?: Prisma.QuestionPaperWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionPapers to fetch.
   */
  orderBy?: Prisma.QuestionPaperOrderByWithRelationInput | Prisma.QuestionPaperOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuestionPapers.
   */
  cursor?: Prisma.QuestionPaperWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionPapers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionPapers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuestionPapers.
   */
  distinct?: Prisma.QuestionPaperScalarFieldEnum | Prisma.QuestionPaperScalarFieldEnum[]
}

/**
 * QuestionPaper findMany
 */
export type QuestionPaperFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaper
   */
  select?: Prisma.QuestionPaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaper
   */
  omit?: Prisma.QuestionPaperOmit<ExtArgs> | null
  /**
   * Filter, which QuestionPapers to fetch.
   */
  where?: Prisma.QuestionPaperWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionPapers to fetch.
   */
  orderBy?: Prisma.QuestionPaperOrderByWithRelationInput | Prisma.QuestionPaperOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing QuestionPapers.
   */
  cursor?: Prisma.QuestionPaperWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionPapers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionPapers.
   */
  skip?: number
  distinct?: Prisma.QuestionPaperScalarFieldEnum | Prisma.QuestionPaperScalarFieldEnum[]
}

/**
 * QuestionPaper create
 */
export type QuestionPaperCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaper
   */
  select?: Prisma.QuestionPaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaper
   */
  omit?: Prisma.QuestionPaperOmit<ExtArgs> | null
  /**
   * The data needed to create a QuestionPaper.
   */
  data: Prisma.XOR<Prisma.QuestionPaperCreateInput, Prisma.QuestionPaperUncheckedCreateInput>
}

/**
 * QuestionPaper createMany
 */
export type QuestionPaperCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many QuestionPapers.
   */
  data: Prisma.QuestionPaperCreateManyInput | Prisma.QuestionPaperCreateManyInput[]
}

/**
 * QuestionPaper createManyAndReturn
 */
export type QuestionPaperCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaper
   */
  select?: Prisma.QuestionPaperSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaper
   */
  omit?: Prisma.QuestionPaperOmit<ExtArgs> | null
  /**
   * The data used to create many QuestionPapers.
   */
  data: Prisma.QuestionPaperCreateManyInput | Prisma.QuestionPaperCreateManyInput[]
}

/**
 * QuestionPaper update
 */
export type QuestionPaperUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaper
   */
  select?: Prisma.QuestionPaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaper
   */
  omit?: Prisma.QuestionPaperOmit<ExtArgs> | null
  /**
   * The data needed to update a QuestionPaper.
   */
  data: Prisma.XOR<Prisma.QuestionPaperUpdateInput, Prisma.QuestionPaperUncheckedUpdateInput>
  /**
   * Choose, which QuestionPaper to update.
   */
  where: Prisma.QuestionPaperWhereUniqueInput
}

/**
 * QuestionPaper updateMany
 */
export type QuestionPaperUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update QuestionPapers.
   */
  data: Prisma.XOR<Prisma.QuestionPaperUpdateManyMutationInput, Prisma.QuestionPaperUncheckedUpdateManyInput>
  /**
   * Filter which QuestionPapers to update
   */
  where?: Prisma.QuestionPaperWhereInput
  /**
   * Limit how many QuestionPapers to update.
   */
  limit?: number
}

/**
 * QuestionPaper updateManyAndReturn
 */
export type QuestionPaperUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaper
   */
  select?: Prisma.QuestionPaperSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaper
   */
  omit?: Prisma.QuestionPaperOmit<ExtArgs> | null
  /**
   * The data used to update QuestionPapers.
   */
  data: Prisma.XOR<Prisma.QuestionPaperUpdateManyMutationInput, Prisma.QuestionPaperUncheckedUpdateManyInput>
  /**
   * Filter which QuestionPapers to update
   */
  where?: Prisma.QuestionPaperWhereInput
  /**
   * Limit how many QuestionPapers to update.
   */
  limit?: number
}

/**
 * QuestionPaper upsert
 */
export type QuestionPaperUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaper
   */
  select?: Prisma.QuestionPaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaper
   */
  omit?: Prisma.QuestionPaperOmit<ExtArgs> | null
  /**
   * The filter to search for the QuestionPaper to update in case it exists.
   */
  where: Prisma.QuestionPaperWhereUniqueInput
  /**
   * In case the QuestionPaper found by the `where` argument doesn't exist, create a new QuestionPaper with this data.
   */
  create: Prisma.XOR<Prisma.QuestionPaperCreateInput, Prisma.QuestionPaperUncheckedCreateInput>
  /**
   * In case the QuestionPaper was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QuestionPaperUpdateInput, Prisma.QuestionPaperUncheckedUpdateInput>
}

/**
 * QuestionPaper delete
 */
export type QuestionPaperDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaper
   */
  select?: Prisma.QuestionPaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaper
   */
  omit?: Prisma.QuestionPaperOmit<ExtArgs> | null
  /**
   * Filter which QuestionPaper to delete.
   */
  where: Prisma.QuestionPaperWhereUniqueInput
}

/**
 * QuestionPaper deleteMany
 */
export type QuestionPaperDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuestionPapers to delete
   */
  where?: Prisma.QuestionPaperWhereInput
  /**
   * Limit how many QuestionPapers to delete.
   */
  limit?: number
}

/**
 * QuestionPaper without action
 */
export type QuestionPaperDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaper
   */
  select?: Prisma.QuestionPaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaper
   */
  omit?: Prisma.QuestionPaperOmit<ExtArgs> | null
}
