
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 * 
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/library"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 * 
 * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
 */
export const PrismaClient = $Class.getPrismaClientClass(__dirname)
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }


// file annotations for bundling tools to include these files
path.join(__dirname, "query_engine-windows.dll.node")
path.join(process.cwd(), "lib/prisma-generated/query_engine-windows.dll.node")

/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Page
 * 
 */
export type Page = Prisma.PageModel
/**
 * Model News
 * 
 */
export type News = Prisma.NewsModel
/**
 * Model GalleryAlbum
 * 
 */
export type GalleryAlbum = Prisma.GalleryAlbumModel
/**
 * Model GalleryImage
 * 
 */
export type GalleryImage = Prisma.GalleryImageModel
/**
 * Model Download
 * 
 */
export type Download = Prisma.DownloadModel
/**
 * Model Setting
 * 
 */
export type Setting = Prisma.SettingModel
/**
 * Model Testimonial
 * 
 */
export type Testimonial = Prisma.TestimonialModel
/**
 * Model NoticeBoardEvent
 * 
 */
export type NoticeBoardEvent = Prisma.NoticeBoardEventModel
/**
 * Model NoticeBoardNotice
 * 
 */
export type NoticeBoardNotice = Prisma.NoticeBoardNoticeModel
/**
 * Model CourseApplication
 * 
 */
export type CourseApplication = Prisma.CourseApplicationModel
/**
 * Model FlashNews
 * 
 */
export type FlashNews = Prisma.FlashNewsModel
/**
 * Model HeroSlide
 * 
 */
export type HeroSlide = Prisma.HeroSlideModel
/**
 * Model ShortTermCourse
 * 
 */
export type ShortTermCourse = Prisma.ShortTermCourseModel
/**
 * Model PopupBanner
 * 
 */
export type PopupBanner = Prisma.PopupBannerModel
/**
 * Model PopupImage
 * 
 */
export type PopupImage = Prisma.PopupImageModel
/**
 * Model PopupViewSession
 * 
 */
export type PopupViewSession = Prisma.PopupViewSessionModel
/**
 * Model StaffProfile
 * 
 */
export type StaffProfile = Prisma.StaffProfileModel
/**
 * Model NavigationMenu
 * 
 */
export type NavigationMenu = Prisma.NavigationMenuModel
/**
 * Model QuestionPaper
 * 
 */
export type QuestionPaper = Prisma.QuestionPaperModel
/**
 * Model Syllabus
 * 
 */
export type Syllabus = Prisma.SyllabusModel
/**
 * Model Grievance
 * 
 */
export type Grievance = Prisma.GrievanceModel
/**
 * Model BloodDonor
 * 
 */
export type BloodDonor = Prisma.BloodDonorModel
/**
 * Model AlumniRegistration
 * Public alumni registration submissions (exportable by admin).
 */
export type AlumniRegistration = Prisma.AlumniRegistrationModel
/**
 * Model CommitteeMeta
 * College committees page metadata (academic year, publish status).
 */
export type CommitteeMeta = Prisma.CommitteeMetaModel
/**
 * Model CommitteeExOfficio
 * Global ex-officio members shown at top of committees page.
 */
export type CommitteeExOfficio = Prisma.CommitteeExOfficioModel
/**
 * Model Committee
 * Individual college committee (IQAC, Academic Council, etc.).
 */
export type Committee = Prisma.CommitteeModel
/**
 * Model CommitteeMember
 * 
 */
export type CommitteeMember = Prisma.CommitteeMemberModel
